package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.fi_FI.classes;

import com.runtimeconverter.runtime.references.ReferenceContainer;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.references.BasicReferenceContainer;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.passByReference.RuntimeArgsWithReferences;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.annotations.ConvertedParameter;
import com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.classes.DateTime;
import com.runtimeconverter.runtime.classes.ClassConstantUtils;
import com.runtimeconverter.runtime.arrays.ZPair;
import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.nativeClasses.spl.exceptions.InvalidArgumentException;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.nativeFunctions.string.function_strlen;
import com.runtimeconverter.runtime.classes.StaticMethodUtils;
import com.project.convertedCode.globalNamespace.NamespaceGlobal;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import static com.runtimeconverter.runtime.ZVal.toStringR;
import static com.runtimeconverter.runtime.ZVal.assignParameter;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/fi_FI/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    @ConvertedMethod
    @ConvertedParameter(
        index = 0,
        name = "birthdate",
        typeHint = "DateTime",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    @ConvertedParameter(
        index = 1,
        name = "gender",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    public Object personalIdentityNumber(RuntimeEnv env, Object... args) {
        int runtimeConverterBreakCount;
        Object birthdate = assignParameter(args, 0, true);
        if (null == birthdate) {
            birthdate = ZVal.getNull();
        }
        Object gender = assignParameter(args, 1, true);
        if (null == gender) {
            gender = ZVal.getNull();
        }
        Object randomDigits = null;
        Object datePart = null;
        Object checksum = null;
        ReferenceContainer checksumCharacters = new BasicReferenceContainer(null);
        Object centurySign = null;
        checksumCharacters.setObject("0123456789ABCDEFHJKLMNPRSTUVWXY");
        if (!ZVal.isTrue(birthdate)) {
            birthdate = DateTime.runtimeStaticObject.dateTimeThisCentury(env);
        }

        datePart = env.callMethod(birthdate, "format", Person.class, "dmy");
        SwitchEnumType12 switchVariable12 =
                ZVal.getEnum(
                        ZVal.toLong(
                                ZVal.divide(
                                        env.callMethod(birthdate, "format", Person.class, "Y"),
                                        100)),
                        SwitchEnumType12.DEFAULT_CASE,
                        SwitchEnumType12.INTEGER_18,
                        18,
                        SwitchEnumType12.INTEGER_19,
                        19,
                        SwitchEnumType12.INTEGER_20,
                        20);
        switch (switchVariable12) {
            case INTEGER_18:
                centurySign = "+";
                break;
            case INTEGER_19:
                centurySign = "-";
                break;
            case INTEGER_20:
                centurySign = "A";
                break;
            case DEFAULT_CASE:
                throw ZVal.getException(
                        env,
                        new InvalidArgumentException(
                                env, "Year must be between 1800 and 2099 inclusive."));
        }
        ;
        randomDigits = runtimeStaticObject.numberBetween(env, 0, 89);
        if (ZVal.toBool(gender)
                && ZVal.toBool(
                        ZVal.equalityCheck(
                                gender,
                                ClassConstantUtils.getConstantValueLateStatic(
                                        env, this, "GENDER_MALE")))) {
            if (ZVal.strictEqualityCheck(randomDigits, "===", 0)) {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(
                                        StaticMethodUtils.accessUnknownLateStaticMethod(
                                                        env, this, Person.class)
                                                .method("randomElement")
                                                .addReferenceArgs(new RuntimeArgsWithReferences())
                                                .call(ZVal.arrayFromList(3, 5, 7, 9))
                                                .value(),
                                        env);

            } else {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(
                                        StaticMethodUtils.accessUnknownLateStaticMethod(
                                                        env, this, Person.class)
                                                .method("randomElement")
                                                .addReferenceArgs(new RuntimeArgsWithReferences())
                                                .call(ZVal.arrayFromList(1, 3, 5, 7, 9))
                                                .value(),
                                        env);
            }

        } else if (ZVal.toBool(gender)
                && ZVal.toBool(
                        ZVal.equalityCheck(
                                gender,
                                ClassConstantUtils.getConstantValueLateStatic(
                                        env, this, "GENDER_FEMALE")))) {
            if (ZVal.strictEqualityCheck(randomDigits, "===", 0)) {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(
                                        StaticMethodUtils.accessUnknownLateStaticMethod(
                                                        env, this, Person.class)
                                                .method("randomElement")
                                                .addReferenceArgs(new RuntimeArgsWithReferences())
                                                .call(ZVal.arrayFromList(2, 4, 6, 8))
                                                .value(),
                                        env);

            } else {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(
                                        StaticMethodUtils.accessUnknownLateStaticMethod(
                                                        env, this, Person.class)
                                                .method("randomElement")
                                                .addReferenceArgs(new RuntimeArgsWithReferences())
                                                .call(ZVal.arrayFromList(0, 2, 4, 6, 8))
                                                .value(),
                                        env);
            }

        } else {
            if (ZVal.strictEqualityCheck(randomDigits, "===", 0)) {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(runtimeStaticObject.numberBetween(env, 2, 9), env);

            } else {
                randomDigits =
                        toStringR(randomDigits, env)
                                + toStringR(
                                        toStringR(
                                                StaticMethodUtils.accessUnknownLateStaticMethod(
                                                                env, this, Person.class)
                                                        .method("numerify")
                                                        .addReferenceArgs(
                                                                new RuntimeArgsWithReferences())
                                                        .call("#")
                                                        .value(),
                                                env),
                                        env);
            }
        }

        randomDigits = NamespaceGlobal.str_pad.env(env).call(randomDigits, 3, "0", 0).value();
        checksum =
                ZVal.assign(
                        checksumCharacters.arrayGet(
                                env,
                                ZVal.modulus(
                                        ZVal.toLong(
                                                toStringR(datePart, env)
                                                        + toStringR(randomDigits, env)),
                                        function_strlen
                                                .f
                                                .env(env)
                                                .call(checksumCharacters.getObject())
                                                .value())));
        return ZVal.assign(
                toStringR(datePart, env)
                        + toStringR(centurySign, env)
                        + toStringR(randomDigits, env)
                        + toStringR(checksum, env));
    }

    public static final Object CONST_class = "Faker\\Provider\\fi_FI\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object maleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}}");

        public Object femaleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}}");

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aleksi",
                                    "Anssi",
                                    "Antero",
                                    "Antti",
                                    "Ari",
                                    "Arttu",
                                    "Daniel",
                                    "Eero",
                                    "Eetu",
                                    "Elias",
                                    "Elmo",
                                    "Emil",
                                    "Erkki",
                                    "Hampus",
                                    "Hannu",
                                    "Harri",
                                    "Heikki",
                                    "Helmi",
                                    "Henri",
                                    "Hermanni",
                                    "Ilja",
                                    "Jaakko",
                                    "Jake",
                                    "Jani",
                                    "Janne",
                                    "Jari",
                                    "Jarno",
                                    "Jere",
                                    "Jeremy",
                                    "Jesper",
                                    "Jesse",
                                    "Jimi",
                                    "Joakim",
                                    "Joel",
                                    "Joona",
                                    "Joonas",
                                    "Juha",
                                    "Juho",
                                    "Jukka",
                                    "Julius",
                                    "Jussi",
                                    "Justus",
                                    "Juuso",
                                    "Kalle",
                                    "Kasperi",
                                    "Konsta",
                                    "Kristian",
                                    "Lassi",
                                    "Leevi",
                                    "Leo",
                                    "Levin",
                                    "Luca",
                                    "Lukas",
                                    "Magnus",
                                    "Marko",
                                    "Markus",
                                    "Matias",
                                    "Matti",
                                    "Miika",
                                    "Mika",
                                    "Mikael",
                                    "Mikko",
                                    "Neo",
                                    "Nico",
                                    "Niklas",
                                    "Niko",
                                    "Oliver",
                                    "Oskari",
                                    "Ossi",
                                    "Otto",
                                    "Paavo",
                                    "Pasi",
                                    "Patrik",
                                    "Paulus",
                                    "Peetu",
                                    "Pekka",
                                    "Pertti",
                                    "Petri",
                                    "Petteri",
                                    "Pyry",
                                    "Rami",
                                    "Rasmus",
                                    "Riku",
                                    "Risto",
                                    "Roope",
                                    "Saku",
                                    "Sami",
                                    "Samu",
                                    "Samuel",
                                    "Samuli",
                                    "Santeri",
                                    "Taneli",
                                    "Tatu",
                                    "Teemu",
                                    "Teppo",
                                    "Tero",
                                    "Timo",
                                    "Tomi",
                                    "Tommi",
                                    "Topi",
                                    "Touko",
                                    "Tuomas",
                                    "Tuomo",
                                    "Tuukka",
                                    "Tuukka",
                                    "Valtteri",
                                    "Veli",
                                    "Viljo",
                                    "Ville",
                                    "Aake",
                                    "Aapeli",
                                    "Aapo",
                                    "Aappo",
                                    "Aarni",
                                    "Aaro",
                                    "Aatto",
                                    "Aatu",
                                    "Akseli",
                                    "Aku",
                                    "Antton",
                                    "Artturi",
                                    "Aune",
                                    "Beeda",
                                    "Briitta",
                                    "Eeli",
                                    "Eelis",
                                    "Eemeli",
                                    "Ekku",
                                    "Eljas",
                                    "Erkko",
                                    "Iiro",
                                    "Ilmari",
                                    "Isto",
                                    "Jirko",
                                    "Joonatan",
                                    "Jore",
                                    "Junnu",
                                    "Jusu",
                                    "Kaste",
                                    "Kauto",
                                    "Luukas",
                                    "Nuutti",
                                    "Onni",
                                    "Osmo",
                                    "Pekko",
                                    "Sampo",
                                    "Santtu",
                                    "Sauli",
                                    "Simo",
                                    "Sisu",
                                    "Teijo",
                                    "Unto",
                                    "Urho",
                                    "Veeti",
                                    "Veikko",
                                    "Vilho",
                                    "Werneri",
                                    "Wiljami");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aada",
                                    "Ada",
                                    "Aina",
                                    "Aino",
                                    "Aki",
                                    "Aliisa",
                                    "Amalia",
                                    "Amanda",
                                    "Amelia",
                                    "Amira",
                                    "Anissa",
                                    "Anita",
                                    "Anna",
                                    "Anne",
                                    "Anni",
                                    "Anniina",
                                    "Annu",
                                    "Anu",
                                    "Asta",
                                    "Atte",
                                    "Atte",
                                    "Aura",
                                    "Aurora",
                                    "Bella",
                                    "Cara",
                                    "Celina",
                                    "Christa",
                                    "Christel",
                                    "Clara",
                                    "Cornelia",
                                    "Dani",
                                    "Eija",
                                    "Elea",
                                    "Elina",
                                    "Elisa",
                                    "Elise",
                                    "Ella",
                                    "Ellen",
                                    "Elma",
                                    "Emilia",
                                    "Emma",
                                    "Emmi",
                                    "Enna",
                                    "Erja",
                                    "Esa",
                                    "Essi",
                                    "Eva",
                                    "Eveliina",
                                    "Fanni",
                                    "Fiona",
                                    "Hanna",
                                    "Heidi",
                                    "Heli",
                                    "Helin\u00E4",
                                    "Henna",
                                    "Hilda",
                                    "Hilja",
                                    "Hilla",
                                    "Hilma",
                                    "Iida",
                                    "Iina",
                                    "Iiris",
                                    "Ilona",
                                    "Inka",
                                    "Inkeri",
                                    "Inna",
                                    "Isabella",
                                    "Jade",
                                    "Jami",
                                    "Janette",
                                    "Janika",
                                    "Janina",
                                    "Janita",
                                    "Janna",
                                    "Janni",
                                    "Jasmiina",
                                    "Jenna",
                                    "Jenni",
                                    "Jessica",
                                    "Johanna",
                                    "Joni",
                                    "Jonna",
                                    "Julia",
                                    "Juulia",
                                    "Kaija",
                                    "Karla",
                                    "Karri",
                                    "Kati",
                                    "Katja",
                                    "Katri",
                                    "Kia",
                                    "Kimi",
                                    "Kirsi",
                                    "Krista",
                                    "Lari",
                                    "Laura",
                                    "Lauri",
                                    "Lea",
                                    "Lila",
                                    "Linnea",
                                    "Lotta",
                                    "Lumina",
                                    "Maarit",
                                    "Maia",
                                    "Maija",
                                    "Maiju",
                                    "Maisa",
                                    "Mari",
                                    "Maria",
                                    "Meeri",
                                    "Meri",
                                    "Mette",
                                    "Mia",
                                    "Milla",
                                    "Mimi",
                                    "Mimosa",
                                    "Minna",
                                    "Mira",
                                    "Mirella",
                                    "Miska",
                                    "Nadja",
                                    "Natalia",
                                    "Nea",
                                    "Neea",
                                    "Nella",
                                    "Nia",
                                    "Niina",
                                    "Noora",
                                    "Olga",
                                    "Olivia",
                                    "Oona",
                                    "Outi",
                                    "Paula",
                                    "Pauliina",
                                    "Petra",
                                    "Pia",
                                    "Piia",
                                    "Pinja",
                                    "P\u00E4ivi",
                                    "Reeta",
                                    "Reetta",
                                    "Riikka",
                                    "Riina",
                                    "Ritva",
                                    "Roni",
                                    "Ronja",
                                    "Sanna",
                                    "Sari",
                                    "Satu",
                                    "Seija",
                                    "Sirpa",
                                    "Siru",
                                    "Susanna",
                                    "Tanja",
                                    "Tara",
                                    "Taru",
                                    "Tea",
                                    "Terhi",
                                    "Tiia",
                                    "Tiina",
                                    "Tiiu",
                                    "Tinja",
                                    "Veera",
                                    "Vili",
                                    "Vilma",
                                    "Wilma",
                                    "Aamu",
                                    "Aliina",
                                    "Annilotta",
                                    "Eerika",
                                    "Eeva",
                                    "Eevi",
                                    "Eliina",
                                    "Elviira",
                                    "Emmaliina",
                                    "Enni",
                                    "Ennika",
                                    "Helmiina",
                                    "Henniina",
                                    "Hertta",
                                    "Hilppa",
                                    "Iia",
                                    "Iita",
                                    "Jadessa",
                                    "Jemina",
                                    "Jenika",
                                    "Jermia",
                                    "Jooa",
                                    "Juttamari",
                                    "Kaisla",
                                    "Kaisu",
                                    "Loviisa",
                                    "Malla",
                                    "Martta",
                                    "Matleena",
                                    "Miina",
                                    "Mimmu",
                                    "Minea",
                                    "Minttu",
                                    "Mirva",
                                    "Nelli",
                                    "Ninni",
                                    "Oliivia",
                                    "Peppi",
                                    "Pihla",
                                    "Pirkko",
                                    "Riia",
                                    "Roosa",
                                    "Taika",
                                    "Venla",
                                    "Viivi",
                                    "Vilja");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aakula",
                                    "Aalto",
                                    "Aaltonen",
                                    "Aarnio",
                                    "Aaronen",
                                    "Aavikkola",
                                    "Ahmala",
                                    "Aho",
                                    "Ahokas",
                                    "Ahola",
                                    "Ahomaa",
                                    "Ahonen",
                                    "Ahoniemi",
                                    "Ahopelto",
                                    "Ahovaara",
                                    "Ahtila",
                                    "Ahtiluoto",
                                    "Ahtio",
                                    "Ahtisaari",
                                    "Ahto",
                                    "Ahtola",
                                    "Ahtonen",
                                    "Ahtorinne",
                                    "Aija",
                                    "Aijala",
                                    "Ainola",
                                    "Aitio",
                                    "Aitolahti",
                                    "Aitomaa",
                                    "Aittasalmi",
                                    "Akkala",
                                    "Akkanen",
                                    "Alahuhta",
                                    "Alajoki",
                                    "Alaj\u00E4rvi",
                                    "Alanen",
                                    "Alatalo",
                                    "Alasalmi",
                                    "Alapuro",
                                    "Alhola",
                                    "Alijoki",
                                    "Ankkala",
                                    "Ankkuri",
                                    "Annala",
                                    "Annunen",
                                    "Anttila",
                                    "Anttinen",
                                    "Anttonen",
                                    "Ara",
                                    "Arhila",
                                    "Arhinm\u00E4ki",
                                    "Arhosuo",
                                    "Arinen",
                                    "Arjamaa",
                                    "Arjanen",
                                    "Arkkila",
                                    "Armio",
                                    "Arnio",
                                    "Aronen",
                                    "Arosuo",
                                    "Arponen",
                                    "Arvola",
                                    "Asikainen",
                                    "Astala",
                                    "Attila",
                                    "Aunela",
                                    "Aura",
                                    "Auramies",
                                    "Auranen",
                                    "Autio",
                                    "Auvinen",
                                    "Auvola",
                                    "Avonius",
                                    "Avotie",
                                    "Br\u00E4ysy",
                                    "Davidsainen",
                                    "Dufva",
                                    "Eerik\u00E4inen",
                                    "Eerola",
                                    "Einel",
                                    "Eino",
                                    "Einola",
                                    "Einonen",
                                    "Ekman",
                                    "Ekola",
                                    "Ellil\u00E4",
                                    "Ellinen",
                                    "Elomaa",
                                    "Eloharju",
                                    "Eloranta",
                                    "Eno",
                                    "Enola",
                                    "En\u00E4j\u00E4rvi",
                                    "Erkinjuntti",
                                    "Erkkil\u00E4",
                                    "Erkkinen",
                                    "Erkko",
                                    "Erkkola",
                                    "Ernamo",
                                    "Erola",
                                    "Eronen",
                                    "Ervola",
                                    "Er\u00E4harju",
                                    "Er\u00E4maja",
                                    "Er\u00E4nen",
                                    "Eskelinen",
                                    "Eskel\u00E4",
                                    "Eskola",
                                    "Evel\u00E4",
                                    "Evil\u00E4",
                                    "Filppula",
                                    "Finni",
                                    "Fr\u00E4ndil\u00E4",
                                    "Fr\u00E4nti",
                                    "Haahka",
                                    "Haahkola",
                                    "Haanp\u00E4\u00E4",
                                    "Haapakorpi",
                                    "Haapala",
                                    "Haapanen",
                                    "Haaparanta",
                                    "Haapasalmi",
                                    "Haapasalo",
                                    "Haapkyl\u00E4",
                                    "Haapoja",
                                    "Haataja",
                                    "Haavisto",
                                    "Haikala",
                                    "Haikara",
                                    "Hakala",
                                    "Hakkarainen",
                                    "Hakki",
                                    "Hakula",
                                    "Halinen",
                                    "Halkola",
                                    "Halkonen",
                                    "Halla",
                                    "Hallaper",
                                    "Hallapuro",
                                    "Hallikainen",
                                    "Hallila",
                                    "Hallonen",
                                    "Halme",
                                    "Halmela",
                                    "Halmelahti",
                                    "Halonen",
                                    "Halttunen",
                                    "Hammas",
                                    "Hanhela",
                                    "Hanhinen",
                                    "Hannula",
                                    "Hannunen",
                                    "Hapola",
                                    "Harjam\u00E4ki",
                                    "Harju",
                                    "Harjula",
                                    "Harjunp\u00E4\u00E4",
                                    "Harkimo",
                                    "Hautakangas",
                                    "Hautakoski",
                                    "Hautala",
                                    "Hautam\u00E4ki",
                                    "Haverinen",
                                    "Havukoski",
                                    "Heikkil\u00E4",
                                    "Heikkinen",
                                    "Heimola",
                                    "Hein\u00E4l\u00E4",
                                    "Heiskanen",
                                    "Heiskari",
                                    "Helenius",
                                    "Helinen",
                                    "Helismaa",
                                    "Helmel",
                                    "Helovirta",
                                    "Helppolainen",
                                    "Helstel",
                                    "Hellgren",
                                    "Hentinen",
                                    "Hento",
                                    "Hepom\u00E4ki",
                                    "Heponen",
                                    "Herranen",
                                    "Hervanta",
                                    "Hervanto",
                                    "Hekkaharju",
                                    "Hiesu",
                                    "Hietala",
                                    "Hietanen",
                                    "Hiltunen",
                                    "Heintikainen",
                                    "Hirvel\u00E4",
                                    "Hirvi",
                                    "Hirvikangas",
                                    "Hirvonen",
                                    "Hoikkala",
                                    "Hoikkanen",
                                    "Holappa",
                                    "Holkeri",
                                    "Hongisto",
                                    "Honkanen",
                                    "Hovi",
                                    "Huhta",
                                    "Huhtala",
                                    "Hukkala",
                                    "Huopainen",
                                    "Huotari",
                                    "Huovinen",
                                    "Huttunen",
                                    "Huuhka",
                                    "Huurinainen",
                                    "Huusko",
                                    "Huvinen",
                                    "Hypp\u00F6l\u00E4",
                                    "Hypp\u00F6nen",
                                    "Hyt\u00F6l\u00E4",
                                    "Hyypi\u00E4",
                                    "Hyypp\u00E4",
                                    "H\u00E4kkinen",
                                    "H\u00E4k\u00E4mies",
                                    "H\u00E4m\u00E4l\u00E4inen",
                                    "H\u00E4nninen",
                                    "H\u00E4rk\u00F6nen",
                                    "Ihalainen",
                                    "Ikola",
                                    "Ikonen",
                                    "Ilmarinen",
                                    "Ilom\u00E4ki",
                                    "Iloniemi",
                                    "Ilvesniemi",
                                    "Immonen",
                                    "Inkeri",
                                    "Inkinen",
                                    "Isoluoma",
                                    "Isom\u00E4ki",
                                    "Isotalo",
                                    "Itkonen",
                                    "It\u00E4vaara",
                                    "It\u00E4vuori",
                                    "Jaakkola",
                                    "Jaakkonen",
                                    "Jaakonmaa",
                                    "Jaatinen",
                                    "Jakkila",
                                    "Jalonen",
                                    "Jauhiainen",
                                    "Jauho",
                                    "Joenhaara",
                                    "Johto",
                                    "Jokelainen",
                                    "Jokihaara",
                                    "Jokimies",
                                    "Jokinen",
                                    "Jortikka",
                                    "Joru",
                                    "Junkkari",
                                    "Juntti",
                                    "Juppi",
                                    "Jurva",
                                    "Jurvala",
                                    "Jurvanen",
                                    "Jussila",
                                    "Juustinen",
                                    "Juuti",
                                    "Juvanen",
                                    "Juvonen",
                                    "Jylh\u00E4",
                                    "J\u00E4nis",
                                    "J\u00E4ppinen",
                                    "J\u00E4rvel\u00E4",
                                    "J\u00E4\u00E4skel\u00E4inen",
                                    "Kaakko",
                                    "Kaikkonen",
                                    "Kainulainen",
                                    "Kaista",
                                    "Kaivola",
                                    "Kakkola",
                                    "Kakkonen",
                                    "Kalinainen",
                                    "Kalkkinen",
                                    "Kalliala",
                                    "Kallio",
                                    "Kaillom\u00E4ki",
                                    "Kalmo",
                                    "Kalvo",
                                    "Kamari",
                                    "Kamppinen",
                                    "Kanala",
                                    "Kangaskorte",
                                    "Kangassalo",
                                    "Kannelmaa",
                                    "Kannelm\u00E4ki",
                                    "Kantele",
                                    "Kantola",
                                    "Kapanen",
                                    "Karalahti",
                                    "Karhu",
                                    "Karjalainen",
                                    "Karpela",
                                    "Karppinen",
                                    "Karukoski",
                                    "Karvonen",
                                    "Katainen",
                                    "Kataja",
                                    "Kauhala",
                                    "Kaukovaara",
                                    "Kauppala",
                                    "Kauppinen",
                                    "Kaurism\u00E4ki",
                                    "Kekkonen",
                                    "Kerava",
                                    "Kerttula",
                                    "Keskinen",
                                    "Keskioja",
                                    "Ketola",
                                    "Ketonen",
                                    "Kettula",
                                    "Kieli",
                                    "Kiianen",
                                    "Kiille",
                                    "Kimalainen",
                                    "Kiiski",
                                    "Kinnula",
                                    "Kinnunen",
                                    "Kiskonen",
                                    "Kissala",
                                    "Kivi",
                                    "Kiviniemi",
                                    "Kivist\u00F6",
                                    "Koirala",
                                    "Koivisto",
                                    "Koivula",
                                    "Koivulehto",
                                    "Koivuniemi",
                                    "Kokkonen",
                                    "Kolehmainen",
                                    "Komulainen",
                                    "Konttinen",
                                    "Kontunen",
                                    "Korhonen",
                                    "Koriseva",
                                    "Kortesj\u00E4rvi",
                                    "Koskela",
                                    "Koskelainen",
                                    "Kosonen",
                                    "Kotanen",
                                    "Koukkula",
                                    "Kouvonen",
                                    "Kovalainen",
                                    "Krapu",
                                    "Krekel\u00E4",
                                    "Kujala",
                                    "Kujanp\u00E4\u00E4",
                                    "Kukkala",
                                    "Kukkam\u00E4ki",
                                    "Kukkonen",
                                    "Kultala",
                                    "Kumpula",
                                    "Kumpulainen",
                                    "Kunnas",
                                    "Kuoppala",
                                    "Kuosmanen",
                                    "Kurkela",
                                    "Kurki",
                                    "Kuusij\u00E4rvi",
                                    "Kyll\u00F6nen",
                                    "Kynsij\u00E4rvi",
                                    "Kynsilehto",
                                    "K\u00E4rki",
                                    "K\u00E4rkk\u00E4inen",
                                    "Laakkola",
                                    "Laakkonen",
                                    "Laakso",
                                    "Laaksonen",
                                    "Laatikainen",
                                    "Lahdenp\u00E4\u00E4",
                                    "Laine",
                                    "Lainela",
                                    "Lakka",
                                    "Lampinen",
                                    "Lappalainen",
                                    "Lassinen",
                                    "Laurila",
                                    "Lauronen",
                                    "Lavola",
                                    "Lehm\u00E4l\u00E4",
                                    "Lehtim\u00E4ki",
                                    "Lehtinen",
                                    "Lehtisalo",
                                    "Lehto",
                                    "Lehtonen",
                                    "Leino",
                                    "Lepist\u00F6",
                                    "Lepom\u00E4ki",
                                    "Leppilampi",
                                    "Lepp\u00E4korpi",
                                    "Lepp\u00E4l\u00E4",
                                    "Lepp\u00E4virta",
                                    "Leskinen",
                                    "Liimatainen",
                                    "Lind",
                                    "Linnala",
                                    "Linnam\u00E4ki",
                                    "Lippo",
                                    "Litmanen",
                                    "Litvala",
                                    "Liukkonen",
                                    "Loiri",
                                    "Lukkari",
                                    "Lumme",
                                    "Luoma",
                                    "Luukkonen",
                                    "Lyly",
                                    "Lyytik\u00E4inen",
                                    "L\u00E4hteenm\u00E4ki",
                                    "L\u00E4ms\u00E4",
                                    "Maahinen",
                                    "Made",
                                    "Maijala",
                                    "Makkonen",
                                    "Malmi",
                                    "Malmivaara",
                                    "Mannila",
                                    "Manninen",
                                    "Mannonen",
                                    "Mansikka-aho",
                                    "Mansikkaoja",
                                    "Marila",
                                    "Marjala",
                                    "Marjam\u00E4ki",
                                    "Marjola",
                                    "Marjomaa",
                                    "Marjonen",
                                    "Markkanen",
                                    "Markkula",
                                    "Markuksela",
                                    "Markus",
                                    "Martikainen",
                                    "Marttinen",
                                    "Masala",
                                    "Masanen",
                                    "Matom\u00E4ki",
                                    "Mattila",
                                    "Maunula",
                                    "Maunola",
                                    "Melasniemi",
                                    "Merel\u00E4",
                                    "Meril\u00E4",
                                    "Meril\u00E4inen",
                                    "Merimaa",
                                    "Metsoja",
                                    "Mets\u00E4lampi",
                                    "Mets\u00E4oja",
                                    "Mielonen",
                                    "Miettinen",
                                    "Mikkola",
                                    "Mikkonen",
                                    "Muhonen",
                                    "Mujunen",
                                    "Murola",
                                    "Mustap\u00E4\u00E4",
                                    "Mustonen",
                                    "Muurinen",
                                    "Myllym\u00E4ki",
                                    "Myllypuro",
                                    "Myllys",
                                    "Myll\u00E4ri",
                                    "M\u00E4enp\u00E4\u00E4",
                                    "M\u00E4kel\u00E4",
                                    "M\u00E4ki",
                                    "M\u00E4kinen",
                                    "M\u00E4ntyl\u00E4",
                                    "M\u00E4\u00E4tt\u00E4",
                                    "M\u00F6tt\u00F6nen",
                                    "Naula",
                                    "Naulap\u00E4\u00E4",
                                    "Neuvonen",
                                    "Nevala",
                                    "Niemel\u00E4",
                                    "Niemi",
                                    "Nieminen",
                                    "Niemist\u00F6",
                                    "Niinimaa",
                                    "Niinist\u00F6",
                                    "Niiranen",
                                    "Nikkanen",
                                    "Nikkil\u00E4",
                                    "Nikula",
                                    "Nikulainen",
                                    "Niskala",
                                    "Nisukangas",
                                    "Niukkanen",
                                    "Nokelainen",
                                    "Nokkonen",
                                    "Notkonen",
                                    "Nousiainen",
                                    "Nukka",
                                    "Nummelin",
                                    "Nuotio",
                                    "Nurkkala",
                                    "Nurmela",
                                    "Nurmi",
                                    "Nurminiemi",
                                    "Nurminen",
                                    "Nuutti",
                                    "Nyk\u00E4nen",
                                    "Nyman",
                                    "N\u00E4rv\u00E4l\u00E4",
                                    "N\u00E4\u00E4t\u00E4nen",
                                    "Oikkonen",
                                    "Oikonen",
                                    "Oinonen",
                                    "Oja",
                                    "Ojala",
                                    "Ojam\u00E4ki",
                                    "Ojanen",
                                    "Ojaniemi",
                                    "Oksala",
                                    "Oksanen",
                                    "Ollikainen",
                                    "Ollila",
                                    "Ollinen",
                                    "Oravainen",
                                    "Oravala",
                                    "Otsamo",
                                    "Outinen",
                                    "Ovaska",
                                    "Paajanen",
                                    "Paakkanen",
                                    "Paananen",
                                    "Paasikivi",
                                    "Paasilinna",
                                    "Paasonen",
                                    "Paavola",
                                    "Pahajoki",
                                    "Pahkasalo",
                                    "Pajum\u00E4ki",
                                    "Pajunen",
                                    "Pakarinen",
                                    "Pakkala",
                                    "Pakola",
                                    "Pallas",
                                    "Paloheimo",
                                    "Palola",
                                    "Palom\u00E4ki",
                                    "Parkkonen",
                                    "Pekkala",
                                    "Pekkarinen",
                                    "Pelkonen",
                                    "Peltomaa",
                                    "Pennanen",
                                    "Pennil\u00E4",
                                    "Pentik\u00E4inen",
                                    "Penttil\u00E4",
                                    "Perni\u00F6",
                                    "Pesola",
                                    "Pesonen",
                                    "Peuranen",
                                    "Peuraniemi",
                                    "Pietil\u00E4",
                                    "Piippola",
                                    "Piirainen",
                                    "Pikkarainen",
                                    "Pirttij\u00E4rvi",
                                    "Pirttikangas",
                                    "Pitk\u00E4m\u00E4ki",
                                    "Pohtamo",
                                    "Porkkala",
                                    "Poronen",
                                    "Poropudas",
                                    "Puhakainen\u00E4",
                                    "Puhakka",
                                    "Pukkila",
                                    "Pulli",
                                    "Puolakka",
                                    "Puuper\u00E4",
                                    "Pyykk\u00F6",
                                    "Pyykk\u00F6nen",
                                    "P\u00E4iv\u00E4l\u00E4",
                                    "P\u00E4iv\u00E4rinta",
                                    "P\u00E4\u00E4kk\u00F6nen",
                                    "P\u00F6ll\u00F6nen",
                                    "P\u00F6ntinen",
                                    "P\u00F6ysti",
                                    "Raappana",
                                    "Raatikainen",
                                    "Raatila",
                                    "Rahka",
                                    "Rahkala",
                                    "Raiskio",
                                    "Raitanen",
                                    "Raittila",
                                    "Rajam\u00E4ki",
                                    "Ramu",
                                    "Ranta",
                                    "Rantamaa",
                                    "Rapala",
                                    "Rasila",
                                    "Rasmus",
                                    "Rauhala",
                                    "Rauhanen",
                                    "Rautaporras",
                                    "Rautavirta",
                                    "Rautio",
                                    "Rehu",
                                    "Reinikainen",
                                    "Reinikka",
                                    "Rekomaa",
                                    "Repo",
                                    "Repola",
                                    "Riihim\u00E4ki",
                                    "Riikonen",
                                    "Rimmanen",
                                    "Rinne",
                                    "Rinta",
                                    "Rintam\u00E4ki",
                                    "Ristil\u00E4",
                                    "Ritari",
                                    "Rokko",
                                    "Ronkainen",
                                    "Roponen",
                                    "Ruhanen",
                                    "Rumpunen",
                                    "Runtti",
                                    "Ruohoniemi",
                                    "Ruonala",
                                    "Ruonansuu",
                                    "Ruotsalainen",
                                    "Ruuhonen",
                                    "Ruuskari",
                                    "Ruusula",
                                    "Ruutti",
                                    "Ryh\u00E4nen",
                                    "Ryti",
                                    "Ryysyl\u00E4inen",
                                    "R\u00E4ikk\u00F6nen",
                                    "R\u00E4is\u00E4nen",
                                    "R\u00E4s\u00E4nen",
                                    "Saanila",
                                    "Saarela",
                                    "Saarenheimo",
                                    "Saari",
                                    "Saarikivi",
                                    "Saarnio",
                                    "Saarnivaara",
                                    "Saastamoinen",
                                    "Saikkonen",
                                    "Saksala",
                                    "Salenius",
                                    "Salmela",
                                    "Salmelainen",
                                    "Salo",
                                    "Salolainen",
                                    "Salonen",
                                    "Saloranta",
                                    "Samulin",
                                    "Sannala",
                                    "Santanen",
                                    "Saraste",
                                    "Sarasvuo",
                                    "Saukko",
                                    "Savioja",
                                    "Savolainen",
                                    "Sel\u00E4nne",
                                    "Seppelin",
                                    "Sepp\u00E4nen",
                                    "Sepp\u00E4l\u00E4",
                                    "Servo",
                                    "Set\u00E4nen",
                                    "Siekkinen",
                                    "Sievinen",
                                    "Sihvonen",
                                    "Siira",
                                    "Siltonen",
                                    "Sikala",
                                    "Silakka",
                                    "Sillanp\u00E4\u00E4",
                                    "Siltala",
                                    "Silvennoinen",
                                    "Simo",
                                    "Simonen",
                                    "Sinnem\u00E4ki",
                                    "Sipil\u00E4",
                                    "Sipola",
                                    "Sirkesalo",
                                    "Sirvi\u00F6",
                                    "Raiski",
                                    "Soikkeli",
                                    "Soini",
                                    "Sonninen",
                                    "Soppela",
                                    "Sorajoki",
                                    "Sormunen",
                                    "Sorsa",
                                    "Suhonen",
                                    "Suikkala",
                                    "Summanen",
                                    "Suomela",
                                    "Suominen",
                                    "Suosalo",
                                    "Susiluoto",
                                    "Sutinen",
                                    "Suuronen",
                                    "Suutarinen",
                                    "Suvela",
                                    "Syd\u00E4nm\u00E4ki",
                                    "Syrj\u00E4",
                                    "Syrj\u00E4l\u00E4",
                                    "S\u00E4kkinen",
                                    "S\u00E4rkk\u00E4",
                                    "Taavettila",
                                    "Taavila",
                                    "Taavitsainen",
                                    "Taipale",
                                    "Takkala",
                                    "Takkula",
                                    "Tamminen",
                                    "Tammisto",
                                    "Tanskanen",
                                    "Tapio",
                                    "Tapola",
                                    "Tarvainen",
                                    "Taskinen",
                                    "Tastula",
                                    "Tauriainen",
                                    "Tenkanen",
                                    "Teppo",
                                    "Tervo",
                                    "Tervonen",
                                    "Ter\u00E4sniska",
                                    "Tiainen",
                                    "Tiilikainen",
                                    "Timonen",
                                    "Toijala",
                                    "Toikkanen",
                                    "Toivanen",
                                    "Tokkola",
                                    "Tolonen",
                                    "Torkkeli",
                                    "Tuisku",
                                    "Tukiainen",
                                    "Tulkki",
                                    "Tuomela",
                                    "Tuominen",
                                    "Tuomisto",
                                    "Tuppurainen",
                                    "Turpeinen",
                                    "Turunen",
                                    "Tuutti",
                                    "Tynkkynen",
                                    "Typp\u00F6",
                                    "Tyrninen",
                                    "T\u00F6rr\u00F6",
                                    "T\u00F6rr\u00F6nen",
                                    "Ukkola",
                                    "Ulvila",
                                    "Unhola",
                                    "Uosukainen",
                                    "Urhonen",
                                    "Uronen",
                                    "Urpalainen",
                                    "Urpilainen",
                                    "Utriainen",
                                    "Uusikari",
                                    "Uusikyl\u00E4",
                                    "Uusisalmi",
                                    "Uusitalo",
                                    "Vaara",
                                    "Vahala",
                                    "Vahanen",
                                    "Vahvanen",
                                    "Vainio",
                                    "Valjakka",
                                    "Valo",
                                    "Valtanen",
                                    "Vanhanen",
                                    "Vanhoja",
                                    "Varjus",
                                    "Vartiainen",
                                    "Vasala",
                                    "Vauhkonen",
                                    "Veijonen",
                                    "Veini",
                                    "Vennala",
                                    "Vennamo",
                                    "Veps\u00E4l\u00E4inen",
                                    "Vesa",
                                    "Vesuri",
                                    "Vetel\u00E4inen",
                                    "Vierikko",
                                    "Vihtanen",
                                    "Viikate",
                                    "Viinanen",
                                    "Viinikka",
                                    "Vilhola",
                                    "Viljanen",
                                    "Vilkkula",
                                    "Vilpas",
                                    "Virkkula",
                                    "Virkkunen",
                                    "Virolainen",
                                    "Virtala",
                                    "Voutilainen",
                                    "Vuokko",
                                    "Vuorenp\u00E4\u00E4",
                                    "Vuorikoski",
                                    "Vuorinen",
                                    "V\u00E4h\u00E4l\u00E4",
                                    "V\u00E4is\u00E4l\u00E4",
                                    "V\u00E4is\u00E4nen",
                                    "V\u00E4limaa",
                                    "V\u00E4lioja",
                                    "V\u00E4yrynen",
                                    "V\u00E4\u00E4t\u00E4nen",
                                    "Wettenranta",
                                    "Wiitanen",
                                    "Wirtanen",
                                    "Wiskari",
                                    "Ylij\u00E4l\u00E4",
                                    "Yliannala",
                                    "Ylijoki",
                                    "Ylikangas",
                                    "Ylioja",
                                    "Ylitalo",
                                    "Ylpp\u00F6",
                                    "Yl\u00E4joki",
                                    "Yrj\u00E4nen",
                                    "Yrj\u00E4n\u00E4",
                                    "Yrj\u00F6l\u00E4",
                                    "Yrttiaho",
                                    "Y\u00F6maa",
                                    "\u00C4ij\u00E4l\u00E4",
                                    "\u00C4mm\u00E4l\u00E4",
                                    "\u00C4n\u00E4kk\u00E4l\u00E4",
                                    "\u00C4yr\u00E4s",
                                    "\u00C4\u00E4rynen",
                                    "\u00D6versti",
                                    "\u00D6ysti",
                                    "\u00D6\u00F6rni");
                        });

        public Object titleMale = ZVal.arrayFromList("Hra.", "Tri.");

        public Object titleFemale = ZVal.arrayFromList("Rva.", "Nti.", "Tri.");
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\fi_FI\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats",
                            "titleFemale",
                            "titleMale")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/fi_FI/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }

    private enum SwitchEnumType12 {
        INTEGER_18,
        INTEGER_19,
        INTEGER_20,
        DEFAULT_CASE,
        UNREACHABLE_CODE_N42
    }
}
