package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.zh_CN.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/zh_CN/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\zh_CN\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object maleNameFormats = ZVal.arrayFromList("{{lastName}}{{firstNameMale}}");

        public Object femaleNameFormats = ZVal.arrayFromList("{{lastName}}{{firstNameFemale}}");

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "\u674E",
                                    "\u738B",
                                    "\u5F20",
                                    "\u5218",
                                    "\u9648",
                                    "\u6768",
                                    "\u8D75",
                                    "\u9EC4",
                                    "\u5468",
                                    "\u5434",
                                    "\u5F90",
                                    "\u5B59",
                                    "\u80E1",
                                    "\u6731",
                                    "\u9AD8",
                                    "\u6797",
                                    "\u4F55",
                                    "\u90ED",
                                    "\u9A6C",
                                    "\u7F57",
                                    "\u6881",
                                    "\u5B8B",
                                    "\u90D1",
                                    "\u8C22",
                                    "\u97E9",
                                    "\u5510",
                                    "\u51AF",
                                    "\u4E8E",
                                    "\u8463",
                                    "\u8427",
                                    "\u7A0B",
                                    "\u66F9",
                                    "\u8881",
                                    "\u9093",
                                    "\u8BB8",
                                    "\u5085",
                                    "\u6C89",
                                    "\u66FE",
                                    "\u5F6D",
                                    "\u5415",
                                    "\u82CF",
                                    "\u5362",
                                    "\u848B",
                                    "\u8521",
                                    "\u8D3E",
                                    "\u4E01",
                                    "\u6797",
                                    "\u859B",
                                    "\u53F6",
                                    "\u960E",
                                    "\u4F59",
                                    "\u6F58",
                                    "\u675C",
                                    "\u6234",
                                    "\u590F",
                                    "\u949F",
                                    "\u6C6A",
                                    "\u7530",
                                    "\u4EFB",
                                    "\u59DC",
                                    "\u8303",
                                    "\u65B9",
                                    "\u77F3",
                                    "\u59DA",
                                    "\u8C2D",
                                    "\u5ED6",
                                    "\u90B9",
                                    "\u718A",
                                    "\u91D1",
                                    "\u9646",
                                    "\u90DD",
                                    "\u5B54",
                                    "\u767D",
                                    "\u5D14",
                                    "\u5EB7",
                                    "\u6BDB",
                                    "\u90B1",
                                    "\u79E6",
                                    "\u6C5F",
                                    "\u53F2",
                                    "\u987E",
                                    "\u4FAF",
                                    "\u90B5",
                                    "\u5B5F",
                                    "\u9F99",
                                    "\u4E07",
                                    "\u6BB5",
                                    "\u96F7",
                                    "\u94B1",
                                    "\u6C64",
                                    "\u5C39",
                                    "\u9ECE",
                                    "\u6613",
                                    "\u5E38",
                                    "\u6B66",
                                    "\u4E54",
                                    "\u8D3A",
                                    "\u8D56",
                                    "\u9F9A",
                                    "\u6587",
                                    "\u5E9E",
                                    "\u6A0A",
                                    "\u5170",
                                    "\u6BB7",
                                    "\u65BD",
                                    "\u9676",
                                    "\u6D2A",
                                    "\u7FDF",
                                    "\u5B89",
                                    "\u989C",
                                    "\u502A",
                                    "\u4E25",
                                    "\u725B",
                                    "\u6E29",
                                    "\u82A6",
                                    "\u5B63",
                                    "\u4FDE",
                                    "\u7AE0",
                                    "\u9C81",
                                    "\u845B",
                                    "\u4F0D",
                                    "\u97E6",
                                    "\u7533",
                                    "\u5C24",
                                    "\u6BD5",
                                    "\u8042",
                                    "\u4E1B",
                                    "\u7126",
                                    "\u5411",
                                    "\u67F3",
                                    "\u90A2",
                                    "\u8DEF",
                                    "\u5CB3",
                                    "\u9F50",
                                    "\u6CBF",
                                    "\u6885",
                                    "\u83AB",
                                    "\u5E84",
                                    "\u8F9B",
                                    "\u7BA1",
                                    "\u795D",
                                    "\u5DE6",
                                    "\u6D82",
                                    "\u8C37",
                                    "\u7941",
                                    "\u65F6",
                                    "\u8212",
                                    "\u803F",
                                    "\u725F",
                                    "\u535C",
                                    "\u8DEF",
                                    "\u8A79",
                                    "\u5173",
                                    "\u82D7",
                                    "\u51CC",
                                    "\u8D39",
                                    "\u7EAA",
                                    "\u9773",
                                    "\u76DB",
                                    "\u7AE5",
                                    "\u6B27",
                                    "\u7504",
                                    "\u9879",
                                    "\u66F2",
                                    "\u6210",
                                    "\u6E38",
                                    "\u9633",
                                    "\u88F4",
                                    "\u5E2D",
                                    "\u536B",
                                    "\u67E5",
                                    "\u5C48",
                                    "\u9C8D",
                                    "\u4F4D",
                                    "\u8983",
                                    "\u970D",
                                    "\u7FC1",
                                    "\u968B",
                                    "\u690D",
                                    "\u7518",
                                    "\u666F",
                                    "\u8584",
                                    "\u5355",
                                    "\u5305",
                                    "\u53F8",
                                    "\u67CF",
                                    "\u5B81",
                                    "\u67EF",
                                    "\u962E",
                                    "\u6842",
                                    "\u95F5",
                                    "\u6B27\u9633",
                                    "\u89E3",
                                    "\u5F3A",
                                    "\u67F4",
                                    "\u534E",
                                    "\u8F66",
                                    "\u5189",
                                    "\u623F",
                                    "\u8FB9",
                                    "\u8F9C",
                                    "\u5409",
                                    "\u9976",
                                    "\u5201",
                                    "\u77BF",
                                    "\u621A",
                                    "\u4E18",
                                    "\u53E4",
                                    "\u7C73",
                                    "\u6C60",
                                    "\u6ED5",
                                    "\u664B",
                                    "\u82D1",
                                    "\u90AC",
                                    "\u81E7",
                                    "\u7545",
                                    "\u5BAB",
                                    "\u6765",
                                    "\u5D7A",
                                    "\u82DF",
                                    "\u5168",
                                    "\u891A",
                                    "\u5EC9",
                                    "\u7B80",
                                    "\u5A04",
                                    "\u76D6",
                                    "\u7B26",
                                    "\u595A",
                                    "\u6728",
                                    "\u7A46",
                                    "\u515A",
                                    "\u71D5",
                                    "\u90CE",
                                    "\u90B8",
                                    "\u5180",
                                    "\u8C08",
                                    "\u59EC",
                                    "\u5C60",
                                    "\u8FDE",
                                    "\u90DC",
                                    "\u664F",
                                    "\u683E",
                                    "\u90C1",
                                    "\u5546",
                                    "\u8499",
                                    "\u8BA1",
                                    "\u55BB",
                                    "\u63ED",
                                    "\u7AA6",
                                    "\u8FDF",
                                    "\u5B87",
                                    "\u6556",
                                    "\u7CDC",
                                    "\u9122",
                                    "\u51B7",
                                    "\u5353",
                                    "\u82B1",
                                    "\u4EC7",
                                    "\u827E",
                                    "\u84DD",
                                    "\u90FD",
                                    "\u5DE9",
                                    "\u7A3D",
                                    "\u4E95",
                                    "\u7EC3",
                                    "\u4EF2",
                                    "\u4E50",
                                    "\u865E",
                                    "\u535E",
                                    "\u5C01",
                                    "\u7AFA",
                                    "\u51BC",
                                    "\u539F",
                                    "\u5B98",
                                    "\u8863",
                                    "\u695A",
                                    "\u4F5F",
                                    "\u6817",
                                    "\u5321",
                                    "\u5B97",
                                    "\u5E94",
                                    "\u53F0",
                                    "\u5DEB",
                                    "\u97A0",
                                    "\u50E7",
                                    "\u6851",
                                    "\u8346",
                                    "\u8C0C",
                                    "\u94F6",
                                    "\u626C",
                                    "\u660E",
                                    "\u6C99",
                                    "\u8584",
                                    "\u4F0F",
                                    "\u5C91",
                                    "\u4E60",
                                    "\u80E5",
                                    "\u4FDD",
                                    "\u548C",
                                    "\u853A");
                        });

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "\u4F1F",
                                    "\u5F3A",
                                    "\u78CA",
                                    "\u6D0B",
                                    "\u52C7",
                                    "\u519B",
                                    "\u6770",
                                    "\u6D9B",
                                    "\u8D85",
                                    "\u660E",
                                    "\u521A",
                                    "\u5E73",
                                    "\u8F89",
                                    "\u9E4F",
                                    "\u534E",
                                    "\u98DE",
                                    "\u946B",
                                    "\u6CE2",
                                    "\u658C",
                                    "\u5B87",
                                    "\u6D69",
                                    "\u51EF",
                                    "\u5065",
                                    "\u4FCA",
                                    "\u5E06",
                                    "\u5E05",
                                    "\u65ED",
                                    "\u5B81",
                                    "\u9F99",
                                    "\u6797",
                                    "\u6B22",
                                    "\u9633",
                                    "\u5EFA\u534E",
                                    "\u4EAE",
                                    "\u6210",
                                    "\u7545",
                                    "\u5EFA",
                                    "\u5CF0",
                                    "\u5EFA\u56FD",
                                    "\u5EFA\u519B",
                                    "\u6668",
                                    "\u745E",
                                    "\u5FD7\u5F3A",
                                    "\u5175",
                                    "\u96F7",
                                    "\u4E1C",
                                    "\u6B23",
                                    "\u535A",
                                    "\u5F6C",
                                    "\u5764",
                                    "\u5168\u5B89",
                                    "\u8363",
                                    "\u5CA9",
                                    "\u6768",
                                    "\u6587",
                                    "\u5229",
                                    "\u6960",
                                    "\u5EFA\u5E73",
                                    "\u5609\u4FCA",
                                    "\u6667",
                                    "\u5EFA\u660E",
                                    "\u5B50\u5B89",
                                    "\u65B0\u534E",
                                    "\u9E4F\u7A0B",
                                    "\u5B66\u660E",
                                    "\u535A\u6D9B",
                                    "\u6377",
                                    "\u6587\u5F6C",
                                    "\u697C",
                                    "\u9E70",
                                    "\u677E",
                                    "\u4F26",
                                    "\u8D85",
                                    "\u949F",
                                    "\u745C",
                                    "\u632F\u56FD",
                                    "\u6D2A",
                                    "\u6BC5",
                                    "\u6631\u7136",
                                    "\u54F2",
                                    "\u7FD4",
                                    "\u7FFC",
                                    "\u7965",
                                    "\u56FD\u5E86",
                                    "\u54F2\u5F66",
                                    "\u6B63\u8BDA",
                                    "\u6B63\u8C6A",
                                    "\u6B63\u5E73",
                                    "\u6B63\u4E1A",
                                    "\u5FD7\u8BDA",
                                    "\u5FD7\u65B0",
                                    "\u5FD7\u52C7",
                                    "\u5FD7\u660E",
                                    "\u5FD7\u5F3A",
                                    "\u5FD7\u6587",
                                    "\u81F4\u8FDC",
                                    "\u667A\u660E",
                                    "\u667A\u52C7",
                                    "\u667A\u654F",
                                    "\u667A\u6E0A");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "\u82B3",
                                    "\u5A1C",
                                    "\u654F",
                                    "\u9759",
                                    "\u654F\u9759",
                                    "\u79C0\u82F1",
                                    "\u4E3D",
                                    "\u6D0B",
                                    "\u8273",
                                    "\u5A1F",
                                    "\u6587\u5A1F",
                                    "\u541B",
                                    "\u6587\u541B",
                                    "\u73FA",
                                    "\u971E",
                                    "\u660E\u971E",
                                    "\u79C0\u5170",
                                    "\u71D5",
                                    "\u82AC",
                                    "\u6842\u82AC",
                                    "\u73B2",
                                    "\u6842\u82F1",
                                    "\u4E39",
                                    "\u840D",
                                    "\u534E",
                                    "\u7EA2",
                                    "\u7389\u5170",
                                    "\u6842\u5170",
                                    "\u82F1",
                                    "\u6885",
                                    "\u8389",
                                    "\u79C0\u73CD",
                                    "\u96EA",
                                    "\u4F9D\u7433",
                                    "\u65ED",
                                    "\u5B81",
                                    "\u5A77",
                                    "\u99A8\u4E88",
                                    "\u7389\u73CD",
                                    "\u51E4\u82F1",
                                    "\u6676",
                                    "\u6B22",
                                    "\u7389\u82F1",
                                    "\u9896",
                                    "\u7EA2\u6885",
                                    "\u4F73",
                                    "\u5029",
                                    "\u7434",
                                    "\u5170\u82F1",
                                    "\u4E91",
                                    "\u6D01",
                                    "\u7231\u534E",
                                    "\u6DD1\u73CD",
                                    "\u6625\u6885",
                                    "\u6D77\u71D5",
                                    "\u6668",
                                    "\u51AC\u6885",
                                    "\u79C0\u8363",
                                    "\u745E",
                                    "\u6842\u73CD",
                                    "\u83B9",
                                    "\u79C0\u4E91",
                                    "\u6842\u8363",
                                    "\u79C0\u6885",
                                    "\u4E3D\u5A1F",
                                    "\u5A77\u5A77",
                                    "\u7389\u534E",
                                    "\u7433",
                                    "\u96EA\u6885",
                                    "\u6DD1\u5170",
                                    "\u4E3D\u4E3D",
                                    "\u7389",
                                    "\u79C0\u82B3",
                                    "\u6B23",
                                    "\u6DD1\u82F1",
                                    "\u6842\u82B3",
                                    "\u4E3D\u534E",
                                    "\u4E39\u4E39",
                                    "\u6842\u9999",
                                    "\u6DD1\u534E",
                                    "\u79C0\u534E",
                                    "\u6842\u829D",
                                    "\u5C0F\u7EA2",
                                    "\u91D1\u51E4",
                                    "\u6587",
                                    "\u5229",
                                    "\u6960",
                                    "\u7EA2\u971E",
                                    "\u745C",
                                    "\u6842\u82B1",
                                    "\u7490",
                                    "\u51E4\u5170",
                                    "\u814A\u6885",
                                    "\u7476",
                                    "\u5609",
                                    "\u6021",
                                    "\u51B0\u51B0",
                                    "\u7389\u6885",
                                    "\u6167",
                                    "\u5A55");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\zh_CN\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/zh_CN/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
