package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.es_AR.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.classes.StaticMethodUtils;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import com.runtimeconverter.runtime.passByReference.RuntimeArgsWithReferences;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/es_AR/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\es_AR\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();

        @ConvertedMethod
        public Object suffix(RuntimeEnv env, Object... args) {
            return ZVal.assign(
                    StaticMethodUtils.accessUnknownLateStaticMethod(env, this, Person.class)
                            .method("randomElement")
                            .addReferenceArgs(new RuntimeArgsWithReferences())
                            .call(
                                    env.getRequestStaticProperties(
                                                    com.project
                                                            .convertedCode
                                                            .globalNamespace
                                                            .namespaces
                                                            .Faker
                                                            .namespaces
                                                            .Provider
                                                            .namespaces
                                                            .es_AR
                                                            .classes
                                                            .Person
                                                            .RequestStaticProperties
                                                            .class)
                                            .suffix)
                            .value());
        }
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object maleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}} {{suffix}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}} {{suffix}}");

        public Object femaleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}} {{suffix}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}} {{suffix}}");

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aar\u00F3n",
                                    "Adri\u00E1n",
                                    "Agust\u00EDn",
                                    "Alan",
                                    "Alejandro",
                                    "Alex",
                                    "Alexander",
                                    "Alonso",
                                    "Andr\u00E9s",
                                    "Anthony",
                                    "Antonio",
                                    "Axel",
                                    "Benjam\u00EDn",
                                    "Bruno",
                                    "Camilo",
                                    "Carlos",
                                    "Christian",
                                    "Christopher",
                                    "Crist\u00F3bal",
                                    "Dami\u00E1n",
                                    "Daniel",
                                    "Dante",
                                    "David",
                                    "Diego",
                                    "Diego Alejandro",
                                    "Dylan",
                                    "Eduardo",
                                    "El\u00EDas",
                                    "Emiliano",
                                    "Emilio",
                                    "Emmanuel",
                                    "Esteban",
                                    "Facundo",
                                    "Felipe",
                                    "Fernando",
                                    "Francisco",
                                    "Franco",
                                    "Gabriel",
                                    "Gael",
                                    "Hip\u00F3lito",
                                    "Horacio",
                                    "Hugo",
                                    "Ian",
                                    "Ignacio",
                                    "Isaac",
                                    "Ivan",
                                    "Jacobo",
                                    "Javier",
                                    "Jer\u00F3nimo",
                                    "Jes\u00FAs",
                                    "Joaqu\u00EDn",
                                    "Jorge",
                                    "Joshua",
                                    "Josu\u00E9",
                                    "Jos\u00E9",
                                    "Juan",
                                    "Juan David",
                                    "Juan Diego",
                                    "Juan Jos\u00E9",
                                    "Juan Manuel",
                                    "Juan Mart\u00EDn",
                                    "Juan Pablo",
                                    "Juan Sebasti\u00E1n",
                                    "Juli\u00E1n",
                                    "Kevin",
                                    "Lautaro",
                                    "Leonardo",
                                    "Lorenzo",
                                    "Lucas",
                                    "Luciano",
                                    "Luis",
                                    "Manuel",
                                    "Mario",
                                    "Mart\u00EDn",
                                    "Mateo",
                                    "Matthew",
                                    "Mat\u00EDas",
                                    "Maximiliano",
                                    "Miguel",
                                    "Miguel \u00C1ngel",
                                    "M\u00E1ximo",
                                    "Nahuel",
                                    "Pablo",
                                    "Pedro",
                                    "Rafael",
                                    "Ricardo",
                                    "Rodrigo",
                                    "Samuel",
                                    "Santiago",
                                    "Santino",
                                    "Sebasti\u00E1n",
                                    "Sergio",
                                    "Sim\u00F3n",
                                    "Thiago",
                                    "Tomas",
                                    "Valentino",
                                    "Valent\u00EDn",
                                    "Vicente",
                                    "Bautista",
                                    "Juan Esteban",
                                    "Hidalgo");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abigail",
                                    "Abril",
                                    "Adriana",
                                    "Agustina",
                                    "Alejandra",
                                    "Alessandra",
                                    "Alexa",
                                    "Allison",
                                    "Alma",
                                    "Amanda",
                                    "Amelia",
                                    "Ana",
                                    "Ana Paula",
                                    "Ana Sof\u00EDa",
                                    "Andrea",
                                    "Antonella",
                                    "Antonia",
                                    "Ariadna",
                                    "Ariana",
                                    "Ashley",
                                    "Bianca",
                                    "Camila",
                                    "Carla",
                                    "Carolina",
                                    "Catalina",
                                    "Clara",
                                    "Constanza",
                                    "Daniela",
                                    "Delfina",
                                    "Elena",
                                    "Elizabeth",
                                    "Emilia",
                                    "Emily",
                                    "Emma",
                                    "Fabiana",
                                    "Florencia",
                                    "F\u00E1tima",
                                    "Gabriela",
                                    "Guadalupe",
                                    "Irene",
                                    "Isabel",
                                    "Isabella",
                                    "Isidora",
                                    "Ivanna",
                                    "Jazm\u00EDn",
                                    "Josefa",
                                    "Josefina",
                                    "Juana",
                                    "Julia",
                                    "Juliana",
                                    "Julieta",
                                    "Laura",
                                    "Lola",
                                    "Luana",
                                    "Luciana",
                                    "Luc\u00EDa",
                                    "Luna",
                                    "Magdalena",
                                    "Maite",
                                    "Malena",
                                    "Manuela",
                                    "Mariana",
                                    "Mariangel",
                                    "Martina",
                                    "Mar\u00EDa",
                                    "Mar\u00EDa Alejandra",
                                    "Mar\u00EDa Camila",
                                    "Mar\u00EDa Fernanda",
                                    "Mar\u00EDa Jos\u00E9",
                                    "Mar\u00EDa Paula",
                                    "Micaela",
                                    "Michelle",
                                    "Miranda",
                                    "Montserrat",
                                    "M\u00EDa",
                                    "Nadia",
                                    "Natalia",
                                    "Nicole",
                                    "Oliva",
                                    "Olivia",
                                    "Ornela",
                                    "Paula",
                                    "Paulina",
                                    "Rafaela",
                                    "Rebeca",
                                    "Regina",
                                    "Renata",
                                    "Romina",
                                    "Salom\u00E9",
                                    "Samantha",
                                    "Sara",
                                    "Silvana",
                                    "Sof\u00EDa",
                                    "Sophie",
                                    "Valentina",
                                    "Valeria",
                                    "Valery",
                                    "Victoria",
                                    "Violeta",
                                    "Zoe",
                                    "Aitana",
                                    "Sara Sof\u00EDa",
                                    "Ximena");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abeyta",
                                    "Abrego",
                                    "Abreu",
                                    "Acevedo",
                                    "Acosta",
                                    "Acu\u00F1a",
                                    "Adame",
                                    "Adorno",
                                    "Agosto",
                                    "Aguayo",
                                    "\u00C1guilar",
                                    "Aguilera",
                                    "Aguirre",
                                    "Alanis",
                                    "Alaniz",
                                    "Alarc\u00F3n",
                                    "Alba",
                                    "Alcala",
                                    "Alc\u00E1ntar",
                                    "Alcaraz",
                                    "Alejandro",
                                    "Alem\u00E1n",
                                    "Alfaro",
                                    "Alicea",
                                    "Almanza",
                                    "Almaraz",
                                    "Almonte",
                                    "Alonso",
                                    "Alonzo",
                                    "Altamirano",
                                    "Alva",
                                    "Alvarado",
                                    "\u00C1lvarez",
                                    "Amador",
                                    "Amaya",
                                    "Anaya",
                                    "Anguiano",
                                    "Angulo",
                                    "Aparicio",
                                    "Apodaca",
                                    "Aponte",
                                    "Arag\u00F3n",
                                    "Ara\u00F1a",
                                    "Aranda",
                                    "Arce",
                                    "Archuleta",
                                    "Arellano",
                                    "Arenas",
                                    "Arevalo",
                                    "Arguello",
                                    "Arias",
                                    "Armas",
                                    "Armend\u00E1riz",
                                    "Armenta",
                                    "Armijo",
                                    "Arredondo",
                                    "Arreola",
                                    "Arriaga",
                                    "Arroyo",
                                    "Arteaga",
                                    "Atencio",
                                    "\u00C1valos",
                                    "\u00C1vila",
                                    "Avil\u00E9s",
                                    "Ayala",
                                    "Baca",
                                    "Badillo",
                                    "B\u00E1ez",
                                    "Baeza",
                                    "Bahena",
                                    "Balderas",
                                    "Ballesteros",
                                    "Banda",
                                    "Ba\u00F1uelos",
                                    "Barajas",
                                    "Barela",
                                    "Barrag\u00E1n",
                                    "Barraza",
                                    "Barrera",
                                    "Barreto",
                                    "Barrientos",
                                    "Barrios",
                                    "Batista",
                                    "Becerra",
                                    "Beltr\u00E1n",
                                    "Benavides",
                                    "Benav\u00EDdez",
                                    "Ben\u00EDtez",
                                    "Berm\u00FAdez",
                                    "Bernal",
                                    "Berr\u00EDos",
                                    "B\u00E9tancourt",
                                    "Blanco",
                                    "Bonilla",
                                    "Borrego",
                                    "Botello",
                                    "Bravo",
                                    "Briones",
                                    "Brise\u00F1o",
                                    "Brito",
                                    "Bueno",
                                    "Burgos",
                                    "Bustamante",
                                    "Bustos",
                                    "Caballero",
                                    "Cab\u00E1n",
                                    "Cabrera",
                                    "Cadena",
                                    "Caldera",
                                    "Calder\u00F3n",
                                    "Calvillo",
                                    "Camacho",
                                    "Camarillo",
                                    "Campos",
                                    "Canales",
                                    "Candelaria",
                                    "Cano",
                                    "Cant\u00FA",
                                    "Caraballo",
                                    "Carbajal",
                                    "Cardenas",
                                    "Cardona",
                                    "Carmona",
                                    "Carranza",
                                    "Carrasco",
                                    "Carrasquillo",
                                    "Carre\u00F3n",
                                    "Carrera",
                                    "Carrero",
                                    "Carrillo",
                                    "Carrion",
                                    "Carvajal",
                                    "Casanova",
                                    "Casares",
                                    "Cas\u00E1rez",
                                    "Casas",
                                    "Casillas",
                                    "Casta\u00F1eda",
                                    "Castellanos",
                                    "Castillo",
                                    "Castro",
                                    "Cavazos",
                                    "Cazares",
                                    "Ceballos",
                                    "Cedillo",
                                    "Ceja",
                                    "Centeno",
                                    "Cepeda",
                                    "Cerda",
                                    "Cervantes",
                                    "Cerv\u00E1ntez",
                                    "Chac\u00F3n",
                                    "Chapa",
                                    "Chavarr\u00EDa",
                                    "Ch\u00E1vez",
                                    "Cintr\u00F3n",
                                    "Cisneros",
                                    "Collado",
                                    "Collazo",
                                    "Col\u00F3n",
                                    "Colunga",
                                    "Concepci\u00F3n",
                                    "Contreras",
                                    "Cordero",
                                    "C\u00F3rdova",
                                    "Cornejo",
                                    "Corona",
                                    "Coronado",
                                    "Corral",
                                    "Corrales",
                                    "Correa",
                                    "Cort\u00E9s",
                                    "Cortez",
                                    "Cotto",
                                    "Covarrubias",
                                    "Crespo",
                                    "Cruz",
                                    "Cuellar",
                                    "Curiel",
                                    "D\u00E1vila",
                                    "de Anda",
                                    "de Jes\u00FAs",
                                    "Delacr\u00FAz",
                                    "Delafuente",
                                    "Delagarza",
                                    "Delao",
                                    "Delapaz",
                                    "Delarosa",
                                    "Delatorre",
                                    "Dele\u00F3n",
                                    "Delgadillo",
                                    "Delgado",
                                    "Delr\u00EDo",
                                    "Delvalle",
                                    "D\u00EDaz",
                                    "Dom\u00EDnguez",
                                    "Dom\u00EDnquez",
                                    "Duarte",
                                    "Due\u00F1as",
                                    "Duran",
                                    "Echevarr\u00EDa",
                                    "Elizondo",
                                    "Enr\u00EDquez",
                                    "Escalante",
                                    "Escamilla",
                                    "Escobar",
                                    "Escobedo",
                                    "Esparza",
                                    "Espinal",
                                    "Espino",
                                    "Espinosa",
                                    "Espinoza",
                                    "Esquibel",
                                    "Esquivel",
                                    "Est\u00E9vez",
                                    "Estrada",
                                    "Fajardo",
                                    "Far\u00EDas",
                                    "Feliciano",
                                    "Fern\u00E1ndez",
                                    "Ferrer",
                                    "Fierro",
                                    "Figueroa",
                                    "Flores",
                                    "Fl\u00F3rez",
                                    "Fonseca",
                                    "Franco",
                                    "Fr\u00EDas",
                                    "Fuentes",
                                    "Gait\u00E1n",
                                    "Galarza",
                                    "Galindo",
                                    "Gallardo",
                                    "Gallegos",
                                    "Galv\u00E1n",
                                    "G\u00E1lvez",
                                    "Gamboa",
                                    "Gamez",
                                    "Gaona",
                                    "Garay",
                                    "Garc\u00EDa",
                                    "Garibay",
                                    "Garica",
                                    "Garrido",
                                    "Garza",
                                    "Gast\u00E9lum",
                                    "Gayt\u00E1n",
                                    "Gil",
                                    "Gir\u00F3n",
                                    "God\u00EDnez",
                                    "Godoy",
                                    "G\u00F3mez",
                                    "Gonzales",
                                    "Gonz\u00E1lez",
                                    "Gracia",
                                    "Granado",
                                    "Granados",
                                    "Griego",
                                    "Grijalva",
                                    "Guajardo",
                                    "Guardado",
                                    "Guerra",
                                    "Guerrero",
                                    "Guevara",
                                    "Guillen",
                                    "Gurule",
                                    "Guti\u00E9rrez",
                                    "Guzm\u00E1n",
                                    "Haro",
                                    "Henr\u00EDquez",
                                    "Heredia",
                                    "Hern\u00E1dez",
                                    "Hernandes",
                                    "Hern\u00E1ndez",
                                    "Herrera",
                                    "Hidalgo",
                                    "Hinojosa",
                                    "Holgu\u00EDn",
                                    "Huerta",
                                    "Hurtado",
                                    "Ibarra",
                                    "Iglesias",
                                    "Irizarry",
                                    "Jaime",
                                    "Jaimes",
                                    "J\u00E1quez",
                                    "Jaramillo",
                                    "Jasso",
                                    "Jim\u00E9nez",
                                    "Jim\u00EDnez",
                                    "Ju\u00E1rez",
                                    "Jurado",
                                    "Laboy",
                                    "Lara",
                                    "Laureano",
                                    "Leal",
                                    "Lebr\u00F3n",
                                    "Ledesma",
                                    "Leiva",
                                    "Lemus",
                                    "Le\u00F3n",
                                    "Lerma",
                                    "Leyva",
                                    "Lim\u00F3n",
                                    "Linares",
                                    "Lira",
                                    "Llamas",
                                    "Loera",
                                    "Lomeli",
                                    "Longoria",
                                    "L\u00F3pez",
                                    "Lovato",
                                    "Loya",
                                    "Lozada",
                                    "Lozano",
                                    "Lucero",
                                    "Lucio",
                                    "Luevano",
                                    "Lugo",
                                    "Luj\u00E1n",
                                    "Luna",
                                    "Mac\u00EDas",
                                    "Madera",
                                    "Madrid",
                                    "Madrigal",
                                    "Maestas",
                                    "Maga\u00F1a",
                                    "Malave",
                                    "Maldonado",
                                    "Manzanares",
                                    "Mares",
                                    "Mar\u00EDn",
                                    "M\u00E1rquez",
                                    "Marrero",
                                    "Marroqu\u00EDn",
                                    "Mart\u00EDnez",
                                    "Mascare\u00F1as",
                                    "Mata",
                                    "Mateo",
                                    "Mat\u00EDas",
                                    "Matos",
                                    "Maya",
                                    "Mayorga",
                                    "Medina",
                                    "Medrano",
                                    "Mej\u00EDa",
                                    "Mel\u00E9ndez",
                                    "Melgar",
                                    "Mena",
                                    "Menchaca",
                                    "M\u00E9ndez",
                                    "Mendoza",
                                    "Men\u00E9ndez",
                                    "Meraz",
                                    "Mercado",
                                    "Merino",
                                    "Mesa",
                                    "Meza",
                                    "Miramontes",
                                    "Miranda",
                                    "Mireles",
                                    "Mojica",
                                    "Molina",
                                    "Mondrag\u00F3n",
                                    "Monroy",
                                    "Montalvo",
                                    "Monta\u00F1ez",
                                    "Monta\u00F1o",
                                    "Montemayor",
                                    "Montenegro",
                                    "Montero",
                                    "Montes",
                                    "Montez",
                                    "Montoya",
                                    "Mora",
                                    "Morales",
                                    "Moreno",
                                    "Mota",
                                    "Moya",
                                    "Mungu\u00EDa",
                                    "Mu\u00F1iz",
                                    "Mu\u00F1oz",
                                    "Murillo",
                                    "Muro",
                                    "N\u00E1jera",
                                    "Naranjo",
                                    "Narv\u00E1ez",
                                    "Nava",
                                    "Navarrete",
                                    "Navarro",
                                    "Nazario",
                                    "Negrete",
                                    "Negr\u00F3n",
                                    "Nev\u00E1rez",
                                    "Nieto",
                                    "Nieves",
                                    "Ni\u00F1o",
                                    "Noriega",
                                    "N\u00FA\u00F1ez",
                                    "Ocampo",
                                    "Ocasio",
                                    "Ochoa",
                                    "Ojeda",
                                    "Olivares",
                                    "Oliv\u00E1rez",
                                    "Olivas",
                                    "Olivera",
                                    "Olivo",
                                    "Olmos",
                                    "Olvera",
                                    "Ontiveros",
                                    "Oquendo",
                                    "Ord\u00F3\u00F1ez",
                                    "Orellana",
                                    "Ornelas",
                                    "Orosco",
                                    "Orozco",
                                    "Orta",
                                    "Ortega",
                                    "Ortiz",
                                    "Osorio",
                                    "Otero",
                                    "Ozuna",
                                    "Pab\u00F3n",
                                    "Pacheco",
                                    "Padilla",
                                    "Padr\u00F3n",
                                    "P\u00E1ez",
                                    "Pagan",
                                    "Palacios",
                                    "Palomino",
                                    "Palomo",
                                    "Pantoja",
                                    "Paredes",
                                    "Parra",
                                    "Partida",
                                    "Pati\u00F1o",
                                    "Paz",
                                    "Pedraza",
                                    "Pedroza",
                                    "Pelayo",
                                    "Pe\u00F1a",
                                    "Perales",
                                    "Peralta",
                                    "Perea",
                                    "Peres",
                                    "P\u00E9rez",
                                    "Pichardo",
                                    "Pi\u00F1a",
                                    "Pineda",
                                    "Pizarro",
                                    "Polanco",
                                    "Ponce",
                                    "Porras",
                                    "Portillo",
                                    "Posada",
                                    "Prado",
                                    "Preciado",
                                    "Prieto",
                                    "Puente",
                                    "Puga",
                                    "Pulido",
                                    "Quesada",
                                    "Quezada",
                                    "Qui\u00F1ones",
                                    "Qui\u00F1\u00F3nez",
                                    "Quintana",
                                    "Quintanilla",
                                    "Quintero",
                                    "Quiroz",
                                    "Rael",
                                    "Ram\u00EDrez",
                                    "Ram\u00F3n",
                                    "Ramos",
                                    "Rangel",
                                    "Rasc\u00F3n",
                                    "Raya",
                                    "Razo",
                                    "Regalado",
                                    "Rend\u00F3n",
                                    "Renter\u00EDa",
                                    "Res\u00E9ndez",
                                    "Reyes",
                                    "Reyna",
                                    "Reynoso",
                                    "Rico",
                                    "Rinc\u00F3n",
                                    "Riojas",
                                    "R\u00EDos",
                                    "Rivas",
                                    "Rivera",
                                    "Rivero",
                                    "Robledo",
                                    "Robles",
                                    "Rocha",
                                    "Rodarte",
                                    "Rodr\u00EDgez",
                                    "Rodr\u00EDguez",
                                    "Rodr\u00EDquez",
                                    "Rojas",
                                    "Rojo",
                                    "Rold\u00E1n",
                                    "Rol\u00F3n",
                                    "Romero",
                                    "Romo",
                                    "Roque",
                                    "Rosado",
                                    "Rosales",
                                    "Rosario",
                                    "Rosas",
                                    "Roybal",
                                    "Rubio",
                                    "Ruelas",
                                    "Ruiz",
                                    "Ruvalcaba",
                                    "Saavedra",
                                    "S\u00E1enz",
                                    "Saiz",
                                    "Salas",
                                    "Salazar",
                                    "Salcedo",
                                    "Salcido",
                                    "Salda\u00F1a",
                                    "Saldivar",
                                    "Salgado",
                                    "Salinas",
                                    "Samaniego",
                                    "Sanabria",
                                    "Sanches",
                                    "S\u00E1nchez",
                                    "Sandoval",
                                    "Santacruz",
                                    "Santana",
                                    "Santiago",
                                    "Santill\u00E1n",
                                    "Sarabia",
                                    "Sauceda",
                                    "Saucedo",
                                    "Sedillo",
                                    "Segovia",
                                    "Segura",
                                    "Sep\u00FAlveda",
                                    "Serna",
                                    "Serrano",
                                    "Serrato",
                                    "Sevilla",
                                    "Sierra",
                                    "Sisneros",
                                    "Solano",
                                    "Sol\u00EDs",
                                    "Soliz",
                                    "Solorio",
                                    "Solorzano",
                                    "Soria",
                                    "Sosa",
                                    "Sotelo",
                                    "Soto",
                                    "Su\u00E1rez",
                                    "Tafoya",
                                    "Tamayo",
                                    "Tamez",
                                    "Tapia",
                                    "Tejada",
                                    "Tejeda",
                                    "T\u00E9llez",
                                    "Tello",
                                    "Ter\u00E1n",
                                    "Terrazas",
                                    "Tijerina",
                                    "Tirado",
                                    "Toledo",
                                    "Toro",
                                    "Torres",
                                    "T\u00F3rrez",
                                    "Tovar",
                                    "Trejo",
                                    "Trevi\u00F1o",
                                    "Trujillo",
                                    "Ulibarri",
                                    "Ulloa",
                                    "Urbina",
                                    "Ure\u00F1a",
                                    "Ur\u00EDas",
                                    "Uribe",
                                    "Urrutia",
                                    "Vaca",
                                    "Valadez",
                                    "Vald\u00E9s",
                                    "Valdez",
                                    "Valdivia",
                                    "Valencia",
                                    "Valent\u00EDn",
                                    "Valenzuela",
                                    "Valladares",
                                    "Valle",
                                    "Vallejo",
                                    "Valles",
                                    "Valverde",
                                    "Vanegas",
                                    "Varela",
                                    "Vargas",
                                    "V\u00E1squez",
                                    "V\u00E1zquez",
                                    "Vega",
                                    "Vela",
                                    "Velasco",
                                    "Vel\u00E1squez",
                                    "Vel\u00E1zquez",
                                    "V\u00E9lez",
                                    "V\u00E9liz",
                                    "Venegas",
                                    "Vera",
                                    "Verdugo",
                                    "Verduzco",
                                    "Vergara",
                                    "Viera",
                                    "Vigil",
                                    "Villa",
                                    "Villag\u00F3mez",
                                    "Villalobos",
                                    "Villalpando",
                                    "Villanueva",
                                    "Villareal",
                                    "Villarreal",
                                    "Villase\u00F1or",
                                    "Villegas",
                                    "Y\u00E1\u00F1ez",
                                    "Ybarra",
                                    "Zambrano",
                                    "Zamora",
                                    "Zamudio",
                                    "Zapata",
                                    "Zaragoza",
                                    "Zarate",
                                    "Zavala",
                                    "Zayas",
                                    "Zelaya",
                                    "Zepeda",
                                    "Z\u00FA\u00F1iga");
                        });

        public Object titleMale = ZVal.arrayFromList("Sr.", "Dn.", "Dr.", "Lic.", "Ing.");

        public Object titleFemale = ZVal.arrayFromList("Sra.", "Srita.", "Dr.", "Lic.", "Ing.");

        public Object suffix = ZVal.arrayFromList("Hijo", "Segundo", "Tercero");
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\es_AR\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats",
                            "suffix",
                            "titleFemale",
                            "titleMale")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/es_AR/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
