package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.de_AT.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.classes.StaticMethodUtils;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import com.runtimeconverter.runtime.passByReference.RuntimeArgsWithReferences;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/de_AT/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\de_AT\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();

        @ConvertedMethod
        public Object suffix(RuntimeEnv env, Object... args) {
            return ZVal.assign(
                    StaticMethodUtils.accessUnknownLateStaticMethod(env, this, Person.class)
                            .method("randomElement")
                            .addReferenceArgs(new RuntimeArgsWithReferences())
                            .call(
                                    env.getRequestStaticProperties(
                                                    com.project
                                                            .convertedCode
                                                            .globalNamespace
                                                            .namespaces
                                                            .Faker
                                                            .namespaces
                                                            .Provider
                                                            .namespaces
                                                            .de_AT
                                                            .classes
                                                            .Person
                                                            .RequestStaticProperties
                                                            .class)
                                            .suffix)
                            .value());
        }
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object maleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}} {{suffix}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}} {{suffix}}");

        public Object femaleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}} {{suffix}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}} {{suffix}}");

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Adrian",
                                    "Alexander",
                                    "Andreas",
                                    "Anton",
                                    "Ben",
                                    "Benedikt",
                                    "Benjamin",
                                    "Bernd",
                                    "Bernhard",
                                    "Christian",
                                    "Christoph",
                                    "Christopher",
                                    "Clemens",
                                    "Daniel",
                                    "David",
                                    "Dominik",
                                    "Elias",
                                    "Emil",
                                    "Erik",
                                    "Fabian",
                                    "Fabio",
                                    "Felix",
                                    "Finn",
                                    "Florian",
                                    "Franz",
                                    "Gabriel",
                                    "Georg",
                                    "Gerald",
                                    "Gerhard",
                                    "Gernot",
                                    "Gregor",
                                    "G\u00FCnther",
                                    "Hannes",
                                    "Harald",
                                    "Helmut",
                                    "Herbert",
                                    "Jakob",
                                    "Jan",
                                    "Johann",
                                    "Johannes",
                                    "Jonas",
                                    "Jonathan",
                                    "Josef",
                                    "Joseph",
                                    "Julian",
                                    "Justin",
                                    "J\u00FCrgen",
                                    "Karl",
                                    "Kevin",
                                    "Kilian",
                                    "Klaus",
                                    "Konstantin",
                                    "Leo",
                                    "Leon",
                                    "Lorenz",
                                    "Luca",
                                    "Luis",
                                    "Lukas",
                                    "Manfred",
                                    "Manuel",
                                    "Marc",
                                    "Marcel",
                                    "Marco",
                                    "Mario",
                                    "Markus",
                                    "Martin",
                                    "Marvin",
                                    "Matteo",
                                    "Matthias",
                                    "Max",
                                    "Maximilian",
                                    "Michael",
                                    "Moritz",
                                    "Nico",
                                    "Nicolas",
                                    "Niklas",
                                    "Noah",
                                    "Oliver",
                                    "Oskar",
                                    "Pascal",
                                    "Patrick",
                                    "Patrik",
                                    "Paul",
                                    "Peter",
                                    "Philipp",
                                    "Ralph",
                                    "Raphael",
                                    "Reinhard",
                                    "Ren\u00E9",
                                    "Richard",
                                    "Robert",
                                    "Roland",
                                    "Roman",
                                    "Samuel",
                                    "Sandro",
                                    "Sascha",
                                    "Sebastian",
                                    "Simon",
                                    "Stefan",
                                    "Theo",
                                    "Theodor",
                                    "Thomas",
                                    "Tim",
                                    "Tobias",
                                    "Valentin",
                                    "Vincent",
                                    "Werner",
                                    "Wolfgang");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Alexandra",
                                    "Alexandrea",
                                    "Algelika",
                                    "Alina",
                                    "Amelie",
                                    "Andrea",
                                    "Angelina",
                                    "Anita",
                                    "Anja",
                                    "Anna",
                                    "Anna-Lena",
                                    "Annika",
                                    "Astrid",
                                    "Barbara",
                                    "Bettina",
                                    "Bianca",
                                    "Birgit",
                                    "Carina",
                                    "Caroline",
                                    "Celina",
                                    "Chiara",
                                    "Christina",
                                    "Christine",
                                    "Clara",
                                    "Claudia",
                                    "Cornelia",
                                    "Daniela",
                                    "Denise",
                                    "Doris",
                                    "Elena",
                                    "Elisa",
                                    "Elisabeth",
                                    "Ella",
                                    "Emely",
                                    "Emilia",
                                    "Emily",
                                    "Emma",
                                    "Eva",
                                    "Eva-Maria",
                                    "Franziska",
                                    "Hanna",
                                    "Hannah",
                                    "Helena",
                                    "Ines",
                                    "Iris",
                                    "Isabel",
                                    "Isabella",
                                    "Jacqueline",
                                    "Jacquline",
                                    "Jana",
                                    "Janine",
                                    "Jasmin",
                                    "Jennifer",
                                    "Jessica",
                                    "Johanna",
                                    "Julia",
                                    "Karin",
                                    "Katharina",
                                    "Katrin",
                                    "Kerstin",
                                    "Lara",
                                    "Larissa",
                                    "Laura",
                                    "Lea",
                                    "Lena",
                                    "Leonie",
                                    "Lilly",
                                    "Lina",
                                    "Lisa",
                                    "Livia",
                                    "Luisa",
                                    "Magdalena",
                                    "Maja",
                                    "Manuela",
                                    "Maria",
                                    "Marie",
                                    "Marion",
                                    "Marlene",
                                    "Martina",
                                    "Melanie",
                                    "Melina",
                                    "Mia",
                                    "Michaela",
                                    "Michelle",
                                    "Miriam",
                                    "Mona",
                                    "Monika",
                                    "Nadine",
                                    "Natalie",
                                    "Nicole",
                                    "Nina",
                                    "Nora",
                                    "Patricia",
                                    "Paula",
                                    "Petra",
                                    "Pia",
                                    "Rebecca",
                                    "Rosa",
                                    "Sabine",
                                    "Sabrina",
                                    "Sandra",
                                    "Sarah",
                                    "Selina",
                                    "Silvia",
                                    "Simone",
                                    "Sonja",
                                    "Sophia",
                                    "Sophie",
                                    "Stefanie",
                                    "Susanne",
                                    "Tamara",
                                    "Tanja",
                                    "Theresa",
                                    "Valentina",
                                    "Valerie",
                                    "Vanessa",
                                    "Verena",
                                    "Viktoria",
                                    "Yvonne");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abraham",
                                    "Achleitner",
                                    "Adam",
                                    "Aichinger",
                                    "Aigner",
                                    "Albrecht",
                                    "Altmann",
                                    "Amann",
                                    "Amon",
                                    "Angerer",
                                    "Arnold",
                                    "Artner",
                                    "Aschauer",
                                    "Auer",
                                    "Augustin",
                                    "Auinger",
                                    "Bacher",
                                    "Bachler",
                                    "Bachmann",
                                    "Bader",
                                    "Baier",
                                    "Barth",
                                    "Bartl",
                                    "Bauer",
                                    "Baumann",
                                    "Baumgartner",
                                    "Bayer",
                                    "Beck",
                                    "Beer",
                                    "Berger",
                                    "Bergmann",
                                    "Bernhard",
                                    "Bichler",
                                    "Binder",
                                    "Bischof",
                                    "Bock",
                                    "Bogner",
                                    "Brandl",
                                    "Brandner",
                                    "Brandstetter",
                                    "Brandst\u00E4tter",
                                    "Braun",
                                    "Brenner",
                                    "Bruckner",
                                    "Brugger",
                                    "Brunner",
                                    "Buchberger",
                                    "Buchegger",
                                    "Bucher",
                                    "Buchinger",
                                    "Buchner",
                                    "Burger",
                                    "Burgstaller",
                                    "Burtscher",
                                    "B\u00F6ck",
                                    "B\u00F6hm",
                                    "B\u00F6sch",
                                    "Danner",
                                    "Denk",
                                    "Deutsch",
                                    "Dietrich",
                                    "Dobler",
                                    "Doppler",
                                    "Dorner",
                                    "Draxler",
                                    "Eberharter",
                                    "Eberl",
                                    "Ebner",
                                    "Ecker",
                                    "Eder",
                                    "Edlinger",
                                    "Egger",
                                    "Eibl",
                                    "Eichberger",
                                    "Eichinger",
                                    "Eigner",
                                    "Erhart",
                                    "Ernst",
                                    "Ertl",
                                    "Falkner",
                                    "Fasching",
                                    "Feichtinger",
                                    "Fellner",
                                    "Fiala",
                                    "Fichtinger",
                                    "Fiedler",
                                    "Fink",
                                    "Fischer",
                                    "Fleischhacker",
                                    "Forster",
                                    "Forstner",
                                    "Frank",
                                    "Franz",
                                    "Friedl",
                                    "Friedrich",
                                    "Fritsch",
                                    "Fritz",
                                    "Fr\u00F6hlich",
                                    "Fr\u00FChwirth",
                                    "Fuchs",
                                    "F\u00FChrer",
                                    "F\u00FCrst",
                                    "Gabriel",
                                    "Gangl",
                                    "Gartner",
                                    "Gasser",
                                    "Gassner",
                                    "Geiger",
                                    "Geisler",
                                    "Geyer",
                                    "Glaser",
                                    "Glatz",
                                    "Gmeiner",
                                    "Grabner",
                                    "Graf",
                                    "Gratzer",
                                    "Greiner",
                                    "Grill",
                                    "Gritsch",
                                    "Gross",
                                    "Gro\u00DF",
                                    "Gruber",
                                    "Gr\u00FCnwald",
                                    "Gschwandtner",
                                    "Gutmann",
                                    "Haas",
                                    "Haberl",
                                    "Hackl",
                                    "Hafner",
                                    "Hagen",
                                    "Hager",
                                    "Hahn",
                                    "Haider",
                                    "Haidinger",
                                    "Haller",
                                    "Hammer",
                                    "Hammerl",
                                    "Handl",
                                    "Handler",
                                    "Harrer",
                                    "Hartl",
                                    "Hartmann",
                                    "Haslinger",
                                    "Hauer",
                                    "Hauser",
                                    "Heindl",
                                    "Heinrich",
                                    "Hemetsberger",
                                    "Herbst",
                                    "Hermann",
                                    "Herzog",
                                    "Hinterberger",
                                    "Hinteregger",
                                    "Hinterleitner",
                                    "Hirsch",
                                    "Hochreiter",
                                    "Hofbauer",
                                    "Hofer",
                                    "Hoffmann",
                                    "Hofmann",
                                    "Hofst\u00E4tter",
                                    "Holzer",
                                    "Holzinger",
                                    "Holzmann",
                                    "Horvath",
                                    "Huber",
                                    "Huemer",
                                    "Hufnagl",
                                    "Humer",
                                    "Hummer",
                                    "Hutter",
                                    "H\u00E4mmerle",
                                    "H\u00F6dl",
                                    "H\u00F6fler",
                                    "H\u00F6ller",
                                    "H\u00F6lzl",
                                    "H\u00F6rmann",
                                    "H\u00FCtter",
                                    "Jahn",
                                    "Jandl",
                                    "Janisch",
                                    "Jovanovic",
                                    "Jung",
                                    "Jungwirth",
                                    "J\u00E4ger",
                                    "Kainz",
                                    "Kaiser",
                                    "Kaltenbrunner",
                                    "Kapeller",
                                    "Kargl",
                                    "Karl",
                                    "Karner",
                                    "Kastner",
                                    "Kaufmann",
                                    "Kellner",
                                    "Kern",
                                    "Kerschbaumer",
                                    "Kirchmair",
                                    "Kirchner",
                                    "Klammer",
                                    "Klein",
                                    "Klinger",
                                    "Klug",
                                    "Knapp",
                                    "Knoll",
                                    "Koch",
                                    "Kofler",
                                    "Kogler",
                                    "Kohl",
                                    "Koller",
                                    "Kollmann",
                                    "Konrad",
                                    "Kopp",
                                    "Kovacs",
                                    "Kraft",
                                    "Krainer",
                                    "Kramer",
                                    "Krammer",
                                    "Kraus",
                                    "Kremser",
                                    "Krenn",
                                    "Kreuzer",
                                    "Kronberger",
                                    "Kr\u00F6ll",
                                    "Kugler",
                                    "Kummer",
                                    "Kurz",
                                    "K\u00F6berl",
                                    "K\u00F6ck",
                                    "K\u00F6hler",
                                    "K\u00F6nig",
                                    "Lackner",
                                    "Lamprecht",
                                    "Lang",
                                    "Langer",
                                    "Lechner",
                                    "Lederer",
                                    "Leeb",
                                    "Lehner",
                                    "Leitgeb",
                                    "Leitner",
                                    "Lengauer",
                                    "Lenz",
                                    "Lettner",
                                    "Lindner",
                                    "List",
                                    "Loidl",
                                    "Lorenz",
                                    "Ludwig",
                                    "Luger",
                                    "Lukas",
                                    "Lutz",
                                    "L\u00F6ffler",
                                    "Mader",
                                    "Maier",
                                    "Maierhofer",
                                    "Mair",
                                    "Mairhofer",
                                    "Mandl",
                                    "Markovic",
                                    "Martin",
                                    "Maurer",
                                    "Mayer",
                                    "Mayerhofer",
                                    "Mayr",
                                    "Mayrhofer",
                                    "Meier",
                                    "Meixner",
                                    "Messner",
                                    "Meyer",
                                    "Mitterer",
                                    "Moosbrugger",
                                    "Moser",
                                    "Muhr",
                                    "M\u00FChlbacher",
                                    "M\u00FCller",
                                    "M\u00FCllner",
                                    "Nagl",
                                    "Nemeth",
                                    "Neubauer",
                                    "Neuhauser",
                                    "Neuhold",
                                    "Neumann",
                                    "Neumayer",
                                    "Neuner",
                                    "Neuwirth",
                                    "Nikolic",
                                    "Novak",
                                    "Nowak",
                                    "Nussbaumer",
                                    "Nu\u00DFbaumer",
                                    "Ofner",
                                    "Ortner",
                                    "Oswald",
                                    "Ott",
                                    "Paar",
                                    "Pacher",
                                    "Pammer",
                                    "Paul",
                                    "Payer",
                                    "Peer",
                                    "Penz",
                                    "Peter",
                                    "Petrovic",
                                    "Petz",
                                    "Pfeffer",
                                    "Pfeifer",
                                    "Pfeiffer",
                                    "Pfister",
                                    "Pfleger",
                                    "Pichler",
                                    "Pilz",
                                    "Pinter",
                                    "Pirker",
                                    "Plank",
                                    "Plattner",
                                    "Platzer",
                                    "Pointner",
                                    "Pokorny",
                                    "Pollak",
                                    "Posch",
                                    "Prem",
                                    "Prinz",
                                    "Probst",
                                    "Pucher",
                                    "Putz",
                                    "P\u00F6ll",
                                    "P\u00F6lzl",
                                    "P\u00F6schl",
                                    "P\u00FChringer",
                                    "Raab",
                                    "Rabl",
                                    "Rainer",
                                    "Rath",
                                    "Rauch",
                                    "Rausch",
                                    "Rauscher",
                                    "Rauter",
                                    "Rechberger",
                                    "Redl",
                                    "Reich",
                                    "Reichl",
                                    "Reindl",
                                    "Reiner",
                                    "Reinisch",
                                    "Reischl",
                                    "Reisinger",
                                    "Reiter",
                                    "Reiterer",
                                    "Renner",
                                    "Resch",
                                    "Richter",
                                    "Rieder",
                                    "Riedl",
                                    "Riedler",
                                    "Rieger",
                                    "Riegler",
                                    "Rieser",
                                    "Ritter",
                                    "Rosenberger",
                                    "Roth",
                                    "Rupp",
                                    "Sailer",
                                    "Sattler",
                                    "Sauer",
                                    "Schachinger",
                                    "Schachner",
                                    "Schaffer",
                                    "Schaller",
                                    "Scharf",
                                    "Schatz",
                                    "Schauer",
                                    "Scheiber",
                                    "Schenk",
                                    "Scheucher",
                                    "Schiefer",
                                    "Schiller",
                                    "Schindler",
                                    "Schlager",
                                    "Schl\u00F6gl",
                                    "Schmid",
                                    "Schmidt",
                                    "Schmied",
                                    "Schnabl",
                                    "Schneeberger",
                                    "Schneider",
                                    "Schober",
                                    "Scholz",
                                    "Schranz",
                                    "Schreiber",
                                    "Schreiner",
                                    "Schubert",
                                    "Schuh",
                                    "Schuller",
                                    "Schulz",
                                    "Schuster",
                                    "Schwab",
                                    "Schwaiger",
                                    "Schwaighofer",
                                    "Schwarz",
                                    "Schweiger",
                                    "Schweighofer",
                                    "Sch\u00F6n",
                                    "Sch\u00F6pf",
                                    "Sch\u00FCtz",
                                    "Seebacher",
                                    "Seidl",
                                    "Siegl",
                                    "Simon",
                                    "Singer",
                                    "Sommer",
                                    "Sonnleitner",
                                    "Spitzer",
                                    "Springer",
                                    "Stadler",
                                    "Stangl",
                                    "Stark",
                                    "Staudinger",
                                    "Steger",
                                    "Steinbauer",
                                    "Steinberger",
                                    "Steindl",
                                    "Steiner",
                                    "Steininger",
                                    "Steinkellner",
                                    "Steinlechner",
                                    "Steinwender",
                                    "Stelzer",
                                    "Stern",
                                    "Steurer",
                                    "Stocker",
                                    "Stockinger",
                                    "Strasser",
                                    "Strauss",
                                    "Strau\u00DF",
                                    "Strobl",
                                    "Stummer",
                                    "Sturm",
                                    "St\u00F6ckl",
                                    "St\u00F6ger",
                                    "Suppan",
                                    "Swoboda",
                                    "Szabo",
                                    "Thaler",
                                    "Thaller",
                                    "Thurner",
                                    "Tischler",
                                    "Toth",
                                    "Traxler",
                                    "Trimmel",
                                    "Trummer",
                                    "Ulrich",
                                    "Unger",
                                    "Unterberger",
                                    "Unterweger",
                                    "Urban",
                                    "Varga",
                                    "Vogel",
                                    "Vogl",
                                    "Wachter",
                                    "Wagner",
                                    "Walch",
                                    "Walcher",
                                    "Wallner",
                                    "Walter",
                                    "Weber",
                                    "Wechselberger",
                                    "Wegscheider",
                                    "Weidinger",
                                    "Weigl",
                                    "Weinberger",
                                    "Weiss",
                                    "Wei\u00DF",
                                    "Weninger",
                                    "Werner",
                                    "Wieland",
                                    "Wieser",
                                    "Wiesinger",
                                    "Wild",
                                    "Wilhelm",
                                    "Wimmer",
                                    "Windisch",
                                    "Winkler",
                                    "Winter",
                                    "Wirth",
                                    "Wittmann",
                                    "Wolf",
                                    "Wurm",
                                    "Wurzer",
                                    "Zach",
                                    "Zangerl",
                                    "Zauner",
                                    "Zechner",
                                    "Zehetner",
                                    "Zeilinger",
                                    "Zeller",
                                    "Zenz",
                                    "Ziegler",
                                    "Zimmermann",
                                    "Z\u00F6hrer");
                        });

        public Object titleMale =
                ZVal.arrayFromList(
                        "Herr", "Dr.", "Mag.", "Ing.", "Dipl.-Ing.", "Prof.", "Univ.Prof.");

        public Object titleFemale =
                ZVal.arrayFromList(
                        "Frau", "Dr.", "Maga.", "Ing.", "Dipl.-Ing.", "Prof.", "Univ.Prof.");

        public Object suffix = ZVal.arrayFromList("B.Sc.", "B.A.", "B.Eng.", "MBA.");
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\de_AT\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats",
                            "suffix",
                            "titleFemale",
                            "titleMale")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/de_AT/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
