package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.sv_SE.classes;

import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.passByReference.RuntimeArgsWithReferences;
import com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Calculator.classes.Luhn;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.annotations.ConvertedParameter;
import com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.classes.DateTime;
import com.runtimeconverter.runtime.classes.ClassConstantUtils;
import com.runtimeconverter.runtime.arrays.ZPair;
import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.StaticMethodUtils;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import static com.runtimeconverter.runtime.ZVal.toStringR;
import static com.runtimeconverter.runtime.ZVal.assignParameter;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/sv_SE/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    @ConvertedMethod
    @ConvertedParameter(
        index = 0,
        name = "birthdate",
        typeHint = "DateTime",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    @ConvertedParameter(
        index = 1,
        name = "gender",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    public Object personalIdentityNumber(RuntimeEnv env, Object... args) {
        Object birthdate = assignParameter(args, 0, true);
        if (null == birthdate) {
            birthdate = ZVal.getNull();
        }
        Object gender = assignParameter(args, 1, true);
        if (null == gender) {
            gender = ZVal.getNull();
        }
        Object randomDigits = null;
        Object datePart = null;
        Object checksum = null;
        if (!ZVal.isTrue(birthdate)) {
            birthdate = DateTime.runtimeStaticObject.dateTimeThisCentury(env);
        }

        datePart = env.callMethod(birthdate, "format", Person.class, "ymd");
        if (ZVal.toBool(gender)
                && ZVal.toBool(
                        ZVal.equalityCheck(
                                gender,
                                ClassConstantUtils.getConstantValueLateStatic(
                                        env, this, "GENDER_MALE")))) {
            randomDigits =
                    toStringR(
                                    toStringR(
                                            StaticMethodUtils.accessUnknownLateStaticMethod(
                                                            env, this, Person.class)
                                                    .method("numerify")
                                                    .addReferenceArgs(
                                                            new RuntimeArgsWithReferences())
                                                    .call("##")
                                                    .value(),
                                            env),
                                    env)
                            + toStringR(
                                    StaticMethodUtils.accessUnknownLateStaticMethod(
                                                    env, this, Person.class)
                                            .method("randomElement")
                                            .addReferenceArgs(new RuntimeArgsWithReferences())
                                            .call(ZVal.arrayFromList(1, 3, 5, 7, 9))
                                            .value(),
                                    env);

        } else if (ZVal.toBool(gender)
                && ZVal.toBool(
                        ZVal.equalityCheck(
                                gender,
                                ClassConstantUtils.getConstantValueLateStatic(
                                        env, this, "GENDER_FEMALE")))) {
            randomDigits =
                    toStringR(
                                    toStringR(
                                            StaticMethodUtils.accessUnknownLateStaticMethod(
                                                            env, this, Person.class)
                                                    .method("numerify")
                                                    .addReferenceArgs(
                                                            new RuntimeArgsWithReferences())
                                                    .call("##")
                                                    .value(),
                                            env),
                                    env)
                            + toStringR(
                                    StaticMethodUtils.accessUnknownLateStaticMethod(
                                                    env, this, Person.class)
                                            .method("randomElement")
                                            .addReferenceArgs(new RuntimeArgsWithReferences())
                                            .call(ZVal.arrayFromList(0, 2, 4, 6, 8))
                                            .value(),
                                    env);

        } else {
            randomDigits =
                    ZVal.assign(
                            toStringR(
                                    StaticMethodUtils.accessUnknownLateStaticMethod(
                                                    env, this, Person.class)
                                            .method("numerify")
                                            .addReferenceArgs(new RuntimeArgsWithReferences())
                                            .call("###")
                                            .value(),
                                    env));
        }

        checksum =
                Luhn.runtimeStaticObject.computeCheckDigit(
                        env, toStringR(datePart, env) + toStringR(randomDigits, env));
        return ZVal.assign(
                toStringR(datePart, env)
                        + "-"
                        + toStringR(randomDigits, env)
                        + toStringR(checksum, env));
    }

    public static final Object CONST_class = "Faker\\Provider\\sv_SE\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object formats =
                ZVal.arrayFromList(
                        "{{firstName}} {{lastName}}",
                        "{{firstName}} {{lastName}}",
                        "{{firstName}} {{lastName}}",
                        "{{firstName}} {{lastName}}",
                        "{{firstName}} {{lastName}}",
                        "{{firstName}} {{firstName}} {{lastName}}",
                        "{{firstName}} {{firstName}} {{lastName}}",
                        "{{firstName}} {{firstName}} {{lastName}}",
                        "{{firstName}} {{lastName}} {{lastName}}",
                        "{{firstName}} {{lastName}}-{{lastName}}",
                        "{{firstName}} {{firstName}} {{lastName}}-{{lastName}}");

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Ada",
                                    "Adela",
                                    "Adele",
                                    "Ad\u00E9le",
                                    "Adelia",
                                    "Adina",
                                    "Adolfina",
                                    "Agda",
                                    "Agnes",
                                    "Agneta",
                                    "Aina",
                                    "Aino",
                                    "Albertina",
                                    "Alexandra",
                                    "Alfhild",
                                    "Alfrida",
                                    "Alice",
                                    "Alida",
                                    "Ally",
                                    "Alma",
                                    "Alva",
                                    "Amalia",
                                    "Amanda",
                                    "Andrea",
                                    "Anette",
                                    "Angela",
                                    "Anita",
                                    "Anja",
                                    "Ann",
                                    "Anna",
                                    "Anna-Carin",
                                    "Anna-Greta",
                                    "Anna-Karin",
                                    "Anna-Lena",
                                    "Anna-Lisa",
                                    "Anna-Maria",
                                    "Anna-Stina",
                                    "Anne",
                                    "Anneli",
                                    "Annelie",
                                    "Annette",
                                    "Anne-Charlotte",
                                    "Anne-Marie",
                                    "Anni",
                                    "Annica",
                                    "Annie",
                                    "Annika",
                                    "Annikki",
                                    "Anny",
                                    "Ann-Britt",
                                    "Ann-Charlott",
                                    "Ann-Charlotte",
                                    "Ann-Christin",
                                    "Ann-Christine",
                                    "Ann-Katrin",
                                    "Ann-Kristin",
                                    "Ann-Louise",
                                    "Ann-Margret",
                                    "Ann-Mari",
                                    "Ann-Marie",
                                    "Ann-Sofi",
                                    "Ann-Sofie",
                                    "Antonia",
                                    "Arvida",
                                    "Asta",
                                    "Astrid",
                                    "Augusta",
                                    "Aurora",
                                    "Axelia",
                                    "Axelina",
                                    "Barbro",
                                    "Beata",
                                    "Beatrice",
                                    "Beda",
                                    "Berit",
                                    "Bernhardina",
                                    "Berta",
                                    "Betty",
                                    "Birgit",
                                    "Birgitta",
                                    "Blenda",
                                    "Bodil",
                                    "Boel",
                                    "Borghild",
                                    "Brita",
                                    "Britt",
                                    "Britta",
                                    "Britt-Inger",
                                    "Britt-Louise",
                                    "Britt-Mari",
                                    "Britt-Marie",
                                    "Camilla",
                                    "Carin",
                                    "Carina",
                                    "Carita",
                                    "Carola",
                                    "Carolina",
                                    "Caroline",
                                    "Catarina",
                                    "Catharina",
                                    "Cathrine",
                                    "Catrin",
                                    "Cecilia",
                                    "Charlott",
                                    "Charlotta",
                                    "Charlotte",
                                    "Christel",
                                    "Christin",
                                    "Christina",
                                    "Christine",
                                    "Clara",
                                    "Clary",
                                    "Constance",
                                    "Cristina",
                                    "Daga",
                                    "Dagmar",
                                    "Dagny",
                                    "Daisy",
                                    "Davida",
                                    "Desideria",
                                    "Desir\u00E9e",
                                    "Diana",
                                    "Disa",
                                    "Dora",
                                    "Doris",
                                    "Dorotea",
                                    "Ebba",
                                    "Edit",
                                    "Edith",
                                    "Edla",
                                    "Eira",
                                    "Eivor",
                                    "Ejvor",
                                    "Elaine",
                                    "Eleonor",
                                    "Eleonora",
                                    "Elfrida",
                                    "Elida",
                                    "Elin",
                                    "Elina",
                                    "Elinor",
                                    "Elisabet",
                                    "Elisabeth",
                                    "Elise",
                                    "Ella",
                                    "Ellen",
                                    "Ellinor",
                                    "Elly",
                                    "Elma",
                                    "Elna",
                                    "Elsa",
                                    "Else",
                                    "Else-Marie",
                                    "Elsi",
                                    "Elsie",
                                    "Elsy",
                                    "Elvi",
                                    "Elvira",
                                    "Elvy",
                                    "Emelia",
                                    "Emerentia",
                                    "Emilia",
                                    "Emma",
                                    "Emmy",
                                    "Erika",
                                    "Erna",
                                    "Ester",
                                    "Estrid",
                                    "Ethel",
                                    "Eufemia",
                                    "Eugenia",
                                    "Eva",
                                    "Eva-Britt",
                                    "Eva-Lena",
                                    "Eva-Lotta",
                                    "Eva-Marie",
                                    "Evelina",
                                    "Evelyn",
                                    "Evy",
                                    "Ewa",
                                    "Fanny",
                                    "Florence",
                                    "Fredrika",
                                    "Frida",
                                    "Frideborg",
                                    "Gabriella",
                                    "Gerd",
                                    "Gerda",
                                    "Gertie",
                                    "Gertrud",
                                    "Gisela",
                                    "Greta",
                                    "Gudrun",
                                    "Gull",
                                    "Gullan",
                                    "Gullbritt",
                                    "Gulli",
                                    "Gullvi",
                                    "Gully",
                                    "Gull-Britt",
                                    "Gun",
                                    "Gunborg",
                                    "Gunbritt",
                                    "Gunda",
                                    "Gunhild",
                                    "Gunilla",
                                    "Gunn",
                                    "Gunnel",
                                    "Gunni",
                                    "Gunvor",
                                    "Gun-Britt",
                                    "Gurli",
                                    "Gustava",
                                    "G\u00E4rd",
                                    "G\u00F6rel",
                                    "G\u00F6ta",
                                    "Hanna",
                                    "Harriet",
                                    "Hedvig",
                                    "Helen",
                                    "Hel\u00E9n",
                                    "Helena",
                                    "Helene",
                                    "Hel\u00E9ne",
                                    "Helfrid",
                                    "Helga",
                                    "Helmi",
                                    "Helny",
                                    "Henny",
                                    "Henrietta",
                                    "Henriette",
                                    "Herta",
                                    "Hilda",
                                    "Hildegard",
                                    "Hildur",
                                    "Hillevi",
                                    "Hilma",
                                    "Hj\u00F6rdis",
                                    "Hulda",
                                    "Ida",
                                    "Ines",
                                    "Inez",
                                    "Inga",
                                    "Ingalill",
                                    "Inga-Britt",
                                    "Inga-Lena",
                                    "Inga-Lill",
                                    "Inga-Lisa",
                                    "Inga-Maj",
                                    "Ingbritt",
                                    "Ingeborg",
                                    "Ingegerd",
                                    "Ingeg\u00E4rd",
                                    "Ingela",
                                    "Inger",
                                    "Ingrid",
                                    "Ingvor",
                                    "Ing-Britt",
                                    "Ing-Mari",
                                    "Ing-Marie",
                                    "Ir\u00E9ne",
                                    "Irene",
                                    "Iris",
                                    "Irma",
                                    "Isabella",
                                    "Jane",
                                    "Janet",
                                    "Jeanette",
                                    "Jenny",
                                    "Jessica",
                                    "Johanna",
                                    "Josefina",
                                    "Judit",
                                    "Judith",
                                    "Julia",
                                    "Juliana",
                                    "Justina",
                                    "Kaarina",
                                    "Kajsa",
                                    "Karin",
                                    "Karina",
                                    "Karla",
                                    "Karola",
                                    "Karolina",
                                    "Katarina",
                                    "Katharina",
                                    "Katrin",
                                    "Katrina",
                                    "Kersti",
                                    "Kerstin",
                                    "Klara",
                                    "Konstantia",
                                    "Kornelia",
                                    "Kristin",
                                    "Kristina",
                                    "Kristine",
                                    "Laila",
                                    "Laura",
                                    "Leila",
                                    "Lena",
                                    "Leontina",
                                    "Liisa",
                                    "Lilian",
                                    "Lill",
                                    "Lillemor",
                                    "Lillian",
                                    "Lilly",
                                    "Linda",
                                    "Linn\u00E9a",
                                    "Linnea",
                                    "Lisa",
                                    "Lisbet",
                                    "Lisbeth",
                                    "Liselott",
                                    "Liselotte",
                                    "Lise-Lott",
                                    "Lise-Lotte",
                                    "Lizzie",
                                    "Lola",
                                    "Louise",
                                    "Lovisa",
                                    "Lucia",
                                    "Lydia",
                                    "Madeleine",
                                    "Madelene",
                                    "Magda",
                                    "Magdalena",
                                    "Magnhild",
                                    "Maj",
                                    "Maja",
                                    "Majbritt",
                                    "Majken",
                                    "Majlis",
                                    "Majvor",
                                    "Maj-Britt",
                                    "Maj-Lis",
                                    "Malin",
                                    "Malvina",
                                    "Margaret",
                                    "Margareta",
                                    "Margareth",
                                    "Margaretha",
                                    "Margit",
                                    "Margita",
                                    "Margot",
                                    "Margret",
                                    "Margreta",
                                    "Mari",
                                    "Maria",
                                    "Mariana",
                                    "Mariann",
                                    "Marianne",
                                    "Marie",
                                    "Mariette",
                                    "Marie-Louise",
                                    "Marika",
                                    "Marina",
                                    "Marion",
                                    "Marit",
                                    "Marita",
                                    "Mari-Ann",
                                    "Marja",
                                    "Marjatta",
                                    "Marlene",
                                    "Marta",
                                    "Martha",
                                    "Martina",
                                    "Mary",
                                    "Mathilda",
                                    "Matilda",
                                    "Maud",
                                    "May",
                                    "Mia",
                                    "Mildred",
                                    "Mimmi",
                                    "Mirjam",
                                    "Mona",
                                    "Monica",
                                    "Monika",
                                    "M\u00E4rit",
                                    "M\u00E4rta",
                                    "M\u00E4rtha",
                                    "Naemi",
                                    "Naima",
                                    "Nancy",
                                    "Nanna",
                                    "Nanny",
                                    "Natalia",
                                    "Nelly",
                                    "Nina",
                                    "Nora",
                                    "Olga",
                                    "Olivia",
                                    "Ottilia",
                                    "Paula",
                                    "Paulina",
                                    "Pauline",
                                    "Pernilla",
                                    "Petra",
                                    "Petronella",
                                    "Pia",
                                    "Ragna",
                                    "Ragnhild",
                                    "Rakel",
                                    "Rebecka",
                                    "Regina",
                                    "Ren\u00E9e",
                                    "Rigmor",
                                    "Rita",
                                    "Rosa",
                                    "Rose",
                                    "Rose-Marie",
                                    "Rosita",
                                    "Ros-Mari",
                                    "Ros-Marie",
                                    "Runa",
                                    "Rut",
                                    "Ruth",
                                    "Sabina",
                                    "Saga",
                                    "Sally",
                                    "Sara",
                                    "Selma",
                                    "Serafia",
                                    "Sibylla",
                                    "Sigbritt",
                                    "Signe",
                                    "Signhild",
                                    "Sigrid",
                                    "Siri",
                                    "Siv",
                                    "Sofi",
                                    "Sofia",
                                    "Sofie",
                                    "Solbritt",
                                    "Solveig",
                                    "Solvig",
                                    "Sonja",
                                    "Stina",
                                    "Susann",
                                    "Susanna",
                                    "Susanne",
                                    "Suzanne",
                                    "Svea",
                                    "Sylvia",
                                    "Synn\u00F6ve",
                                    "Syster",
                                    "Tea",
                                    "Tekla",
                                    "Terese",
                                    "Teresia",
                                    "Ther\u00E9se",
                                    "Therese",
                                    "Theresia",
                                    "Thyra",
                                    "Tina",
                                    "Tora",
                                    "Torborg",
                                    "Tove",
                                    "Tyra",
                                    "Ulla",
                                    "Ulla-Britt",
                                    "Ulla-Britta",
                                    "Ulrica",
                                    "Ulrika",
                                    "Ursula",
                                    "Valborg",
                                    "Vanja",
                                    "Vega",
                                    "Vendela",
                                    "Vendla",
                                    "Vera",
                                    "Veronica",
                                    "Veronika",
                                    "Victoria",
                                    "Viktoria",
                                    "Vilhelmina",
                                    "Vilma",
                                    "Viola",
                                    "Virginia",
                                    "Vivan",
                                    "Viveca",
                                    "Viveka",
                                    "Vivi",
                                    "Vivian",
                                    "Viviann",
                                    "Vivianne",
                                    "Vivi-Ann",
                                    "Vivi-Anne",
                                    "Wilhelmina",
                                    "Ylva",
                                    "Yvonne",
                                    "\u00C5sa",
                                    "\u00C5se");
                        });

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abraham",
                                    "Adam",
                                    "Adolf",
                                    "Adrian",
                                    "Agaton",
                                    "Agne",
                                    "Albert",
                                    "Albin",
                                    "Aldor",
                                    "Alex",
                                    "Alexander",
                                    "Alexis",
                                    "Alexius",
                                    "Alf",
                                    "Alfons",
                                    "Alfred",
                                    "Algot",
                                    "Allan",
                                    "Alrik",
                                    "Alvar",
                                    "Alve",
                                    "Amandus",
                                    "Anders",
                                    "Andr\u00E9",
                                    "Andreas",
                                    "Anselm",
                                    "Anshelm",
                                    "Antero",
                                    "Anton",
                                    "Antonius",
                                    "Arne",
                                    "Arnold",
                                    "Aron",
                                    "Arthur",
                                    "Artur",
                                    "Arvid",
                                    "Assar",
                                    "Astor",
                                    "August",
                                    "Augustin",
                                    "Axel",
                                    "Bengt",
                                    "Bengt-G\u00F6ran",
                                    "Bengt-Olof",
                                    "Bengt-\u00C5ke",
                                    "Benny",
                                    "Berndt",
                                    "Berne",
                                    "Bernhard",
                                    "Bernt",
                                    "Bert",
                                    "Berth",
                                    "Berthold",
                                    "Bertil",
                                    "Bill",
                                    "Billy",
                                    "Birger",
                                    "Bjarne",
                                    "Bj\u00F6rn",
                                    "Bo",
                                    "Boris",
                                    "Bror",
                                    "Bruno",
                                    "Brynolf",
                                    "B\u00F6rje",
                                    "Carl",
                                    "Carl-Axel",
                                    "Carl-Erik",
                                    "Carl-Gustaf",
                                    "Carl-Gustav",
                                    "Carl-Johan",
                                    "Charles",
                                    "Christer",
                                    "Christian",
                                    "Claes",
                                    "Claes-G\u00F6ran",
                                    "Clarence",
                                    "Clas",
                                    "Conny",
                                    "Crister",
                                    "Curt",
                                    "Dag",
                                    "Dan",
                                    "Daniel",
                                    "David",
                                    "Dennis",
                                    "Dick",
                                    "Donald",
                                    "Douglas",
                                    "Ebbe",
                                    "Eddie",
                                    "Eddy",
                                    "Edgar",
                                    "Edmund",
                                    "Edvard",
                                    "Edvin",
                                    "Efraim",
                                    "Egon",
                                    "Eilert",
                                    "Einar",
                                    "Eje",
                                    "Ejnar",
                                    "Elias",
                                    "Elis",
                                    "Ellert",
                                    "Elmer",
                                    "Elof",
                                    "Elon",
                                    "Elov",
                                    "Elving",
                                    "Elvir",
                                    "Emanuel",
                                    "Emil",
                                    "Enar",
                                    "Engelbert",
                                    "Engelbrekt",
                                    "Enok",
                                    "Erhard",
                                    "Eric",
                                    "Erik",
                                    "Erland",
                                    "Erling",
                                    "Ernfrid",
                                    "Ernst",
                                    "Esbj\u00F6rn",
                                    "Eskil",
                                    "Eug\u00E9n",
                                    "Eugen",
                                    "Evald",
                                    "Eve",
                                    "Evert",
                                    "Fabian",
                                    "Felix",
                                    "Ferdinand",
                                    "Filip",
                                    "Fingal",
                                    "Finn",
                                    "Folke",
                                    "Frank",
                                    "Frans",
                                    "Franz",
                                    "Fred",
                                    "Fredrik",
                                    "Fridolf",
                                    "Friedrich",
                                    "Fritiof",
                                    "Fritjof",
                                    "Frits",
                                    "Fritz",
                                    "Gabriel",
                                    "Georg",
                                    "George",
                                    "Gerhard",
                                    "Gert",
                                    "Gideon",
                                    "Gilbert",
                                    "Gillis",
                                    "Glenn",
                                    "Gottfrid",
                                    "Gotthard",
                                    "Greger",
                                    "Gudmund",
                                    "Gunder",
                                    "Gunnar",
                                    "Gustaf",
                                    "Gustav",
                                    "G\u00F6ran",
                                    "G\u00F6rgen",
                                    "G\u00F6sta",
                                    "G\u00F6te",
                                    "Hadar",
                                    "Halvar",
                                    "Halvard",
                                    "Hans",
                                    "Hans-Erik",
                                    "Hans-Olof",
                                    "Hans-\u00C5ke",
                                    "Harald",
                                    "Hardy",
                                    "Harry",
                                    "Hartvig",
                                    "Hasse",
                                    "Heinrich",
                                    "Heinz",
                                    "Helge",
                                    "Helmer",
                                    "Henning",
                                    "Henric",
                                    "Henrik",
                                    "Henry",
                                    "Herbert",
                                    "Heribert",
                                    "Herman",
                                    "Hilbert",
                                    "Hilding",
                                    "Hilmer",
                                    "Hjalmar",
                                    "Holger",
                                    "Holmfrid",
                                    "Hubert",
                                    "Hugo",
                                    "H\u00E5kan",
                                    "Inge",
                                    "Ingemar",
                                    "Ingmar",
                                    "Ingvald",
                                    "Ingvar",
                                    "Isak",
                                    "Isidor",
                                    "Ivan",
                                    "Ivar",
                                    "Jack",
                                    "Jacob",
                                    "Jakob",
                                    "James",
                                    "Jan",
                                    "Janne",
                                    "Jan-Eric",
                                    "Jan-Erik",
                                    "Jan-Olof",
                                    "Jan-Olov",
                                    "Jan-Ove",
                                    "Jan-\u00C5ke",
                                    "Jarl",
                                    "Jean",
                                    "Jens",
                                    "Jerker",
                                    "Jerry",
                                    "Jesper",
                                    "Jim",
                                    "Jimmy",
                                    "Joachim",
                                    "Joacim",
                                    "Joakim",
                                    "Joel",
                                    "Johan",
                                    "Johannes",
                                    "John",
                                    "Johnny",
                                    "Johny",
                                    "Jon",
                                    "Jonas",
                                    "Jonny",
                                    "Josef",
                                    "Juhani",
                                    "Julius",
                                    "Justus",
                                    "J\u00F6ns",
                                    "J\u00F6rgen",
                                    "Kai",
                                    "Kaj",
                                    "Kalevi",
                                    "Karl",
                                    "Karl-Axel",
                                    "Karl-Erik",
                                    "Karl-Gunnar",
                                    "Karl-Gustaf",
                                    "Karl-Gustav",
                                    "Karl-Johan",
                                    "Kennert",
                                    "Kennet",
                                    "Kenneth",
                                    "Kenny",
                                    "Kent",
                                    "Kenth",
                                    "Kjell",
                                    "Kjell-\u00C5ke",
                                    "Klas",
                                    "Knut",
                                    "Konrad",
                                    "Konstantin",
                                    "Krister",
                                    "Kristian",
                                    "Kristoffer",
                                    "Kurt",
                                    "K\u00E5re",
                                    "Lage",
                                    "Lambert",
                                    "Lars",
                                    "Lars-Eric",
                                    "Lars-Erik",
                                    "Lars-Gunnar",
                                    "Lars-G\u00F6ran",
                                    "Lars-Olof",
                                    "Lars-Olov",
                                    "Lars-Ove",
                                    "Lars-\u00C5ke",
                                    "Laurentius",
                                    "Leander",
                                    "Leif",
                                    "Lennart",
                                    "Leo",
                                    "Leon",
                                    "Leonard",
                                    "Leopold",
                                    "Levi",
                                    "Levin",
                                    "Linn\u00E9",
                                    "Linus",
                                    "Lorentz",
                                    "Louis",
                                    "Ludvig",
                                    "Magni",
                                    "Magnus",
                                    "Malkolm",
                                    "Malte",
                                    "Manfred",
                                    "Manne",
                                    "Marcus",
                                    "Markus",
                                    "Martin",
                                    "Mathias",
                                    "Mats",
                                    "Matti",
                                    "Mattias",
                                    "Matts",
                                    "Maurits",
                                    "Mauritz",
                                    "Max",
                                    "Melker",
                                    "Micael",
                                    "Michael",
                                    "Mickael",
                                    "Mikael",
                                    "Morgan",
                                    "M\u00E5ns",
                                    "M\u00E5rten",
                                    "Napoleon",
                                    "Natanael",
                                    "Nicklas",
                                    "Niclas",
                                    "Niklas",
                                    "Nikolaus",
                                    "Nils",
                                    "Nils-Erik",
                                    "Nore",
                                    "Odd",
                                    "Ola",
                                    "Olaus",
                                    "Olav",
                                    "Olavi",
                                    "Ole",
                                    "Oliver",
                                    "Olle",
                                    "Olof",
                                    "Olov",
                                    "Orvar",
                                    "Oscar",
                                    "Oskar",
                                    "Ossian",
                                    "Osvald",
                                    "Otto",
                                    "Ove",
                                    "Owe",
                                    "Patric",
                                    "Patrick",
                                    "Patrik",
                                    "Paul",
                                    "Peder",
                                    "Per",
                                    "Percy",
                                    "Per-Anders",
                                    "Per-Arne",
                                    "Per-Erik",
                                    "Per-Ola",
                                    "Per-Olof",
                                    "Per-Olov",
                                    "Per-\u00C5ke",
                                    "Peter",
                                    "Petrus",
                                    "Petter",
                                    "Pierre",
                                    "Pontus",
                                    "P\u00E4r",
                                    "Ragnar",
                                    "Ragnvald",
                                    "Ralf",
                                    "Ralph",
                                    "Raymond",
                                    "Reidar",
                                    "Reine",
                                    "Reinhold",
                                    "Reino",
                                    "Richard",
                                    "Rickard",
                                    "Rikard",
                                    "Robert",
                                    "Roger",
                                    "Roine",
                                    "Roland",
                                    "Rolf",
                                    "Ronald",
                                    "Ronnie",
                                    "Ronny",
                                    "Roy",
                                    "Ruben",
                                    "Rudolf",
                                    "Runar",
                                    "Rune",
                                    "Runo",
                                    "Rutger",
                                    "Salomon",
                                    "Sam",
                                    "Samuel",
                                    "Sanfrid",
                                    "Sebastian",
                                    "Set",
                                    "Seth",
                                    "Seved",
                                    "Severin",
                                    "Sigfrid",
                                    "Sigmund",
                                    "Signar",
                                    "Sigurd",
                                    "Sigvard",
                                    "Simon",
                                    "Sivert",
                                    "Sixten",
                                    "Sonny",
                                    "Staffan",
                                    "Stanley",
                                    "Stefan",
                                    "Stellan",
                                    "Sten",
                                    "Stephan",
                                    "Steve",
                                    "Stig",
                                    "Sture",
                                    "Sune",
                                    "Svante",
                                    "Sven",
                                    "Sven-Erik",
                                    "Sven-Olof",
                                    "Sven-Olov",
                                    "Sven-\u00C5ke",
                                    "Sverker",
                                    "S\u00F6lve",
                                    "S\u00F6ren",
                                    "Tage",
                                    "Ted",
                                    "Teodor",
                                    "Theodor",
                                    "Thomas",
                                    "Thor",
                                    "Thorbj\u00F6rn",
                                    "Thord",
                                    "Thore",
                                    "Thorsten",
                                    "Thorvald",
                                    "Thure",
                                    "Tobias",
                                    "Toivo",
                                    "Tom",
                                    "Tomas",
                                    "Tommy",
                                    "Tonny",
                                    "Tony",
                                    "Tor",
                                    "Torbj\u00F6rn",
                                    "Tord",
                                    "Tore",
                                    "Torgny",
                                    "Torkel",
                                    "Torsten",
                                    "Torvald",
                                    "Tryggve",
                                    "Ture",
                                    "Tyko",
                                    "Ulf",
                                    "Ulrik",
                                    "Uno",
                                    "Urban",
                                    "Valdemar",
                                    "Valentin",
                                    "Valfrid",
                                    "Vallentin",
                                    "Valter",
                                    "Veine",
                                    "Verner",
                                    "Victor",
                                    "Vidar",
                                    "Viggo",
                                    "Viking",
                                    "Viktor",
                                    "Vilgot",
                                    "Vilhelm",
                                    "Villiam",
                                    "Villy",
                                    "Vincent",
                                    "Vitalis",
                                    "Waldemar",
                                    "Walter",
                                    "Werner",
                                    "Wilhelm",
                                    "William",
                                    "Willy",
                                    "Yngve",
                                    "\u00C5ke",
                                    "\u00D6rjan",
                                    "\u00D6sten");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abrahamsson",
                                    "Andersson",
                                    "Andreasson",
                                    "Arvidsson",
                                    "Axelsson",
                                    "Bengtsson",
                                    "Berg",
                                    "Berggren",
                                    "Berglund",
                                    "Bergman",
                                    "Bergqvist",
                                    "Bergstr\u00F6m",
                                    "Bj\u00F6rk",
                                    "Bj\u00F6rklund",
                                    "Blom",
                                    "Blomqvist",
                                    "Claesson",
                                    "Dahlberg",
                                    "Danielsson",
                                    "Engstr\u00F6m",
                                    "Ek",
                                    "Eklund",
                                    "Ekstr\u00F6m",
                                    "Eliasson",
                                    "Eriksson",
                                    "Falk",
                                    "Forsberg",
                                    "Fransson",
                                    "Fredriksson",
                                    "Gunnarsson",
                                    "Gustafsson",
                                    "Hansen",
                                    "Hansson",
                                    "Hedlund",
                                    "Hellstr\u00F6m",
                                    "Henriksson",
                                    "Hermansson",
                                    "Holm",
                                    "Holmberg",
                                    "Holmgren",
                                    "Holmqvist",
                                    "H\u00E5kansson",
                                    "Isaksson",
                                    "Ivarsson",
                                    "Jakobsson",
                                    "Jansson",
                                    "Johansson",
                                    "Jonasson",
                                    "Jonsson",
                                    "J\u00F6nsson",
                                    "Karlsson",
                                    "Larsson",
                                    "Lind",
                                    "Lindberg",
                                    "Lindgren",
                                    "Lindholm",
                                    "Lindqvist",
                                    "Lindstr\u00F6m",
                                    "Lund",
                                    "Lundberg",
                                    "Lundgren",
                                    "Lundin",
                                    "Lundqvist",
                                    "Lundstr\u00F6m",
                                    "L\u00F6fgren",
                                    "Magnusson",
                                    "Martinsson",
                                    "Mattsson",
                                    "M\u00E5nsson",
                                    "M\u00E5rtensson",
                                    "Nilsson",
                                    "Norberg",
                                    "Nordin",
                                    "Nordstr\u00F6m",
                                    "Nyberg",
                                    "Nystr\u00F6m",
                                    "Olofsson",
                                    "Olsson",
                                    "Persson",
                                    "Pettersson",
                                    "P\u00E5lsson",
                                    "Samuelsson",
                                    "Sandberg",
                                    "Sandstr\u00F6m",
                                    "Sj\u00F6berg",
                                    "Sj\u00F6gren",
                                    "Str\u00F6m",
                                    "Str\u00F6mberg",
                                    "Sundberg",
                                    "Sundqvist",
                                    "Sundstr\u00F6m",
                                    "Svensson",
                                    "S\u00F6derberg",
                                    "Viklund",
                                    "Wallin",
                                    "Wikstr\u00F6m",
                                    "\u00C5berg",
                                    "\u00C5kesson",
                                    "\u00C5str\u00F6m",
                                    "\u00D6berg");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\sv_SE\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "firstNameFemale", "firstNameMale", "formats", "lastName")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/sv_SE/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
