package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.it_CH.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/it_CH/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .namespaces
                .it_IT
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\it_CH\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .namespaces
                    .it_IT
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aaron",
                                    "Adriano",
                                    "Alain",
                                    "Alan",
                                    "Alberto",
                                    "Aldo",
                                    "Alessandro",
                                    "Alessio",
                                    "Alex",
                                    "Alexander",
                                    "Alfredo",
                                    "Andrea",
                                    "Andreas",
                                    "Andr\u00E9",
                                    "Angelo",
                                    "Antonino",
                                    "Antonio",
                                    "Aris",
                                    "Armando",
                                    "Arturo",
                                    "Athos",
                                    "Attilio",
                                    "Augusto",
                                    "Aurelio",
                                    "Boris",
                                    "Bruno",
                                    "Carlo",
                                    "Carlos",
                                    "Carmelo",
                                    "Carmine",
                                    "Cesare",
                                    "Christian",
                                    "Claudio",
                                    "Corrado",
                                    "Cristian",
                                    "Cristiano",
                                    "Damiano",
                                    "Daniel",
                                    "Daniele",
                                    "Danilo",
                                    "Dante",
                                    "Dario",
                                    "David",
                                    "Davide",
                                    "Denis",
                                    "Diego",
                                    "Domenico",
                                    "Donato",
                                    "Edoardo",
                                    "Elia",
                                    "Elio",
                                    "Emanuele",
                                    "Emilio",
                                    "Enea",
                                    "Enrico",
                                    "Enzo",
                                    "Eric",
                                    "Ernesto",
                                    "Eros",
                                    "Ettore",
                                    "Eugenio",
                                    "Ezio",
                                    "Fabiano",
                                    "Fabio",
                                    "Fabrizio",
                                    "Fausto",
                                    "Federico",
                                    "Felice",
                                    "Fernando",
                                    "Filippo",
                                    "Fiorenzo",
                                    "Flavio",
                                    "Francesco",
                                    "Franco",
                                    "Fulvio",
                                    "Gabriel",
                                    "Gabriele",
                                    "Gaetano",
                                    "Gerardo",
                                    "Giacomo",
                                    "Gian",
                                    "Giancarlo",
                                    "Gianfranco",
                                    "Gianluca",
                                    "Gianni",
                                    "Gioele",
                                    "Giona",
                                    "Giordano",
                                    "Giorgio",
                                    "Giovanni",
                                    "Giuliano",
                                    "Giulio",
                                    "Giuseppe",
                                    "Graziano",
                                    "Guido",
                                    "Hans",
                                    "Igor",
                                    "Ivan",
                                    "Ivano",
                                    "Ivo",
                                    "Jacopo",
                                    "Jean",
                                    "Joel",
                                    "Jonathan",
                                    "Jos\u00E9",
                                    "Kevin",
                                    "Kurt",
                                    "Leandro",
                                    "Leonardo",
                                    "Liam",
                                    "Livio",
                                    "Lorenzo",
                                    "Loris",
                                    "Luca",
                                    "Luciano",
                                    "Lucio",
                                    "Luigi",
                                    "Luis",
                                    "Manuel",
                                    "Marcello",
                                    "Marco",
                                    "Marino",
                                    "Mario",
                                    "Marko",
                                    "Markus",
                                    "Martin",
                                    "Martino",
                                    "Marzio",
                                    "Massimiliano",
                                    "Massimo",
                                    "Matteo",
                                    "Mattia",
                                    "Maurizio",
                                    "Mauro",
                                    "Michael",
                                    "Michel",
                                    "Michele",
                                    "Mirco",
                                    "Mirko",
                                    "Moreno",
                                    "Nathan",
                                    "Nicola",
                                    "Nicolas",
                                    "Nicol\u00F2",
                                    "Noah",
                                    "Oliver",
                                    "Omar",
                                    "Oscar",
                                    "Paolo",
                                    "Pasquale",
                                    "Patrick",
                                    "Paul",
                                    "Pedro",
                                    "Peter",
                                    "Pier",
                                    "Pierluigi",
                                    "Piero",
                                    "Pietro",
                                    "Raffaele",
                                    "Remo",
                                    "Renato",
                                    "Renzo",
                                    "Ren\u00E9",
                                    "Reto",
                                    "Riccardo",
                                    "Robert",
                                    "Roberto",
                                    "Rocco",
                                    "Roland",
                                    "Rolf",
                                    "Romano",
                                    "Rosario",
                                    "Ruben",
                                    "Rudolf",
                                    "Sacha",
                                    "Salvatore",
                                    "Samuel",
                                    "Samuele",
                                    "Sandro",
                                    "Sebastian",
                                    "Sebastiano",
                                    "Sergio",
                                    "Silvano",
                                    "Silvio",
                                    "Simon",
                                    "Simone",
                                    "Stefan",
                                    "Stefano",
                                    "Thomas",
                                    "Tiziano",
                                    "Tommaso",
                                    "Valentino",
                                    "Valerio",
                                    "Vincenzo",
                                    "Vito",
                                    "Vittorio",
                                    "Walter",
                                    "Werner");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Ada",
                                    "Adele",
                                    "Adriana",
                                    "Agnese",
                                    "Alessandra",
                                    "Alessia",
                                    "Alexandra",
                                    "Alice",
                                    "Aline",
                                    "Ana",
                                    "Andrea",
                                    "Angela",
                                    "Angelina",
                                    "Anita",
                                    "Anna",
                                    "Annamaria",
                                    "Antonella",
                                    "Antonia",
                                    "Antonietta",
                                    "Arianna",
                                    "Asia",
                                    "Aurora",
                                    "Barbara",
                                    "Beatrice",
                                    "Bianca",
                                    "Brigitte",
                                    "Bruna",
                                    "Camilla",
                                    "Carla",
                                    "Carmela",
                                    "Carmen",
                                    "Carolina",
                                    "Caterina",
                                    "Cecilia",
                                    "Chantal",
                                    "Chiara",
                                    "Christine",
                                    "Cinzia",
                                    "Clara",
                                    "Claudia",
                                    "Cristina",
                                    "Daniela",
                                    "Debora",
                                    "Deborah",
                                    "Denise",
                                    "Diana",
                                    "Dolores",
                                    "Donatella",
                                    "Doris",
                                    "Elda",
                                    "Elena",
                                    "Eleonora",
                                    "Eliana",
                                    "Elisa",
                                    "Elisabeth",
                                    "Elisabetta",
                                    "Elsa",
                                    "Emanuela",
                                    "Emilia",
                                    "Emma",
                                    "Enrica",
                                    "Erica",
                                    "Erika",
                                    "Ester",
                                    "Eva",
                                    "Fabiana",
                                    "Federica",
                                    "Fernanda",
                                    "Filomena",
                                    "Flavia",
                                    "Franca",
                                    "Francesca",
                                    "Gabriella",
                                    "Gaia",
                                    "Giada",
                                    "Gianna",
                                    "Giorgia",
                                    "Giovanna",
                                    "Giulia",
                                    "Giuliana",
                                    "Giuseppina",
                                    "Gloria",
                                    "Graziella",
                                    "Greta",
                                    "Ida",
                                    "Ilaria",
                                    "Ines",
                                    "Irene",
                                    "Iris",
                                    "Isabel",
                                    "Isabella",
                                    "Ivana",
                                    "Jacqueline",
                                    "Jennifer",
                                    "Jessica",
                                    "Jolanda",
                                    "Karin",
                                    "Katia",
                                    "Lara",
                                    "Laura",
                                    "Letizia",
                                    "Lia",
                                    "Lidia",
                                    "Liliana",
                                    "Lina",
                                    "Linda",
                                    "Lisa",
                                    "Loredana",
                                    "Lorena",
                                    "Lorenza",
                                    "Luana",
                                    "Lucia",
                                    "Luciana",
                                    "Luisa",
                                    "Manuela",
                                    "Mara",
                                    "Margherita",
                                    "Margrit",
                                    "Maria",
                                    "Mariangela",
                                    "Marianne",
                                    "Marie",
                                    "Mariella",
                                    "Marilena",
                                    "Marina",
                                    "Marisa",
                                    "Marta",
                                    "Martina",
                                    "Matilde",
                                    "Maura",
                                    "Melissa",
                                    "Michela",
                                    "Michelle",
                                    "Milena",
                                    "Mirella",
                                    "Miriam",
                                    "Monica",
                                    "Monika",
                                    "Morena",
                                    "Myriam",
                                    "Nadia",
                                    "Nathalie",
                                    "Nicole",
                                    "Nicoletta",
                                    "Nina",
                                    "Nives",
                                    "Noemi",
                                    "Nora",
                                    "Olga",
                                    "Ornella",
                                    "Pamela",
                                    "Paola",
                                    "Patricia",
                                    "Patrizia",
                                    "Pia",
                                    "Pierina",
                                    "Prisca",
                                    "Raffaella",
                                    "Renata",
                                    "Rita",
                                    "Roberta",
                                    "Romina",
                                    "Rosa",
                                    "Rosanna",
                                    "Rosmarie",
                                    "Ruth",
                                    "Sabina",
                                    "Sabrina",
                                    "Samantha",
                                    "Sandra",
                                    "Sara",
                                    "Sarah",
                                    "Serena",
                                    "Silvana",
                                    "Silvia",
                                    "Simona",
                                    "Sofia",
                                    "Sonia",
                                    "Sonja",
                                    "Sophie",
                                    "Stefania",
                                    "Susanna",
                                    "Susanne",
                                    "Tamara",
                                    "Tania",
                                    "Tatiana",
                                    "Teresa",
                                    "Tiziana",
                                    "Ursula",
                                    "Valentina",
                                    "Valeria",
                                    "Vanessa",
                                    "Vera",
                                    "Verena",
                                    "Veronica",
                                    "Virginia",
                                    "Vittoria",
                                    "Viviana",
                                    "Yvonne");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Agustoni",
                                    "Alberti",
                                    "Albertini",
                                    "Albisetti",
                                    "Ambrosini",
                                    "Antonini",
                                    "Balestra",
                                    "Balmelli",
                                    "Bassetti",
                                    "Bassi",
                                    "Baumann",
                                    "Beffa",
                                    "Belotti",
                                    "Beretta",
                                    "Bernasconi",
                                    "Berta",
                                    "Besomi",
                                    "Bettosini",
                                    "Bianchi",
                                    "Bianda",
                                    "Bizzozero",
                                    "Bonetti",
                                    "Botta",
                                    "Bottinelli",
                                    "Brunner",
                                    "Butti",
                                    "Caccia",
                                    "Campana",
                                    "Camponovo",
                                    "Candolfi",
                                    "Canepa",
                                    "Canonica",
                                    "Capoferri",
                                    "Carrara",
                                    "Casanova",
                                    "Cassina",
                                    "Castelli",
                                    "Cattaneo",
                                    "Cavadini",
                                    "Cavalli",
                                    "Ceppi",
                                    "Cereghetti",
                                    "Cerutti",
                                    "Chiesa",
                                    "Colombo",
                                    "Conti",
                                    "Corti",
                                    "Costa",
                                    "Crivelli",
                                    "Croci",
                                    "Delc\u00F2",
                                    "Delmenico",
                                    "Donati",
                                    "Esposito",
                                    "Ferrari",
                                    "Ferrazzini",
                                    "Ferretti",
                                    "Filippini",
                                    "Fischer",
                                    "Foglia",
                                    "Foletti",
                                    "Fontana",
                                    "Forni",
                                    "Frei",
                                    "Frey",
                                    "Frigerio",
                                    "Fumagalli",
                                    "Galfetti",
                                    "Galli",
                                    "Gamboni",
                                    "Genini",
                                    "Gerosa",
                                    "Ghirlanda",
                                    "Gianella",
                                    "Gianinazzi",
                                    "Gianini",
                                    "Giannini",
                                    "Gianola",
                                    "Gilardi",
                                    "Giovannini",
                                    "Giudici",
                                    "Gobbi",
                                    "Grandi",
                                    "Grassi",
                                    "Grossi",
                                    "Guerra",
                                    "Guglielmetti",
                                    "Guidotti",
                                    "Huber",
                                    "Jelmini",
                                    "Keller",
                                    "Lafranchi",
                                    "Leonardi",
                                    "Leoni",
                                    "Lepori",
                                    "Locatelli",
                                    "Lombardi",
                                    "Lombardo",
                                    "Lorenzetti",
                                    "Lucchini",
                                    "Lupi",
                                    "Lurati",
                                    "Maggetti",
                                    "Maggi",
                                    "Maggini",
                                    "Martinelli",
                                    "Martini",
                                    "Maspoli",
                                    "Mattei",
                                    "Medici",
                                    "Meier",
                                    "Meroni",
                                    "Meyer",
                                    "Milani",
                                    "Minotti",
                                    "Molinari",
                                    "Molteni",
                                    "Mombelli",
                                    "Monti",
                                    "Morandi",
                                    "Mordasini",
                                    "Moresi",
                                    "Moretti",
                                    "Morisoli",
                                    "Moro",
                                    "Moser",
                                    "M\u00FCller",
                                    "Nessi",
                                    "Notari",
                                    "Ortelli",
                                    "Pagani",
                                    "Pagnamenta",
                                    "Papa",
                                    "Pedrazzi",
                                    "Pedrazzini",
                                    "Pedrini",
                                    "Pedroni",
                                    "Peduzzi",
                                    "Pellanda",
                                    "Pellegrini",
                                    "Pelloni",
                                    "Pescia",
                                    "Pesenti",
                                    "Petrini",
                                    "Piffaretti",
                                    "Pini",
                                    "Polli",
                                    "Ponti",
                                    "Ponzio",
                                    "Poretti",
                                    "Pozzi",
                                    "Quadri",
                                    "Realini",
                                    "Regazzoni",
                                    "Rezzonico",
                                    "Rigamonti",
                                    "Righetti",
                                    "Rinaldi",
                                    "Riva",
                                    "Rizzi",
                                    "Robbiani",
                                    "Rodoni",
                                    "Romano",
                                    "Roncoroni",
                                    "Rosselli",
                                    "Rossetti",
                                    "Rossi",
                                    "Rossini",
                                    "Rusca",
                                    "Rusconi",
                                    "Russo",
                                    "Sala",
                                    "Sargenti",
                                    "Sartori",
                                    "Sassi",
                                    "Schmid",
                                    "Schneider",
                                    "Scolari",
                                    "Solari",
                                    "Solc\u00E0",
                                    "Soldati",
                                    "Soldini",
                                    "Steiner",
                                    "Storni",
                                    "Sulmoni",
                                    "Suter",
                                    "Taddei",
                                    "Tamagni",
                                    "Tettamanti",
                                    "Togni",
                                    "Tognola",
                                    "Valsangiacomo",
                                    "Vassalli",
                                    "Villa",
                                    "Vitali",
                                    "Weber",
                                    "Widmer",
                                    "Zanetti",
                                    "Zanini",
                                    "Zimmermann");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\it_CH\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames("firstNameFemale", "firstNameMale", "lastName")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/it_CH/Person.php")
                    .addExtendsClass("Faker\\Provider\\it_IT\\Person")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
