package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.es_ES.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.classes.StaticMethodUtils;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import com.runtimeconverter.runtime.passByReference.RuntimeArgsWithReferences;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;
import static com.runtimeconverter.runtime.ZVal.toStringR;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/es_ES/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\es_ES\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();

        @ConvertedMethod
        public Object suffix(RuntimeEnv env, Object... args) {
            return ZVal.assign(
                    StaticMethodUtils.accessUnknownLateStaticMethod(env, this, Person.class)
                            .method("randomElement")
                            .addReferenceArgs(new RuntimeArgsWithReferences())
                            .call(
                                    env.getRequestStaticProperties(
                                                    com.project
                                                            .convertedCode
                                                            .globalNamespace
                                                            .namespaces
                                                            .Faker
                                                            .namespaces
                                                            .Provider
                                                            .namespaces
                                                            .es_ES
                                                            .classes
                                                            .Person
                                                            .RequestStaticProperties
                                                            .class)
                                            .suffix)
                            .value());
        }

        @ConvertedMethod
        public Object dni(RuntimeEnv env, Object... args) {
            Object number = null;
            Object letter = null;
            number =
                    StaticMethodUtils.accessUnknownLateStaticMethod(env, this, Person.class)
                            .method("numerify")
                            .addReferenceArgs(new RuntimeArgsWithReferences())
                            .call("########")
                            .value();
            letter =
                    ZVal.assign(
                            env.getRequestStaticPropertiesReference(
                                            com.project
                                                    .convertedCode
                                                    .globalNamespace
                                                    .namespaces
                                                    .Faker
                                                    .namespaces
                                                    .Provider
                                                    .namespaces
                                                    .es_ES
                                                    .classes
                                                    .Person
                                                    .RequestStaticProperties
                                                    .class,
                                            "crcMap")
                                    .arrayGet(env, ZVal.modulus(number, 23)));
            return ZVal.assign(toStringR(number, env) + toStringR(letter, env));
        }
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object crcMap =
                ZVal.arrayFromList(
                        "T", "R", "W", "A", "G", "M", "Y", "F", "P", "D", "X", "B", "N", "J", "Z",
                        "S", "Q", "V", "H", "L", "C", "K", "E", "T");

        public Object maleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}} {{suffix}}",
                        "{{firstNameMale}} {{lastName}} {{suffix}}");

        public Object femaleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}} {{suffix}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}} {{suffix}}");

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aaron",
                                    "Adam",
                                    "Adri\u00E1n",
                                    "Aitor",
                                    "Alberto",
                                    "Aleix",
                                    "Alejandro",
                                    "Alex",
                                    "Alonso",
                                    "\u00C1lvaro",
                                    "Ander",
                                    "Andr\u00E9s",
                                    "\u00C1ngel",
                                    "Antonio",
                                    "Arnau",
                                    "Asier",
                                    "Biel",
                                    "Bruno",
                                    "Carlos",
                                    "C\u00E9sar",
                                    "Cristian",
                                    "Daniel",
                                    "Dario",
                                    "David",
                                    "Diego",
                                    "Eduardo",
                                    "Enrique",
                                    "Eric",
                                    "Erik",
                                    "Fernando",
                                    "Francisco",
                                    "Francisco Javier",
                                    "Gabriel",
                                    "Gael",
                                    "Gerard",
                                    "Gonzalo",
                                    "Guillem",
                                    "Guillermo",
                                    "H\u00E9ctor",
                                    "Hugo",
                                    "Ian",
                                    "Ignacio",
                                    "Iker",
                                    "Isaac",
                                    "Ismael",
                                    "Iv\u00E1n",
                                    "Izan",
                                    "Jaime",
                                    "Jan",
                                    "Javier",
                                    "Jes\u00FAs",
                                    "Joel",
                                    "Jon",
                                    "Jordi",
                                    "Jorge",
                                    "Jos\u00E9",
                                    "Jos\u00E9 Antonio",
                                    "Jos\u00E9 Manuel",
                                    "Juan",
                                    "Juan Jos\u00E9",
                                    "Leo",
                                    "Lucas",
                                    "Luis",
                                    "Manuel",
                                    "Marc",
                                    "Marco",
                                    "Marcos",
                                    "Mario",
                                    "Mart\u00EDn",
                                    "Mateo",
                                    "Miguel",
                                    "Miguel \u00C1ngel",
                                    "Nicol\u00E1s",
                                    "Oliver",
                                    "Omar",
                                    "Oriol",
                                    "\u00D3scar",
                                    "Pablo",
                                    "Pedro",
                                    "Pol",
                                    "Rafael",
                                    "Ra\u00FAl",
                                    "Rayan",
                                    "Roberto",
                                    "Rodrigo",
                                    "Rub\u00E9n",
                                    "Samuel",
                                    "Santiago",
                                    "Sa\u00FAl",
                                    "Sergio",
                                    "Unai",
                                    "V\u00EDctor",
                                    "Yago",
                                    "Yeray");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abril",
                                    "Adriana",
                                    "Africa",
                                    "Aina",
                                    "Ainara",
                                    "Ainhoa",
                                    "Aitana",
                                    "Alba",
                                    "Alejandra",
                                    "Alexandra",
                                    "Alexia",
                                    "Alicia",
                                    "Alma",
                                    "Ana",
                                    "Andrea",
                                    "Ane",
                                    "Angela",
                                    "Anna",
                                    "Ariadna",
                                    "Aroa",
                                    "Aya",
                                    "Beatriz",
                                    "Berta",
                                    "Blanca",
                                    "Candela",
                                    "Carla",
                                    "Carlota",
                                    "Carmen",
                                    "Carolina",
                                    "Celia",
                                    "Clara",
                                    "Claudia",
                                    "Cristina",
                                    "Daniela",
                                    "Diana",
                                    "Elena",
                                    "Elsa",
                                    "Emma",
                                    "Erika",
                                    "Eva",
                                    "F\u00E1tima",
                                    "Gabriela",
                                    "Helena",
                                    "In\u00E9s",
                                    "Irene",
                                    "Iria",
                                    "Isabel",
                                    "Jana",
                                    "Jimena",
                                    "Joan",
                                    "Julia",
                                    "Laia",
                                    "Lara",
                                    "Laura",
                                    "Leire",
                                    "Leyre",
                                    "Lidia",
                                    "Lola",
                                    "Luc\u00EDa",
                                    "Luna",
                                    "Malak",
                                    "Manuela",
                                    "Mar",
                                    "Mara",
                                    "Mar\u00EDa",
                                    "Marina",
                                    "Marta",
                                    "Mart\u00ED",
                                    "Martina",
                                    "Mireia",
                                    "Miriam",
                                    "Nadia",
                                    "Nahia",
                                    "Naia",
                                    "Naiara",
                                    "Natalia",
                                    "Nayara",
                                    "Nerea",
                                    "Nil",
                                    "Noa",
                                    "Noelia",
                                    "Nora",
                                    "Nuria",
                                    "Olivia",
                                    "Ona",
                                    "Paola",
                                    "Patricia",
                                    "Pau",
                                    "Paula",
                                    "Raquel",
                                    "Roc\u00EDo",
                                    "Salma",
                                    "Sandra",
                                    "Sara",
                                    "Silvia",
                                    "Sof\u00EDa",
                                    "Teresa",
                                    "Valentina",
                                    "Valeria",
                                    "Vega",
                                    "Vera",
                                    "Victoria",
                                    "Yaiza",
                                    "Zoe");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abad",
                                    "Abeyta",
                                    "Abrego",
                                    "Abreu",
                                    "Acevedo",
                                    "Acosta",
                                    "Acu\u00F1a",
                                    "Adame",
                                    "Adorno",
                                    "Agosto",
                                    "Aguado",
                                    "Aguayo",
                                    "Aguilar",
                                    "Aguilera",
                                    "Aguirre",
                                    "Alanis",
                                    "Alaniz",
                                    "Alarc\u00F3n",
                                    "Alba",
                                    "Alcala",
                                    "Alcar\u00E1z",
                                    "Alc\u00E1ntar",
                                    "Alejandro",
                                    "Alem\u00E1n",
                                    "Alfaro",
                                    "Alfonso",
                                    "Alicea",
                                    "Almanza",
                                    "Almar\u00E1z",
                                    "Almonte",
                                    "Alonso",
                                    "Alonzo",
                                    "Altamirano",
                                    "Alva",
                                    "Alvarado",
                                    "Amador",
                                    "Amaya",
                                    "Anaya",
                                    "Andreu",
                                    "Andr\u00E9s",
                                    "Anguiano",
                                    "Angulo",
                                    "Ant\u00F3n",
                                    "Aparicio",
                                    "Apodaca",
                                    "Aponte",
                                    "Arag\u00F3n",
                                    "Aranda",
                                    "Ara\u00F1a",
                                    "Arce",
                                    "Archuleta",
                                    "Arellano",
                                    "Arenas",
                                    "Arevalo",
                                    "Arguello",
                                    "Arias",
                                    "Armas",
                                    "Armend\u00E1riz",
                                    "Armenta",
                                    "Armijo",
                                    "Arredondo",
                                    "Arreola",
                                    "Arriaga",
                                    "Arribas",
                                    "Arroyo",
                                    "Arteaga",
                                    "Asensio",
                                    "Atencio",
                                    "Avil\u00E9s",
                                    "Ayala",
                                    "Baca",
                                    "Badillo",
                                    "Baeza",
                                    "Bahena",
                                    "Balderas",
                                    "Ballesteros",
                                    "Banda",
                                    "Barajas",
                                    "Barela",
                                    "Barrag\u00E1n",
                                    "Barraza",
                                    "Barrera",
                                    "Barreto",
                                    "Barrientos",
                                    "Barrios",
                                    "Barroso",
                                    "Batista",
                                    "Bautista",
                                    "Ba\u00F1uelos",
                                    "Becerra",
                                    "Beltr\u00E1n",
                                    "Benavides",
                                    "Benav\u00EDdez",
                                    "Benito",
                                    "Ben\u00EDtez",
                                    "Bermejo",
                                    "Berm\u00FAdez",
                                    "Bernal",
                                    "Berr\u00EDos",
                                    "Blanco",
                                    "Blasco",
                                    "Bl\u00E1zquez",
                                    "Bonilla",
                                    "Borrego",
                                    "Botello",
                                    "Bravo",
                                    "Briones",
                                    "Brise\u00F1o",
                                    "Brito",
                                    "Bueno",
                                    "Burgos",
                                    "Bustamante",
                                    "Bustos",
                                    "B\u00E1ez",
                                    "Betancourt",
                                    "Caballero",
                                    "Cabello",
                                    "Cabrera",
                                    "Cab\u00E1n",
                                    "Cadena",
                                    "Caldera",
                                    "Calder\u00F3n",
                                    "Calero",
                                    "Calvillo",
                                    "Calvo",
                                    "Camacho",
                                    "Camarillo",
                                    "Campos",
                                    "Canales",
                                    "Candelaria",
                                    "Cano",
                                    "Cant\u00FA",
                                    "Caraballo",
                                    "Carbajal",
                                    "Carballo",
                                    "Carbonell",
                                    "C\u00E1rdenas",
                                    "Cardona",
                                    "Carmona",
                                    "Caro",
                                    "Carranza",
                                    "Carrasco",
                                    "Carrasquillo",
                                    "Carrera",
                                    "Carrero",
                                    "Carretero",
                                    "Carre\u00F3n",
                                    "Carrillo",
                                    "Carri\u00F3n",
                                    "Carvajal",
                                    "Casado",
                                    "Casanova",
                                    "Casares",
                                    "Casas",
                                    "Casillas",
                                    "Casta\u00F1eda",
                                    "Casta\u00F1o",
                                    "Castellano",
                                    "Castellanos",
                                    "Castillo",
                                    "Castro",
                                    "Cas\u00E1rez",
                                    "Cavazos",
                                    "Cazares",
                                    "Ceballos",
                                    "Cedillo",
                                    "Ceja",
                                    "Centeno",
                                    "Cepeda",
                                    "Cerda",
                                    "Cervantes",
                                    "Cerv\u00E1ntez",
                                    "Chac\u00F3n",
                                    "Chapa",
                                    "Chavarr\u00EDa",
                                    "Ch\u00E1vez",
                                    "Cintr\u00F3n",
                                    "Cisneros",
                                    "Clemente",
                                    "Cobo",
                                    "Collado",
                                    "Collazo",
                                    "Colunga",
                                    "Col\u00F3n",
                                    "Concepci\u00F3n",
                                    "Conde",
                                    "Contreras",
                                    "Cordero",
                                    "Cornejo",
                                    "Corona",
                                    "Coronado",
                                    "Corral",
                                    "Corrales",
                                    "Correa",
                                    "Cort\u00E9s",
                                    "Cortez",
                                    "Cort\u00E9s",
                                    "Costa",
                                    "Cotto",
                                    "Covarrubias",
                                    "Crespo",
                                    "Cruz",
                                    "Cuellar",
                                    "Cuenca",
                                    "Cuesta",
                                    "Cuevas",
                                    "Curiel",
                                    "C\u00F3rdoba",
                                    "C\u00F3rdova",
                                    "De la Cruz",
                                    "De la Fuente",
                                    "De la Torre",
                                    "Del R\u00EDo",
                                    "Delacr\u00FAz",
                                    "Delafuente",
                                    "Delagarza",
                                    "Delao",
                                    "Delapaz",
                                    "Delarosa",
                                    "Delatorre",
                                    "Dele\u00F3n",
                                    "Delgadillo",
                                    "Delgado",
                                    "Delr\u00EDo",
                                    "Delvalle",
                                    "D\u00EDez",
                                    "Domenech",
                                    "Domingo",
                                    "Dom\u00EDnguez",
                                    "Dom\u00EDnquez",
                                    "Duarte",
                                    "Due\u00F1as",
                                    "Duran",
                                    "D\u00E1vila",
                                    "D\u00EDaz",
                                    "Echevarr\u00EDa",
                                    "Elizondo",
                                    "Enr\u00EDquez",
                                    "Escalante",
                                    "Escamilla",
                                    "Escobar",
                                    "Escobedo",
                                    "Escribano",
                                    "Escudero",
                                    "Esparza",
                                    "Espinal",
                                    "Espino",
                                    "Espinosa",
                                    "Espinoza",
                                    "Esquibel",
                                    "Esquivel",
                                    "Esteban",
                                    "Esteve",
                                    "Estrada",
                                    "Est\u00E9vez",
                                    "Exp\u00F3sito",
                                    "Fajardo",
                                    "Far\u00EDas",
                                    "Feliciano",
                                    "Fern\u00E1ndez",
                                    "Ferrer",
                                    "Fierro",
                                    "Figueroa",
                                    "Flores",
                                    "Fl\u00F3rez",
                                    "Fonseca",
                                    "Font",
                                    "Franco",
                                    "Fr\u00EDas",
                                    "Fuentes",
                                    "Gait\u00E1n",
                                    "Galarza",
                                    "Galindo",
                                    "Gallardo",
                                    "Gallego",
                                    "Gallegos",
                                    "Galv\u00E1n",
                                    "Gal\u00E1n",
                                    "Gamboa",
                                    "G\u00E1mez",
                                    "Gaona",
                                    "Garay",
                                    "Garc\u00EDa",
                                    "Garibay",
                                    "Garica",
                                    "Garrido",
                                    "Garza",
                                    "Gast\u00E9lum",
                                    "Gayt\u00E1n",
                                    "Gil",
                                    "Gimeno",
                                    "Gim\u00E9nez",
                                    "Gir\u00F3n",
                                    "Godoy",
                                    "God\u00EDnez",
                                    "Gonz\u00E1les",
                                    "Gonz\u00E1lez",
                                    "Gracia",
                                    "Granado",
                                    "Granados",
                                    "Griego",
                                    "Grijalva",
                                    "Guajardo",
                                    "Guardado",
                                    "Guerra",
                                    "Guerrero",
                                    "Guevara",
                                    "Guillen",
                                    "Gurule",
                                    "Guti\u00E9rrez",
                                    "Guzm\u00E1n",
                                    "G\u00E1lvez",
                                    "G\u00F3mez",
                                    "Haro",
                                    "Henr\u00EDquez",
                                    "Heredia",
                                    "Hern\u00E1ndes",
                                    "Hernando",
                                    "Hern\u00E1dez",
                                    "Hern\u00E1ndez",
                                    "Herrera",
                                    "Herrero",
                                    "Hidalgo",
                                    "Hinojosa",
                                    "Holgu\u00EDn",
                                    "Huerta",
                                    "Hurtado",
                                    "Ibarra",
                                    "Ib\u00E1\u00F1ez",
                                    "Iglesias",
                                    "Irizarry",
                                    "Izquierdo",
                                    "Jaime",
                                    "Jaimes",
                                    "Jaramillo",
                                    "Jasso",
                                    "Jim\u00E9nez",
                                    "Jim\u00EDnez",
                                    "Juan",
                                    "Jurado",
                                    "Ju\u00E1rez",
                                    "J\u00E1quez",
                                    "Laboy",
                                    "Lara",
                                    "Laureano",
                                    "Leal",
                                    "Lebr\u00F3n",
                                    "Ledesma",
                                    "Leiva",
                                    "Lemus",
                                    "Lerma",
                                    "Leyva",
                                    "Le\u00F3n",
                                    "Lim\u00F3n",
                                    "Linares",
                                    "Lira",
                                    "Llamas",
                                    "Llorente",
                                    "Loera",
                                    "Lomeli",
                                    "Longoria",
                                    "Lorente",
                                    "Lorenzo",
                                    "Lovato",
                                    "Loya",
                                    "Lozada",
                                    "Lozano",
                                    "Lucas",
                                    "Lucero",
                                    "Lucio",
                                    "Luevano",
                                    "Lugo",
                                    "Luis",
                                    "Luj\u00E1n",
                                    "Luna",
                                    "Luque",
                                    "L\u00E1zaro",
                                    "L\u00F3pez",
                                    "Macias",
                                    "Mac\u00EDas",
                                    "Madera",
                                    "Madrid",
                                    "Madrigal",
                                    "Maestas",
                                    "Maga\u00F1a",
                                    "Malave",
                                    "Maldonado",
                                    "Manzanares",
                                    "Manzano",
                                    "Marco",
                                    "Marcos",
                                    "Mares",
                                    "Marrero",
                                    "Marroqu\u00EDn",
                                    "Martos",
                                    "Mart\u00ED",
                                    "Mart\u00EDn",
                                    "Mart\u00EDnez",
                                    "Mar\u00EDn",
                                    "M\u00E1s",
                                    "Mascare\u00F1as",
                                    "Mata",
                                    "Mateo",
                                    "Mateos",
                                    "Matos",
                                    "Mat\u00EDas",
                                    "Maya",
                                    "Mayorga",
                                    "Medina",
                                    "Medrano",
                                    "Mej\u00EDa",
                                    "Melgar",
                                    "Mel\u00E9ndez",
                                    "Mena",
                                    "Menchaca",
                                    "Mendoza",
                                    "Men\u00E9ndez",
                                    "Meraz",
                                    "Mercado",
                                    "Merino",
                                    "Mesa",
                                    "Meza",
                                    "Miguel",
                                    "Mill\u00E1n",
                                    "Miramontes",
                                    "Miranda",
                                    "Mireles",
                                    "Mojica",
                                    "Molina",
                                    "Mondrag\u00F3n",
                                    "Monroy",
                                    "Montalvo",
                                    "Monta\u00F1ez",
                                    "Monta\u00F1o",
                                    "Montemayor",
                                    "Montenegro",
                                    "Montero",
                                    "Montes",
                                    "Montez",
                                    "Montoya",
                                    "Mora",
                                    "Moral",
                                    "Morales",
                                    "Mor\u00E1n",
                                    "Moreno",
                                    "Mota",
                                    "Moya",
                                    "Mungu\u00EDa",
                                    "Murillo",
                                    "Muro",
                                    "Mu\u00F1iz",
                                    "Mu\u00F1oz",
                                    "M\u00E1rquez",
                                    "M\u00E9ndez",
                                    "Naranjo",
                                    "Narv\u00E1ez",
                                    "Nava",
                                    "Navarrete",
                                    "Navarro",
                                    "Navas",
                                    "Nazario",
                                    "Negrete",
                                    "Negr\u00F3n",
                                    "Nev\u00E1rez",
                                    "Nieto",
                                    "Nieves",
                                    "Ni\u00F1o",
                                    "Noriega",
                                    "N\u00E1jera",
                                    "N\u00FA\u00F1ez",
                                    "Ocampo",
                                    "Ocasio",
                                    "Ochoa",
                                    "Ojeda",
                                    "Oliva",
                                    "Olivares",
                                    "Olivas",
                                    "Oliver",
                                    "Olivera",
                                    "Olivo",
                                    "Oliv\u00E1rez",
                                    "Olmos",
                                    "Olvera",
                                    "Ontiveros",
                                    "Oquendo",
                                    "Ordo\u00F1ez",
                                    "Ord\u00F3\u00F1ez",
                                    "Orellana",
                                    "Ornelas",
                                    "Orosco",
                                    "Orozco",
                                    "Orta",
                                    "Ortega",
                                    "Ort\u00EDz",
                                    "Osorio",
                                    "Otero",
                                    "Ozuna",
                                    "Pab\u00F3n",
                                    "Pacheco",
                                    "Padilla",
                                    "Padr\u00F3n",
                                    "Pagan",
                                    "Palacios",
                                    "Palomino",
                                    "Palomo",
                                    "Pantoja",
                                    "Pardo",
                                    "Paredes",
                                    "Parra",
                                    "Partida",
                                    "Pascual",
                                    "Pastor",
                                    "Pati\u00F1o",
                                    "Paz",
                                    "Pedraza",
                                    "Pedroza",
                                    "Pelayo",
                                    "Pel\u00E1ez",
                                    "Perales",
                                    "Peralta",
                                    "Perea",
                                    "Pereira",
                                    "Peres",
                                    "Pe\u00F1a",
                                    "Pichardo",
                                    "Pineda",
                                    "Pizarro",
                                    "Pi\u00F1a",
                                    "Pi\u00F1eiro",
                                    "Plaza",
                                    "Polanco",
                                    "Polo",
                                    "Ponce",
                                    "Pons",
                                    "Porras",
                                    "Portillo",
                                    "Posada",
                                    "Pozo",
                                    "Prado",
                                    "Preciado",
                                    "Prieto",
                                    "Puente",
                                    "Puga",
                                    "Puig",
                                    "Pulido",
                                    "P\u00E1ez",
                                    "P\u00E9rez",
                                    "Quesada",
                                    "Quezada",
                                    "Quintana",
                                    "Quintanilla",
                                    "Quintero",
                                    "Quiroz",
                                    "Qui\u00F1ones",
                                    "Qui\u00F1\u00F3nez",
                                    "Rael",
                                    "Ramos",
                                    "Ram\u00EDrez",
                                    "Ram\u00F3n",
                                    "Rangel",
                                    "Rasc\u00F3n",
                                    "Raya",
                                    "Razo",
                                    "Redondo",
                                    "Regalado",
                                    "Reina",
                                    "Rend\u00F3n",
                                    "Renter\u00EDa",
                                    "Requena",
                                    "Res\u00E9ndez",
                                    "Rey",
                                    "Reyes",
                                    "Reyna",
                                    "Reynoso",
                                    "Rico",
                                    "Riera",
                                    "Rinc\u00F3n",
                                    "Riojas",
                                    "Rivas",
                                    "Rivera",
                                    "Rivero",
                                    "Robledo",
                                    "Robles",
                                    "Roca",
                                    "Rocha",
                                    "Rodarte",
                                    "Rodrigo",
                                    "Rodr\u00EDguez",
                                    "Rodr\u00EDquez",
                                    "Roig",
                                    "Rojas",
                                    "Rojo",
                                    "Rold\u00E1n",
                                    "Rol\u00F3n",
                                    "Romero",
                                    "Romo",
                                    "Rom\u00E1n",
                                    "Roque",
                                    "Ros",
                                    "Rosa",
                                    "Rosado",
                                    "Rosales",
                                    "Rosario",
                                    "Rosas",
                                    "Roybal",
                                    "Rubio",
                                    "Rueda",
                                    "Ruelas",
                                    "Ruiz",
                                    "Ruvalcaba",
                                    "Ru\u00EDz",
                                    "R\u00EDos",
                                    "Saavedra",
                                    "Saiz",
                                    "Salas",
                                    "Salazar",
                                    "Salcedo",
                                    "Salcido",
                                    "Salda\u00F1a",
                                    "Saldivar",
                                    "Salgado",
                                    "Salinas",
                                    "Salvador",
                                    "Samaniego",
                                    "Sanabria",
                                    "S\u00E1nchez",
                                    "Sancho",
                                    "Sandoval",
                                    "Santacruz",
                                    "Santamar\u00EDa",
                                    "Santana",
                                    "Santiago",
                                    "Santill\u00E1n",
                                    "Santos",
                                    "Sanz",
                                    "Sarabia",
                                    "Sauceda",
                                    "Saucedo",
                                    "Sedillo",
                                    "Segovia",
                                    "Segura",
                                    "Sep\u00FAlveda",
                                    "Serna",
                                    "Serra",
                                    "Serrano",
                                    "Serrato",
                                    "Sevilla",
                                    "Sierra",
                                    "Silva",
                                    "Sim\u00F3n",
                                    "Sisneros",
                                    "Sola",
                                    "Solano",
                                    "Soler",
                                    "Soliz",
                                    "Solorio",
                                    "Solorzano",
                                    "Sol\u00EDs",
                                    "Soria",
                                    "Soriano",
                                    "Sosa",
                                    "Sotelo",
                                    "Soto",
                                    "Su\u00E1rez",
                                    "S\u00E1enz",
                                    "S\u00E1ez",
                                    "S\u00E1nchez",
                                    "Tafoya",
                                    "Tamayo",
                                    "Tamez",
                                    "Tapia",
                                    "Tejada",
                                    "Tejeda",
                                    "Tello",
                                    "Terrazas",
                                    "Ter\u00E1n",
                                    "Tijerina",
                                    "Tirado",
                                    "Toledo",
                                    "Toro",
                                    "Torres",
                                    "Tovar",
                                    "Trejo",
                                    "Trevi\u00F1o",
                                    "Trujillo",
                                    "T\u00E9llez",
                                    "T\u00F3rrez",
                                    "Ulibarri",
                                    "Ulloa",
                                    "Urbina",
                                    "Ure\u00F1a",
                                    "Uribe",
                                    "Urrutia",
                                    "Ur\u00EDas",
                                    "Vaca",
                                    "Valadez",
                                    "Valdez",
                                    "Valdivia",
                                    "Vald\u00E9s",
                                    "Valencia",
                                    "Valent\u00EDn",
                                    "Valenzuela",
                                    "Valero",
                                    "Valladares",
                                    "Valle",
                                    "Vallejo",
                                    "Valles",
                                    "Valverde",
                                    "Vanegas",
                                    "Varela",
                                    "Vargas",
                                    "Vega",
                                    "Vela",
                                    "Velasco",
                                    "Vel\u00E1squez",
                                    "Vel\u00E1zquez",
                                    "Venegas",
                                    "Vera",
                                    "Verdugo",
                                    "Verduzco",
                                    "Vergara",
                                    "Vicente",
                                    "Vidal",
                                    "Viera",
                                    "Vigil",
                                    "Vila",
                                    "Villa",
                                    "Villag\u00F3mez",
                                    "Villalba",
                                    "Villalobos",
                                    "Villalpando",
                                    "Villanueva",
                                    "Villar",
                                    "Villareal",
                                    "Villarreal",
                                    "Villase\u00F1or",
                                    "Villegas",
                                    "V\u00E1squez",
                                    "V\u00E1zquez",
                                    "V\u00E9lez",
                                    "V\u00E9liz",
                                    "Ybarra",
                                    "Y\u00E1\u00F1ez",
                                    "Zambrano",
                                    "Zamora",
                                    "Zamudio",
                                    "Zapata",
                                    "Zaragoza",
                                    "Zarate",
                                    "Zavala",
                                    "Zayas",
                                    "Zelaya",
                                    "Zepeda",
                                    "Z\u00FA\u00F1iga",
                                    "de Anda",
                                    "de Jes\u00FAs",
                                    "\u00C1guilar",
                                    "\u00C1lvarez",
                                    "\u00C1valos",
                                    "\u00C1vila");
                        });

        public Object titleMale = ZVal.arrayFromList("Sr.", "Dn.", "Dr.", "Lic.", "Ing.");

        public Object titleFemale = ZVal.arrayFromList("Sra.", "Srita.", "Dr.", "Lic.", "Ing.");

        public Object suffix = ZVal.arrayFromList("Hijo", "Segundo", "Tercero");
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\es_ES\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "crcMap",
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats",
                            "suffix",
                            "titleFemale",
                            "titleMale")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/es_ES/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
