package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.de_CH.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/de_CH/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .namespaces
                .de_DE
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\de_CH\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .namespaces
                    .de_DE
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Adolf",
                                    "Adrian",
                                    "Alain",
                                    "Albert",
                                    "Alessandro",
                                    "Alex",
                                    "Alexander",
                                    "Alfred",
                                    "Ali",
                                    "Alois",
                                    "Andrea",
                                    "Andreas",
                                    "Andrin",
                                    "Andr\u00E9",
                                    "Angelo",
                                    "Anton",
                                    "Antonio",
                                    "Armin",
                                    "Arnold",
                                    "Arthur",
                                    "Beat",
                                    "Benjamin",
                                    "Bernhard",
                                    "Bruno",
                                    "Carlo",
                                    "Carlos",
                                    "Christian",
                                    "Christoph",
                                    "Claudio",
                                    "Cyrill",
                                    "C\u00E9dric",
                                    "Damian",
                                    "Daniel",
                                    "Dario",
                                    "David",
                                    "Denis",
                                    "Diego",
                                    "Dieter",
                                    "Dominic",
                                    "Dominik",
                                    "Eduard",
                                    "Elia",
                                    "Elias",
                                    "Emil",
                                    "Eric",
                                    "Erich",
                                    "Ernst",
                                    "Erwin",
                                    "Eugen",
                                    "Fabian",
                                    "Fabio",
                                    "Felix",
                                    "Flavio",
                                    "Florian",
                                    "Francesco",
                                    "Frank",
                                    "Franz",
                                    "Friedrich",
                                    "Fritz",
                                    "Gabriel",
                                    "Georg",
                                    "Gerhard",
                                    "Gian",
                                    "Giovanni",
                                    "Giuseppe",
                                    "Guido",
                                    "Hans",
                                    "Hans-Peter",
                                    "Hanspeter",
                                    "Heinrich",
                                    "Heinz",
                                    "Herbert",
                                    "Hermann",
                                    "Hugo",
                                    "Ivan",
                                    "Ivo",
                                    "Jakob",
                                    "Jan",
                                    "Jean",
                                    "Joel",
                                    "Johann",
                                    "Johannes",
                                    "Jonas",
                                    "Jonathan",
                                    "Josef",
                                    "Jos\u00E9",
                                    "Jo\u00EBl",
                                    "Julian",
                                    "J\u00F6rg",
                                    "J\u00FCrg",
                                    "J\u00FCrgen",
                                    "Karl",
                                    "Kevin",
                                    "Kilian",
                                    "Klaus",
                                    "Konrad",
                                    "Kurt",
                                    "Lars",
                                    "Leandro",
                                    "Leo",
                                    "Leon",
                                    "Levin",
                                    "Livio",
                                    "Lorenz",
                                    "Loris",
                                    "Louis",
                                    "Luca",
                                    "Luigi",
                                    "Luis",
                                    "Lukas",
                                    "Manfred",
                                    "Manuel",
                                    "Marc",
                                    "Marcel",
                                    "Marco",
                                    "Mario",
                                    "Mark",
                                    "Marko",
                                    "Markus",
                                    "Martin",
                                    "Mathias",
                                    "Matteo",
                                    "Matthias",
                                    "Mauro",
                                    "Max",
                                    "Mehmet",
                                    "Michael",
                                    "Michel",
                                    "Michele",
                                    "Mike",
                                    "Moritz",
                                    "Nico",
                                    "Nicola",
                                    "Nicolas",
                                    "Niklaus",
                                    "Nils",
                                    "Noah",
                                    "Norbert",
                                    "Oliver",
                                    "Olivier",
                                    "Othmar",
                                    "Otto",
                                    "Pascal",
                                    "Patrick",
                                    "Patrik",
                                    "Paul",
                                    "Peter",
                                    "Philip",
                                    "Philipp",
                                    "Philippe",
                                    "Pius",
                                    "Rafael",
                                    "Rainer",
                                    "Ralf",
                                    "Ralph",
                                    "Ramon",
                                    "Raphael",
                                    "Remo",
                                    "Renato",
                                    "Ren\u00E9",
                                    "Reto",
                                    "Richard",
                                    "Robert",
                                    "Roberto",
                                    "Robin",
                                    "Roger",
                                    "Roland",
                                    "Rolf",
                                    "Roman",
                                    "Rudolf",
                                    "Salvatore",
                                    "Samuel",
                                    "Sandro",
                                    "Sascha",
                                    "Sebastian",
                                    "Severin",
                                    "Silvan",
                                    "Silvio",
                                    "Simon",
                                    "Stefan",
                                    "Stephan",
                                    "Sven",
                                    "Theodor",
                                    "Thomas",
                                    "Tim",
                                    "Timo",
                                    "Tobias",
                                    "Ulrich",
                                    "Urs",
                                    "Walter",
                                    "Werner",
                                    "Wilhelm",
                                    "Willi",
                                    "Willy",
                                    "Wolfgang",
                                    "Yannick",
                                    "Yves");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Adelheid",
                                    "Agnes",
                                    "Alessia",
                                    "Alexandra",
                                    "Alice",
                                    "Alina",
                                    "Aline",
                                    "Ana",
                                    "Andrea",
                                    "Angela",
                                    "Angelika",
                                    "Anita",
                                    "Anja",
                                    "Anna",
                                    "Annemarie",
                                    "Antonia",
                                    "Astrid",
                                    "Barbara",
                                    "Beatrice",
                                    "Beatrix",
                                    "Bernadette",
                                    "Bertha",
                                    "Bettina",
                                    "Brigitta",
                                    "Brigitte",
                                    "Carla",
                                    "Carmen",
                                    "Caroline",
                                    "Chantal",
                                    "Charlotte",
                                    "Chiara",
                                    "Christa",
                                    "Christina",
                                    "Christine",
                                    "Claudia",
                                    "Corina",
                                    "Corinne",
                                    "Cornelia",
                                    "C\u00E9line",
                                    "Daniela",
                                    "Deborah",
                                    "Denise",
                                    "Diana",
                                    "Dora",
                                    "Doris",
                                    "Dorothea",
                                    "Edith",
                                    "Elena",
                                    "Eliane",
                                    "Elisabeth",
                                    "Elsa",
                                    "Elsbeth",
                                    "Emma",
                                    "Erika",
                                    "Erna",
                                    "Esther",
                                    "Eva",
                                    "Eveline",
                                    "Fabienne",
                                    "Fiona",
                                    "Franziska",
                                    "Frieda",
                                    "Gabriela",
                                    "Gabriele",
                                    "Gertrud",
                                    "Gisela",
                                    "Hanna",
                                    "Hedwig",
                                    "Heidi",
                                    "Helena",
                                    "Helene",
                                    "Hildegard",
                                    "Ida",
                                    "Ingrid",
                                    "Irene",
                                    "Iris",
                                    "Irma",
                                    "Isabel",
                                    "Isabella",
                                    "Isabelle",
                                    "Jacqueline",
                                    "Jana",
                                    "Janine",
                                    "Jasmin",
                                    "Jeannette",
                                    "Jennifer",
                                    "Jessica",
                                    "Johanna",
                                    "Jolanda",
                                    "Judith",
                                    "Julia",
                                    "Karin",
                                    "Katharina",
                                    "Kathrin",
                                    "Katja",
                                    "Katrin",
                                    "Klara",
                                    "Lara",
                                    "Larissa",
                                    "Laura",
                                    "Lea",
                                    "Lena",
                                    "Leonie",
                                    "Lina",
                                    "Linda",
                                    "Lisa",
                                    "Liselotte",
                                    "Livia",
                                    "Lorena",
                                    "Luana",
                                    "Lucia",
                                    "Luzia",
                                    "Lydia",
                                    "Madeleine",
                                    "Magdalena",
                                    "Maja",
                                    "Manuela",
                                    "Mara",
                                    "Margareta",
                                    "Margaretha",
                                    "Margaritha",
                                    "Margrit",
                                    "Margrith",
                                    "Maria",
                                    "Marianna",
                                    "Marianne",
                                    "Marie",
                                    "Marina",
                                    "Marion",
                                    "Marlise",
                                    "Martha",
                                    "Martina",
                                    "Melanie",
                                    "Mia",
                                    "Michaela",
                                    "Michelle",
                                    "Mich\u00E8le",
                                    "Milena",
                                    "Miriam",
                                    "Mirjam",
                                    "Monica",
                                    "Monika",
                                    "Nadia",
                                    "Nadine",
                                    "Nadja",
                                    "Natalie",
                                    "Nathalie",
                                    "Nelly",
                                    "Nicole",
                                    "Nina",
                                    "Noemi",
                                    "Nora",
                                    "Patricia",
                                    "Patrizia",
                                    "Paula",
                                    "Petra",
                                    "Pia",
                                    "Priska",
                                    "Rahel",
                                    "Ramona",
                                    "Rebecca",
                                    "Regina",
                                    "Regula",
                                    "Renata",
                                    "Renate",
                                    "Rita",
                                    "Rosa",
                                    "Rosmarie",
                                    "Ruth",
                                    "Sabine",
                                    "Sabrina",
                                    "Sandra",
                                    "Sara",
                                    "Sarah",
                                    "Selina",
                                    "Seraina",
                                    "Sibylle",
                                    "Silvia",
                                    "Simone",
                                    "Sina",
                                    "Sonja",
                                    "Sophie",
                                    "Stefanie",
                                    "Stephanie",
                                    "Susanna",
                                    "Susanne",
                                    "Sylvia",
                                    "Tamara",
                                    "Tanja",
                                    "Therese",
                                    "Theresia",
                                    "Ursula",
                                    "Valentina",
                                    "Vanessa",
                                    "Vera",
                                    "Verena",
                                    "Veronika",
                                    "Yvonne");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Achermann",
                                    "Ackermann",
                                    "Aeschlimann",
                                    "Ammann",
                                    "Arnold",
                                    "Bachmann",
                                    "Baumann",
                                    "Baumgartner",
                                    "Beck",
                                    "Benz",
                                    "Berger",
                                    "Betschart",
                                    "Bieri",
                                    "Bischof",
                                    "Blaser",
                                    "Blum",
                                    "Bolliger",
                                    "Bosshard",
                                    "Brunner",
                                    "Bucher",
                                    "Burri",
                                    "B\u00E4rtschi",
                                    "B\u00F6sch",
                                    "B\u00FChler",
                                    "B\u00FChlmann",
                                    "B\u00FCrgi",
                                    "B\u00FCrki",
                                    "Christen",
                                    "Eberle",
                                    "Egger",
                                    "Egli",
                                    "Eichenberger",
                                    "Erni",
                                    "Eugster",
                                    "Fankhauser",
                                    "Fehr",
                                    "Fischer",
                                    "Flury",
                                    "Fl\u00FCckiger",
                                    "Frei",
                                    "Frey",
                                    "Friedli",
                                    "Frischknecht",
                                    "Fuchs",
                                    "Furrer",
                                    "F\u00E4ssler",
                                    "Gasser",
                                    "Gerber",
                                    "Giger",
                                    "Gisler",
                                    "Gloor",
                                    "Graber",
                                    "Graf",
                                    "Grob",
                                    "Gut",
                                    "Haas",
                                    "Haller",
                                    "Hartmann",
                                    "Hasler",
                                    "Hauser",
                                    "Heiniger",
                                    "Herzog",
                                    "Hess",
                                    "Hofer",
                                    "Hofmann",
                                    "Hofstetter",
                                    "Hostettler",
                                    "Huber",
                                    "Hug",
                                    "Hunziker",
                                    "H\u00E4fliger",
                                    "H\u00E4nni",
                                    "H\u00FCrlimann",
                                    "Imhof",
                                    "Iten",
                                    "Jenni",
                                    "Jost",
                                    "J\u00E4ggi",
                                    "Kaiser",
                                    "Kaufmann",
                                    "Keller",
                                    "Kessler",
                                    "Knecht",
                                    "Koch",
                                    "Kohler",
                                    "Koller",
                                    "Krebs",
                                    "Kuhn",
                                    "Kunz",
                                    "Kuster",
                                    "K\u00E4lin",
                                    "K\u00E4ser",
                                    "K\u00FCng",
                                    "Lang",
                                    "Lanz",
                                    "Lehmann",
                                    "Leuenberger",
                                    "Liechti",
                                    "Locher",
                                    "Lutz",
                                    "L\u00FCscher",
                                    "L\u00FCthi",
                                    "Marti",
                                    "Marty",
                                    "Mathis",
                                    "Mathys",
                                    "Maurer",
                                    "Meier",
                                    "Meister",
                                    "Merz",
                                    "Mettler",
                                    "Meyer",
                                    "Michel",
                                    "Moser",
                                    "M\u00E4der",
                                    "M\u00FCller",
                                    "Niederberger",
                                    "Nussbaumer",
                                    "N\u00E4f",
                                    "Odermatt",
                                    "Ott",
                                    "Peter",
                                    "Pfister",
                                    "Portmann",
                                    "Probst",
                                    "Reber",
                                    "Rohner",
                                    "Rohrer",
                                    "Roth",
                                    "R\u00F6thlisberger",
                                    "R\u00FCegg",
                                    "Schaub",
                                    "Scheidegger",
                                    "Schenk",
                                    "Scherrer",
                                    "Schmid",
                                    "Schmidt",
                                    "Schneider",
                                    "Schnyder",
                                    "Schuler",
                                    "Schumacher",
                                    "Schwab",
                                    "Schwarz",
                                    "Schweizer",
                                    "Sch\u00E4r",
                                    "Sch\u00E4rer",
                                    "Sch\u00FCpbach",
                                    "Sch\u00FCtz",
                                    "Seiler",
                                    "Senn",
                                    "Sieber",
                                    "Siegenthaler",
                                    "Siegrist",
                                    "Sigrist",
                                    "Sommer",
                                    "Stadelmann",
                                    "Stalder",
                                    "Staub",
                                    "Steffen",
                                    "Steiger",
                                    "Steiner",
                                    "Steinmann",
                                    "Stettler",
                                    "Stocker",
                                    "Stucki",
                                    "Studer",
                                    "Stutz",
                                    "St\u00F6ckli",
                                    "Suter",
                                    "Sutter",
                                    "Tanner",
                                    "Tobler",
                                    "Trachsel",
                                    "Ulrich",
                                    "Vogel",
                                    "Vogt",
                                    "Wagner",
                                    "Walker",
                                    "Walser",
                                    "Weber",
                                    "Wehrli",
                                    "Weibel",
                                    "Weiss",
                                    "Wenger",
                                    "Wicki",
                                    "Widmer",
                                    "Willi",
                                    "Wirth",
                                    "Wirz",
                                    "Wittwer",
                                    "Wolf",
                                    "Wyss",
                                    "W\u00FCthrich",
                                    "Zaugg",
                                    "Zbinden",
                                    "Zehnder",
                                    "Ziegler",
                                    "Zimmermann",
                                    "Zwahlen",
                                    "Z\u00FCrcher");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\de_CH\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames("firstNameFemale", "firstNameMale", "lastName")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/de_CH/Person.php")
                    .addExtendsClass("Faker\\Provider\\de_DE\\Person")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
