package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.en_ZA.classes;

import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Calculator.classes.Luhn;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.annotations.ConvertedParameter;
import com.runtimeconverter.runtime.classes.ClassConstantUtils;
import com.runtimeconverter.runtime.arrays.ZPair;
import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.project.convertedCode.globalNamespace.NamespaceGlobal;
import com.runtimeconverter.runtime.annotations.ConvertedMethod;
import static com.runtimeconverter.runtime.ZVal.toStringR;
import static com.runtimeconverter.runtime.ZVal.toObjectR;
import static com.runtimeconverter.runtime.ZVal.assignParameter;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/en_ZA/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    @ConvertedMethod
    @ConvertedParameter(
        index = 0,
        name = "birthdate",
        typeHint = "DateTime",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    @ConvertedParameter(
        index = 1,
        name = "citizen",
        defaultValue = "true",
        defaultValueType = "constant"
    )
    @ConvertedParameter(
        index = 2,
        name = "gender",
        defaultValue = "NULL",
        defaultValueType = "constant"
    )
    public Object idNumber(RuntimeEnv env, Object... args) {
        int runtimeConverterBreakCount;
        Object birthdate = assignParameter(args, 0, true);
        if (null == birthdate) {
            birthdate = ZVal.getNull();
        }
        Object citizen = assignParameter(args, 1, true);
        if (null == citizen) {
            citizen = true;
        }
        Object gender = assignParameter(args, 2, true);
        if (null == gender) {
            gender = ZVal.getNull();
        }
        Object birthDateString = null;
        Object raceDigit = null;
        Object genderDigit = null;
        Object citizenDigit = null;
        Object partialIdNumber = null;
        Object sequenceDigits = null;
        if (!ZVal.isTrue(birthdate)) {
            birthdate =
                    env.callMethod(
                            toObjectR(this).accessProp(this, env).name("generator").value(),
                            "dateTimeThisCentury",
                            Person.class);
        }

        birthDateString = env.callMethod(birthdate, "format", Person.class, "ymd");
        SwitchEnumType11 switchVariable11 =
                ZVal.getEnum(
                        NamespaceGlobal.strtolower.env(env).call(gender).value(),
                        SwitchEnumType11.DEFAULT_CASE,
                        SwitchEnumType11.DYNAMIC_TYPE_47,
                        ClassConstantUtils.getConstantValueLateStatic(env, this, "GENDER_FEMALE"),
                        SwitchEnumType11.DYNAMIC_TYPE_48,
                        ClassConstantUtils.getConstantValueLateStatic(env, this, "GENDER_MALE"));
        switch (switchVariable11) {
            case DYNAMIC_TYPE_47:
                genderDigit = runtimeStaticObject.numberBetween(env, 0, 4);
                break;
            case DYNAMIC_TYPE_48:
                genderDigit = runtimeStaticObject.numberBetween(env, 5, 9);
                break;
            case DEFAULT_CASE:
                genderDigit = runtimeStaticObject.numberBetween(env, 0, 9);
        }
        ;
        sequenceDigits =
                NamespaceGlobal.str_pad
                        .env(env)
                        .call(runtimeStaticObject.randomNumber(env, 3), 3, 0, 2)
                        .value();
        citizenDigit = ZVal.assign(ZVal.strictEqualityCheck(citizen, "===", true) ? "0" : "1");
        raceDigit = runtimeStaticObject.randomNumber(env, 1);
        partialIdNumber =
                toStringR(birthDateString, env)
                        + toStringR(genderDigit, env)
                        + toStringR(sequenceDigits, env)
                        + toStringR(citizenDigit, env)
                        + toStringR(raceDigit, env);
        return ZVal.assign(
                toStringR(partialIdNumber, env)
                        + toStringR(
                                Luhn.runtimeStaticObject.computeCheckDigit(env, partialIdNumber),
                                env));
    }

    public static final Object CONST_class = "Faker\\Provider\\en_ZA\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object maleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{firstNameMale}} {{lastName}}",
                        "{{titleMale}} {{firstNameMale}} {{lastName}}");

        public Object femaleNameFormats =
                ZVal.arrayFromList(
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{firstNameFemale}} {{lastName}}",
                        "{{titleFemale}} {{firstNameFemale}} {{lastName}}");

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abraham",
                                    "Adriaan",
                                    "Adrian",
                                    "Ahmed",
                                    "Alan",
                                    "Albert",
                                    "Alex",
                                    "Alexander",
                                    "Alfred",
                                    "Allan",
                                    "Andile",
                                    "Andre",
                                    "Andrew",
                                    "Andr\u00E9",
                                    "Anthony",
                                    "Anton",
                                    "Arnold",
                                    "Arthur",
                                    "Ayanda",
                                    "Barry",
                                    "Ben",
                                    "Benjamin",
                                    "Bernard",
                                    "Bongani",
                                    "Bradley",
                                    "Brandon",
                                    "Brent",
                                    "Brett",
                                    "Brian",
                                    "Bruce",
                                    "Bryan",
                                    "Carel",
                                    "Carl",
                                    "Charl",
                                    "Charles",
                                    "Chris",
                                    "Christiaan",
                                    "Christian",
                                    "Christo",
                                    "Christopher",
                                    "Clifford",
                                    "Clint",
                                    "Clinton",
                                    "Clive",
                                    "Colin",
                                    "Conrad",
                                    "Cornelius",
                                    "Craig",
                                    "Daniel",
                                    "Darren",
                                    "Dave",
                                    "David",
                                    "Dean",
                                    "Dennis",
                                    "Deon",
                                    "Derek",
                                    "Desmond",
                                    "Dirk",
                                    "Donald",
                                    "Donovan",
                                    "Douglas",
                                    "Edward",
                                    "Edwin",
                                    "Emmanuel",
                                    "Eric",
                                    "Ernest",
                                    "Etienne",
                                    "Eugene",
                                    "Francis",
                                    "Francois",
                                    "Frank",
                                    "Frans",
                                    "Frederick",
                                    "Gabriel",
                                    "Gareth",
                                    "Garth",
                                    "Gary",
                                    "Gavin",
                                    "George",
                                    "Gerald",
                                    "Gerhard",
                                    "Gerrit",
                                    "Gert",
                                    "Gideon",
                                    "Godfrey",
                                    "Gordon",
                                    "Graham",
                                    "Grant",
                                    "Greg",
                                    "Gregory",
                                    "Hannes",
                                    "Heinrich",
                                    "Hendrik",
                                    "Hennie",
                                    "Henry",
                                    "Herman",
                                    "Ian",
                                    "Innocent",
                                    "Isaac",
                                    "Itumeleng",
                                    "Ivan",
                                    "Jabulani",
                                    "Jaco",
                                    "Jacob",
                                    "Jacques",
                                    "James",
                                    "Jan",
                                    "Jason",
                                    "Jeffrey",
                                    "Jeremy",
                                    "Jerome",
                                    "Joe",
                                    "Johan",
                                    "Johann",
                                    "Johannes",
                                    "John",
                                    "Jonathan",
                                    "Joseph",
                                    "Juan",
                                    "Julian",
                                    "Justin",
                                    "Keith",
                                    "Kenneth",
                                    "Kevin",
                                    "Kgomotso",
                                    "Kobus",
                                    "Kyle",
                                    "Lawrence",
                                    "Lee",
                                    "Leon",
                                    "Leonard",
                                    "Lloyd",
                                    "Louis",
                                    "Lucas ",
                                    "Lucky",
                                    "Malcolm",
                                    "Mandla",
                                    "Marc",
                                    "Marco",
                                    "Mario",
                                    "Marius",
                                    "Mark",
                                    "Martin",
                                    "Matthew",
                                    "Mduduzi",
                                    "Michael",
                                    "Mike",
                                    "Mogamat",
                                    "Mohamed",
                                    "Mohammed",
                                    "Morne",
                                    "Morn\u00E9",
                                    "Moses",
                                    "Mr. ",
                                    "Muhammad",
                                    "Musa",
                                    "Nathan",
                                    "Neil",
                                    "Neo",
                                    "Neville",
                                    "Nicholas",
                                    "Nick",
                                    "Nico",
                                    "Nigel",
                                    "Nkululeko",
                                    "Norman",
                                    "Ntokozo",
                                    "Patrick",
                                    "Paul",
                                    "Peter",
                                    "Petrus",
                                    "Philip",
                                    "Phillip",
                                    "Pierre",
                                    "Pieter",
                                    "Prince",
                                    "Raymond",
                                    "Rene",
                                    "Ren\u00E9",
                                    "Riaan",
                                    "Ricardo",
                                    "Richard",
                                    "Rob",
                                    "Robert",
                                    "Rodney",
                                    "Roger",
                                    "Ronald",
                                    "Roy",
                                    "Rudi",
                                    "Russell",
                                    "Ryan",
                                    "Sam",
                                    "Samuel",
                                    "Sandile",
                                    "Sean",
                                    "Shane",
                                    "Shaun",
                                    "Shawn",
                                    "Sibusiso",
                                    "Simon",
                                    "Simone",
                                    "Simphiwe",
                                    "Siphiwe",
                                    "Sipho",
                                    "Siyabonga",
                                    "Sizwe",
                                    "Stanley",
                                    "Stefan",
                                    "Stephan",
                                    "Stephen",
                                    "Steve",
                                    "Steven",
                                    "Stuart",
                                    "Tebogo",
                                    "Terence",
                                    "Thabang",
                                    "Thabiso",
                                    "Thabo",
                                    "Thando",
                                    "Thapelo",
                                    "Themba",
                                    "Theo",
                                    "Thomas",
                                    "Timothy",
                                    "To ",
                                    "Tony",
                                    "Trevor",
                                    "Tshepo",
                                    "Tsholofelo",
                                    "Vernon",
                                    "Victor",
                                    "Vincent",
                                    "Walter",
                                    "Warren",
                                    "Wayne",
                                    "Werner",
                                    "Wesley",
                                    "Willem",
                                    "William",
                                    "Willie",
                                    "Wynand",
                                    "Xolani",
                                    "Yusuf",
                                    "andries",
                                    "barend",
                                    "contact",
                                    "dumisani",
                                    "jacobus",
                                    "kabelo",
                                    "kagiso",
                                    "karabo",
                                    "lesego",
                                    "marthinus",
                                    "mashudu",
                                    "next",
                                    "nhlanhla",
                                    "nicolaas",
                                    "nkosinathi",
                                    "personal",
                                    "sello",
                                    "sifiso",
                                    "takalani",
                                    "teboho",
                                    "thulani",
                                    "tumelo",
                                    "vusi",
                                    "your",
                                    "Andries",
                                    "Babalwa",
                                    "Barend",
                                    "Bulelwa",
                                    "Contact ",
                                    "Dumisani",
                                    "Fikile",
                                    "Jacobus",
                                    "Kabelo",
                                    "Kagiso",
                                    "Karabo",
                                    "Kelebogile",
                                    "Lesego",
                                    "Lindiwe",
                                    "Marthinus",
                                    "Mashudu",
                                    "Next",
                                    "Nhlanhla",
                                    "Nicolaas",
                                    "Nkosinathi",
                                    "Nompumelelo",
                                    "Nonhlanhla",
                                    "Nonkululeko",
                                    "Nosipho",
                                    "Nozipho",
                                    "Personal",
                                    "Phumzile",
                                    "Refiloe",
                                    "Sello",
                                    "Sibongile",
                                    "Sifiso",
                                    "Siphokazi",
                                    "Takalani",
                                    "Teboho",
                                    "Thandeka",
                                    "Thandi",
                                    "Thembi",
                                    "Thulani",
                                    "Tumelo",
                                    "Unathi",
                                    "Vusi",
                                    "Vuyokazi",
                                    "Yolandi",
                                    "Your",
                                    "Zandile");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Abigail",
                                    "Adele",
                                    "Alicia",
                                    "Alison",
                                    "Amanda",
                                    "Andiswa",
                                    "Andrea",
                                    "Angela",
                                    "Angelique",
                                    "Anita",
                                    "Anna",
                                    "Anne",
                                    "Anthea",
                                    "Antoinette",
                                    "Asanda",
                                    "Ashley",
                                    "Aubrey",
                                    "Barbara",
                                    "Belinda",
                                    "Beverley",
                                    "Bianca",
                                    "Boitumelo",
                                    "Bongiwe",
                                    "Brenda",
                                    "Bronwyn",
                                    "Busisiwe",
                                    "Candice",
                                    "Carla",
                                    "Carmen",
                                    "Carol",
                                    "Caroline",
                                    "Catherine",
                                    "Cecilia",
                                    "Celeste",
                                    "Chantal",
                                    "Chantel",
                                    "Chantelle",
                                    "Charlene",
                                    "Charlotte",
                                    "Charmaine",
                                    "Cheryl",
                                    "Christina",
                                    "Christine",
                                    "Cindy",
                                    "Claire",
                                    "Claudia",
                                    "Colleen",
                                    "Cynthia",
                                    "Danie",
                                    "Danielle",
                                    "Debbie",
                                    "Deborah",
                                    "Denise",
                                    "Desiree",
                                    "Diane",
                                    "Dimakatso",
                                    "Dineo",
                                    "Duduzile",
                                    "Elaine",
                                    "Elizabeth",
                                    "Estelle",
                                    "Esther ",
                                    "Faith",
                                    "Fatima",
                                    "Fiona",
                                    "Gail",
                                    "Gillian",
                                    "Gloria",
                                    "Grace",
                                    "Gugu",
                                    "Gugulethu",
                                    "Heather",
                                    "Heidi",
                                    "Helen",
                                    "Ingrid",
                                    "Irene",
                                    "Jackie",
                                    "Jacqueline",
                                    "Jane",
                                    "Janet",
                                    "Janine",
                                    "Jean",
                                    "Jeanette ",
                                    "Jennifer",
                                    "Jenny",
                                    "Jessica",
                                    "Johanna",
                                    "Joyce",
                                    "Juanita",
                                    "Judith",
                                    "Julia",
                                    "Julie",
                                    "Karen",
                                    "Karin",
                                    "Katlego",
                                    "Kelly",
                                    "Kim",
                                    "Laura",
                                    "Lauren",
                                    "Lebogang",
                                    "Lebohang",
                                    "Lee-ann",
                                    "Leigh",
                                    "Lerato",
                                    "Lesley",
                                    "Liezel",
                                    "Linda",
                                    "Lisa",
                                    "Lizelle",
                                    "Lorraine",
                                    "Louise",
                                    "Lungile",
                                    "Lydia",
                                    "Lynette",
                                    "Lynn",
                                    "Mandisa",
                                    "Mandy",
                                    "Margaret",
                                    "Maria",
                                    "Marlene",
                                    "Martha",
                                    "Mary",
                                    "Maureen",
                                    "Mbali",
                                    "Megan",
                                    "Melanie",
                                    "Melissa",
                                    "Michelle",
                                    "Miss",
                                    "Monica",
                                    "Monique",
                                    "Mpho",
                                    "Nadia",
                                    "Nadine",
                                    "Natalie",
                                    "Natasha",
                                    "Nicola",
                                    "Nicole",
                                    "Nicolene",
                                    "Nicolette",
                                    "Nokuthula",
                                    "Nomfundo",
                                    "Nomsa",
                                    "Nthabiseng",
                                    "Olivia",
                                    "Palesa",
                                    "Pamela",
                                    "Patience",
                                    "Patricia",
                                    "Pearl",
                                    "Phindile ",
                                    "Portia",
                                    "Precious",
                                    "Priscilla",
                                    "Prudence",
                                    "Rachel",
                                    "Rebecca",
                                    "Refilwe",
                                    "Robin",
                                    "Robyn",
                                    "Ronel",
                                    "Roxanne",
                                    "Ruth",
                                    "Samantha",
                                    "Sandra",
                                    "Sarah",
                                    "Shannon",
                                    "Sharon",
                                    "Shirley",
                                    "Sonja",
                                    "Stephanie",
                                    "Susan",
                                    "Sydney",
                                    "Sylvia",
                                    "Tania",
                                    "Tanya",
                                    "Taryn",
                                    "Tasneem",
                                    "Thato",
                                    "Theresa",
                                    "Tracey",
                                    "Tracy",
                                    "Tshegofatso",
                                    "Tshepiso",
                                    "Ursula",
                                    "Vanessa",
                                    "Veronica",
                                    "Victoria",
                                    "Wendy",
                                    "Yolanda",
                                    "Yvette",
                                    "Yvonne",
                                    "Zama",
                                    "Zanele",
                                    "Zelda",
                                    "babalwa",
                                    "bulelwa",
                                    "fikile",
                                    "kelebogile",
                                    "lindiwe",
                                    "nompumelelo",
                                    "nonhlanhla",
                                    "nonkululeko",
                                    "nosipho",
                                    "nozipho",
                                    "phumzile",
                                    "refiloe",
                                    "sibongile",
                                    "siphokazi",
                                    "thandeka",
                                    "thandi",
                                    "thembi",
                                    "unathi",
                                    "vuyokazi",
                                    "yolandi",
                                    "zandile",
                                    "Andries",
                                    "Babalwa",
                                    "Barend",
                                    "Bulelwa",
                                    "Contact ",
                                    "Dumisani",
                                    "Fikile",
                                    "Jacobus",
                                    "Kabelo",
                                    "Kagiso",
                                    "Karabo",
                                    "Kelebogile",
                                    "Lesego",
                                    "Lindiwe",
                                    "Marthinus",
                                    "Mashudu",
                                    "Next",
                                    "Nhlanhla",
                                    "Nicolaas",
                                    "Nkosinathi",
                                    "Nompumelelo",
                                    "Nonhlanhla",
                                    "Nonkululeko",
                                    "Nosipho",
                                    "Nozipho",
                                    "Personal",
                                    "Phumzile",
                                    "Refiloe",
                                    "Sello",
                                    "Sibongile",
                                    "Sifiso",
                                    "Siphokazi",
                                    "Takalani",
                                    "Teboho",
                                    "Thandeka",
                                    "Thandi",
                                    "Thembi",
                                    "Thulani",
                                    "Tumelo",
                                    "Unathi",
                                    "Vusi",
                                    "Vuyokazi",
                                    "Yolandi",
                                    "Your",
                                    "Zandile");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Naidoo",
                                    "Govender",
                                    "Pillay",
                                    "Smith",
                                    "Botha",
                                    "van der Merwe",
                                    "Jacobs",
                                    "Moodley",
                                    "Singh",
                                    "Ndlovu",
                                    "Dlamini",
                                    "Pretorius",
                                    "Williams",
                                    "Khumalo",
                                    "du Plessis",
                                    "Nkosi",
                                    "Coetzee",
                                    "Venter",
                                    "Nel",
                                    "Fourie",
                                    "Van Wyk",
                                    "Chetty",
                                    "Smit",
                                    "Kruger",
                                    "Van Zyl",
                                    "Sithole",
                                    "du Toit",
                                    "Adams",
                                    "van Niekerk",
                                    "Reddy",
                                    "Khan",
                                    "Meyer",
                                    "Mahlangu",
                                    "Abrahams",
                                    "Mokoena",
                                    "Erasmus",
                                    "Dube",
                                    "Louw",
                                    "Le Roux",
                                    "Steyn",
                                    "Tshabalala",
                                    "Swanepoel",
                                    "Naicker",
                                    "Marais",
                                    "Joubert",
                                    "Baloyi",
                                    "Petersen",
                                    "Davids",
                                    "Viljoen",
                                    "Maharaj",
                                    "Details",
                                    "Swart",
                                    "Radebe",
                                    "Potgieter",
                                    "van der Westhuizen",
                                    "Move",
                                    "Strydom",
                                    "Mkhize",
                                    "Olivier",
                                    "Du Preez",
                                    "Van Rooyen",
                                    "Brown",
                                    "Engelbrecht",
                                    "Oosthuizen",
                                    "Hendricks",
                                    "Ngwenya",
                                    "van der Walt",
                                    "Johnson",
                                    "Thomas",
                                    "Van Heerden",
                                    "Ngcobo",
                                    "de Beer",
                                    "Khoza",
                                    "Barnard",
                                    "Ferreira",
                                    "Muller",
                                    "Mazibuko",
                                    "Zulu",
                                    "Moyo",
                                    "Zwane",
                                    "Maseko",
                                    "Chauke",
                                    "Bezuidenhout",
                                    "De Villiers",
                                    "Jones",
                                    "Buthelezi",
                                    "Mthembu",
                                    "Jordaan",
                                    "Molefe",
                                    "Mofokeng",
                                    "Burger",
                                    "Visser",
                                    "Daniels",
                                    "Maluleke",
                                    "Pienaar",
                                    "Martin",
                                    "Cloete",
                                    "Prinsloo",
                                    "Mathebula",
                                    "Janse van Rensburg",
                                    "Grobler",
                                    "Wilson",
                                    "Ncube",
                                    "Gumede",
                                    "Ngobeni",
                                    "Moloi",
                                    "Kekana",
                                    "Mhlongo",
                                    "Mbatha",
                                    "Nxumalo",
                                    "Theron",
                                    "Snyman",
                                    "Phiri",
                                    "Sibiya",
                                    "Ntuli",
                                    "Van Den Berg",
                                    "Mabaso",
                                    "Bester",
                                    "Isaacs",
                                    "Labuschagne",
                                    "Jansen",
                                    "Pieterse",
                                    "Vorster",
                                    "De Wet",
                                    "Schoeman",
                                    "De Klerk",
                                    "Groenewald",
                                    "Sibanda",
                                    "Rossouw",
                                    "Van Rensburg",
                                    "Naidu",
                                    "De Jager",
                                    "van Staden",
                                    "Scheepers",
                                    "Nhlapo",
                                    "Nkuna",
                                    "Kotze",
                                    "Mtshali",
                                    "Modise",
                                    "Ismail",
                                    "Van Schalkwyk",
                                    "Padayachee",
                                    "Taylor",
                                    "Thompson",
                                    "Motaung",
                                    "Booysen",
                                    "Patel",
                                    "Harris",
                                    "Joseph",
                                    "Mthethwa",
                                    "Arendse",
                                    "Vilakazi",
                                    "Lombard",
                                    "Roberts",
                                    "Steenkamp",
                                    "Roux",
                                    "Gouws",
                                    "Botes",
                                    "De Kock",
                                    "Lewis",
                                    "James",
                                    "Mnisi",
                                    "Mohamed",
                                    "Africa",
                                    "Wessels",
                                    "Badenhorst",
                                    "Miller",
                                    "Hlongwane",
                                    "Hlatshwayo",
                                    "Vermeulen",
                                    "Kunene",
                                    "Liebenberg",
                                    "Alexander",
                                    "Mudau",
                                    "Myburgh",
                                    "van Tonder",
                                    "Hattingh",
                                    "Mhlanga",
                                    "Francis",
                                    "Mkhwanazi",
                                    "Basson",
                                    "Boshoff",
                                    "Scott",
                                    "Xaba",
                                    "De Lange",
                                    "Mphahlele",
                                    "Ebrahim",
                                    "Cele",
                                    "Matlala",
                                    "Beukes",
                                    "Coetzer",
                                    "Nkomo",
                                    "Ledwaba",
                                    "Ndaba",
                                    "Parker",
                                    "Els",
                                    "Green",
                                    "Mnguni",
                                    "Scholtz",
                                    "King",
                                    "Anderson",
                                    "Langa",
                                    "Mulaudzi",
                                    "Simelane",
                                    "Jackson",
                                    "Shabangu",
                                    "Mostert",
                                    "Dhlamini",
                                    "Geldenhuys",
                                    "Ngubane",
                                    "Skosana",
                                    "Bekker",
                                    "Phillips",
                                    "Brits",
                                    "Mahomed",
                                    "Human",
                                    "Peters",
                                    "George",
                                    "Cronje",
                                    "Sibeko",
                                    "Swartz",
                                    "Jooste",
                                    "Matthews",
                                    "Du Plooy",
                                    "Roos",
                                    "Van Vuuren",
                                    "Esterhuizen",
                                    "Masuku",
                                    "Mabunda",
                                    "Lawrence",
                                    "Moses",
                                    "Fisher",
                                    "Visagie",
                                    "Solomon",
                                    "Naude",
                                    "Gerber",
                                    "Campbell",
                                    "Lubbe",
                                    "Van Dyk",
                                    "Vermaak",
                                    "Kubheka",
                                    "Malan",
                                    "da Silva",
                                    "White",
                                    "Malatji",
                                    "Mashaba",
                                    "Edwards",
                                    "Banda",
                                    "Greyling",
                                    "Dreyer",
                                    "Hadebe",
                                    "Fredericks",
                                    "Mdluli",
                                    "Maritz",
                                    "Zondi",
                                    "Masemola",
                                    "Mabasa",
                                    "Fortuin",
                                    "Shabalala",
                                    "Bosman",
                                    "Brink",
                                    "Ndhlovu",
                                    "Moonsamy",
                                    "Mogale",
                                    "Tsotetsi",
                                    "Mabena",
                                    "Morris",
                                    "Mitchell",
                                    "Morgan",
                                    "Gordon",
                                    "Robinson",
                                    "Dladla",
                                    "Kriel",
                                    "Young",
                                    "Moloto",
                                    "Mabuza",
                                    "Richards",
                                    "Sibanyoni",
                                    "Stevens",
                                    "Pather",
                                    "Mngomezulu",
                                    "Masango",
                                    "Solomons",
                                    "Mlambo",
                                    "Shongwe",
                                    "Mthombeni",
                                    "Lourens",
                                    "Zungu",
                                    "Mamabolo",
                                    "Watson",
                                    "Opperman",
                                    "Stander",
                                    "Nair",
                                    "Twala",
                                    "Uys",
                                    "Letsoalo",
                                    "Clark",
                                    "Wright",
                                    "Mohlala",
                                    "Cupido",
                                    "Delport",
                                    "Sibisi",
                                    "Terblanche",
                                    "Motloung",
                                    "De Bruyn",
                                    "Davis",
                                    "Ndou",
                                    "Bothma",
                                    "Benjamin",
                                    "Jansen van Vuuren",
                                    "Rikhotso",
                                    "Majola",
                                    "Pietersen",
                                    "Mashego",
                                    "Herbst",
                                    "van Deventer",
                                    "Conradie",
                                    "Khanyile",
                                    "Msibi",
                                    "Mchunu",
                                    "Buys",
                                    "Malinga",
                                    "Britz",
                                    "Bailey",
                                    "Cilliers",
                                    "Goosen",
                                    "Walker",
                                    "Schutte",
                                    "Salie",
                                    "Samuels",
                                    "Davies",
                                    "Nkabinde",
                                    "Robertson",
                                    "Lee",
                                    "Perumal",
                                    "Mbele",
                                    "Greeff",
                                    "Brand",
                                    "Manuel",
                                    "Nyathi",
                                    "Kumar",
                                    "Moore",
                                    "Masilela",
                                    "Bell",
                                    "Mohale",
                                    "Hill",
                                    "Maree",
                                    "Ross",
                                    "Bouwer",
                                    "Ellis",
                                    "Kemp",
                                    "Mpofu",
                                    "Wood",
                                    "Stewart",
                                    "Ahmed",
                                    "Peter",
                                    "Slabbert",
                                    "Nortje",
                                    "Murray",
                                    "Van Aswegen",
                                    "De Bruin",
                                    "Collins",
                                    "Blignaut",
                                    "Van Der Berg",
                                    "Modiba",
                                    "Jonker",
                                    "Hall",
                                    "Mouton",
                                    "Allie",
                                    "Van Jaarsveld",
                                    "Minnaar",
                                    "Street",
                                    "Maake",
                                    "Zondo",
                                    "Koekemoer",
                                    "Koen",
                                    "Claassen",
                                    "Khosa",
                                    "Barnes",
                                    "Bosch",
                                    "Mncube",
                                    "Marx",
                                    "Ntombela",
                                    "Nell",
                                    "Makhubela",
                                    "Jansen van Rensburg",
                                    "Evans",
                                    "Clarke",
                                    "Strauss",
                                    "Mokone",
                                    "Moosa",
                                    "Neethling",
                                    "September",
                                    "Madonsela",
                                    "Willemse",
                                    "Mashigo",
                                    "Simpson",
                                    "Otto",
                                    "Legodi",
                                    "Mlangeni",
                                    "Mokwena",
                                    "Andrews",
                                    "Mashele",
                                    "Gounden",
                                    "Zuma",
                                    "Msomi",
                                    "Ngema",
                                    "Bennett",
                                    "Baker",
                                    "Ntshangase",
                                    "Nene",
                                    "Magagula",
                                    "Tladi",
                                    "Xulu",
                                    "M\u00FCller",
                                    "Laubscher",
                                    "Maluleka",
                                    "May",
                                    "Rautenbach",
                                    "Ndebele",
                                    "Grobbelaar",
                                    "Henning",
                                    "Carstens",
                                    "Maleka",
                                    "Odendaal",
                                    "Kok",
                                    "Oliver",
                                    "Cassim",
                                    "Van Eeden",
                                    "Lottering",
                                    "Mavuso",
                                    "Mashinini",
                                    "Kumalo",
                                    "Mathe",
                                    "Taljaard",
                                    "Molepo",
                                    "David",
                                    "Shezi",
                                    "Turner",
                                    "Oberholzer",
                                    "Motsepe",
                                    "Alberts",
                                    "Adonis",
                                    "van den Heever",
                                    "van der Linde",
                                    "Marshall",
                                    "Hugo",
                                    "Thwala",
                                    "Park",
                                    "Cooper",
                                    "Nelson",
                                    "John",
                                    "Anthony",
                                    "Adam",
                                    "Naud\u00E9",
                                    "Harrison",
                                    "Mulder",
                                    "Enslin",
                                    "Truter",
                                    "Khuzwayo",
                                    "Makhanya",
                                    "Harmse",
                                    "Loubser",
                                    "Kleynhans",
                                    "Paul",
                                    "Nieuwoudt",
                                    "Horn",
                                    "Vosloo",
                                    "Wentzel",
                                    "Munyai",
                                    "Kelly",
                                    "Walters",
                                    "Nzimande",
                                    "Hoosen",
                                    "Mkhabela",
                                    "Madlala",
                                    "Saunders",
                                    "Palmer",
                                    "Hughes",
                                    "Hanekom",
                                    "Ally",
                                    "Schmidt",
                                    "Butler",
                                    "Mtsweni",
                                    "Maphumulo",
                                    "Manamela",
                                    "Hoffman",
                                    "Wolmarans",
                                    "Duma",
                                    "Pule",
                                    "Hlophe",
                                    "Miya",
                                    "Moagi");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\en_ZA\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames(
                            "femaleNameFormats",
                            "firstNameFemale",
                            "firstNameMale",
                            "lastName",
                            "maleNameFormats")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/en_ZA/Person.php")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }

    private enum SwitchEnumType11 {
        DYNAMIC_TYPE_47,
        DYNAMIC_TYPE_48,
        DEFAULT_CASE,
        UNREACHABLE_CODE_N42
    }
}
