package com.project.convertedCode.globalNamespace.namespaces.Faker.namespaces.Provider.namespaces.fr_CH.classes;

import java.lang.invoke.MethodHandles;
import com.runtimeconverter.runtime.passByReference.PassByReferenceArgs;
import com.runtimeconverter.runtime.classes.NoConstructor;
import com.runtimeconverter.runtime.classes.RuntimeClassBase;
import com.runtimeconverter.runtime.RuntimeEnv;
import com.runtimeconverter.runtime.ZVal;
import com.runtimeconverter.runtime.reflection.ReflectionClassData;
import com.runtimeconverter.runtime.arrays.ZPair;

/*

 Converted with The Runtime Converter (runtimeconverter.com)

 vendor/fzaninotto/faker/src/Faker/Provider/fr_CH/Person.php

*/

public class Person
        extends com.project
                .convertedCode
                .globalNamespace
                .namespaces
                .Faker
                .namespaces
                .Provider
                .namespaces
                .fr_FR
                .classes
                .Person {

    public Person(RuntimeEnv env, Object... args) {
        super(env);
        if (this.getClass() == Person.class) {
            this.__construct(env, args);
        }
    }

    public Person(NoConstructor n) {
        super(n);
    }

    public static final Object CONST_class = "Faker\\Provider\\fr_CH\\Person";

    // Runtime Converter Internals
    // RuntimeStaticCompanion contains static methods
    // RequestStaticProperties contains static (per-request) properties
    // ReflectionClassData contains php reflection data used by the runtime library

    public static class RuntimeStaticCompanion
            extends com.project
                    .convertedCode
                    .globalNamespace
                    .namespaces
                    .Faker
                    .namespaces
                    .Provider
                    .namespaces
                    .fr_FR
                    .classes
                    .Person
                    .RuntimeStaticCompanion {

        private static final MethodHandles.Lookup staticCompanionLookup = MethodHandles.lookup();
    }

    public static final RuntimeStaticCompanion runtimeStaticObject = new RuntimeStaticCompanion();

    public static class RequestStaticProperties {

        public Object firstNameMale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Adrian",
                                    "Adrien",
                                    "Alain",
                                    "Albert",
                                    "Alberto",
                                    "Alessandro",
                                    "Alex",
                                    "Alexander",
                                    "Alexandre",
                                    "Alexis",
                                    "Alfred",
                                    "Ali",
                                    "Andrea",
                                    "Andr\u00E9",
                                    "Angelo",
                                    "Anthony",
                                    "Antoine",
                                    "Antonio",
                                    "Ant\u00F3nio",
                                    "Arnaud",
                                    "Arthur",
                                    "Aur\u00E9lien",
                                    "Axel",
                                    "Baptiste",
                                    "Bastien",
                                    "Benjamin",
                                    "Beno\u00EEt",
                                    "Bernard",
                                    "Bertrand",
                                    "Bruno",
                                    "Bryan",
                                    "Carlos",
                                    "Charles",
                                    "Christian",
                                    "Christophe",
                                    "Christopher",
                                    "Claude",
                                    "Claudio",
                                    "Cyril",
                                    "C\u00E9dric",
                                    "Damien",
                                    "Daniel",
                                    "David",
                                    "Denis",
                                    "Didier",
                                    "Diego",
                                    "Diogo",
                                    "Dominique",
                                    "Dylan",
                                    "Emmanuel",
                                    "Enzo",
                                    "Eric",
                                    "Etienne",
                                    "Fabien",
                                    "Fabio",
                                    "Fabrice",
                                    "Fernando",
                                    "Filipe",
                                    "Florian",
                                    "Francesco",
                                    "Francis",
                                    "Francisco",
                                    "Fran\u00E7ois",
                                    "Fr\u00E9d\u00E9ric",
                                    "Gabriel",
                                    "Georges",
                                    "Gilbert",
                                    "Gilles",
                                    "Giovanni",
                                    "Giuseppe",
                                    "Gregory",
                                    "Gr\u00E9goire",
                                    "Gr\u00E9gory",
                                    "Guillaume",
                                    "Guy",
                                    "G\u00E9rald",
                                    "G\u00E9rard",
                                    "Hans",
                                    "Henri",
                                    "Herv\u00E9",
                                    "Hugo",
                                    "Jacques",
                                    "Jean",
                                    "Jean-Claude",
                                    "Jean-Daniel",
                                    "Jean-Fran\u00E7ois",
                                    "Jean-Jacques",
                                    "Jean-Louis",
                                    "Jean-Luc",
                                    "Jean-Marc",
                                    "Jean-Marie",
                                    "Jean-Michel",
                                    "Jean-Paul",
                                    "Jean-Pierre",
                                    "Joao",
                                    "Joaquim",
                                    "John",
                                    "Jonas",
                                    "Jonathan",
                                    "Jorge",
                                    "Jose",
                                    "Joseph",
                                    "Jos\u00E9",
                                    "Jo\u00E3o",
                                    "Jo\u00EBl",
                                    "Juan",
                                    "Julien",
                                    "J\u00E9r\u00E9mie",
                                    "J\u00E9r\u00E9my",
                                    "J\u00E9r\u00F4me",
                                    "Kevin",
                                    "Laurent",
                                    "Lionel",
                                    "Loris",
                                    "Louis",
                                    "Lo\u00EFc",
                                    "Luc",
                                    "Luca",
                                    "Lucas",
                                    "Lucien",
                                    "Ludovic",
                                    "Luis",
                                    "L\u00E9o",
                                    "Manuel",
                                    "Marc",
                                    "Marcel",
                                    "Marco",
                                    "Mario",
                                    "Martin",
                                    "Mathias",
                                    "Mathieu",
                                    "Matteo",
                                    "Matthieu",
                                    "Maurice",
                                    "Max",
                                    "Maxime",
                                    "Michael",
                                    "Micha\u00EBl",
                                    "Michel",
                                    "Miguel",
                                    "Mohamed",
                                    "Nathan",
                                    "Nicolas",
                                    "Noah",
                                    "Nolan",
                                    "Nuno",
                                    "Olivier",
                                    "Pascal",
                                    "Patrice",
                                    "Patrick",
                                    "Paul",
                                    "Paulo",
                                    "Pedro",
                                    "Peter",
                                    "Philippe",
                                    "Pierre",
                                    "Pierre-Alain",
                                    "Pierre-Andr\u00E9",
                                    "Quentin",
                                    "Rafael",
                                    "Rapha\u00EBl",
                                    "Raymond",
                                    "Ren\u00E9",
                                    "Ricardo",
                                    "Richard",
                                    "Robert",
                                    "Roberto",
                                    "Robin",
                                    "Roger",
                                    "Roland",
                                    "Romain",
                                    "Rui",
                                    "R\u00E9my",
                                    "Sacha",
                                    "Salvatore",
                                    "Samuel",
                                    "Serge",
                                    "Sergio",
                                    "Simon",
                                    "Steve",
                                    "St\u00E9phane",
                                    "Sylvain",
                                    "S\u00E9bastien",
                                    "Thierry",
                                    "Thomas",
                                    "Th\u00E9o",
                                    "Tiago",
                                    "Valentin",
                                    "Victor",
                                    "Vincent",
                                    "Vitor",
                                    "Walter",
                                    "William",
                                    "Willy",
                                    "Xavier",
                                    "Yann",
                                    "Yannick",
                                    "Yvan",
                                    "Yves");
                        });

        public Object firstNameFemale =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Agn\u00E8s",
                                    "Alexandra",
                                    "Alice",
                                    "Alicia",
                                    "Aline",
                                    "Am\u00E9lie",
                                    "Ana",
                                    "Ana\u00EFs",
                                    "Andrea",
                                    "Andr\u00E9e",
                                    "Angela",
                                    "Anita",
                                    "Anna",
                                    "Anne",
                                    "Anne-Marie",
                                    "Antoinette",
                                    "Ariane",
                                    "Arlette",
                                    "Audrey",
                                    "Aur\u00E9lie",
                                    "Barbara",
                                    "Bernadette",
                                    "Brigitte",
                                    "B\u00E9atrice",
                                    "Camille",
                                    "Carine",
                                    "Carla",
                                    "Carmen",
                                    "Carole",
                                    "Caroline",
                                    "Catherine",
                                    "Chantal",
                                    "Charlotte",
                                    "Chlo\u00E9",
                                    "Christelle",
                                    "Christiane",
                                    "Christine",
                                    "Cindy",
                                    "Claire",
                                    "Clara",
                                    "Claudia",
                                    "Claudine",
                                    "Colette",
                                    "Coralie",
                                    "Corinne",
                                    "Cristina",
                                    "C\u00E9cile",
                                    "C\u00E9lia",
                                    "C\u00E9line",
                                    "Daniela",
                                    "Danielle",
                                    "Dani\u00E8le",
                                    "Delphine",
                                    "Denise",
                                    "Diana",
                                    "Dominique",
                                    "Edith",
                                    "Elena",
                                    "Eliane",
                                    "Elisa",
                                    "Elisabeth",
                                    "Elodie",
                                    "Elsa",
                                    "Emilie",
                                    "Emma",
                                    "Erika",
                                    "Estelle",
                                    "Esther",
                                    "Eva",
                                    "Evelyne",
                                    "Fabienne",
                                    "Fanny",
                                    "Florence",
                                    "Francine",
                                    "Fran\u00E7oise",
                                    "Gabrielle",
                                    "Genevi\u00E8ve",
                                    "Georgette",
                                    "Ginette",
                                    "Gis\u00E8le",
                                    "G\u00E9raldine",
                                    "Huguette",
                                    "H\u00E9l\u00E8ne",
                                    "In\u00E8s",
                                    "Ir\u00E8ne",
                                    "Isabel",
                                    "Isabelle",
                                    "Jacqueline",
                                    "Janine",
                                    "Jeanne",
                                    "Jeannine",
                                    "Jennifer",
                                    "Jessica",
                                    "Joana",
                                    "Jocelyne",
                                    "Josette",
                                    "Josiane",
                                    "Jo\u00EBlle",
                                    "Julia",
                                    "Julie",
                                    "Juliette",
                                    "Justine",
                                    "Karin",
                                    "Karine",
                                    "Katia",
                                    "Laetitia",
                                    "Lara",
                                    "Laura",
                                    "Laure",
                                    "Laurence",
                                    "Liliane",
                                    "Lisa",
                                    "Louise",
                                    "Lucia",
                                    "Lucie",
                                    "L\u00E9a",
                                    "Madeleine",
                                    "Magali",
                                    "Manon",
                                    "Manuela",
                                    "Marguerite",
                                    "Maria",
                                    "Marianne",
                                    "Marie",
                                    "Marie-Th\u00E9r\u00E8se",
                                    "Marina",
                                    "Marine",
                                    "Marion",
                                    "Marlyse",
                                    "Marl\u00E8ne",
                                    "Martine",
                                    "Mathilde",
                                    "Melissa",
                                    "Micheline",
                                    "Michelle",
                                    "Mich\u00E8le",
                                    "Mireille",
                                    "Monica",
                                    "Monique",
                                    "Morgane",
                                    "Muriel",
                                    "Myriam",
                                    "M\u00E9lanie",
                                    "Nadia",
                                    "Nadine",
                                    "Natacha",
                                    "Nathalie",
                                    "Nelly",
                                    "Nicole",
                                    "Nina",
                                    "No\u00E9mie",
                                    "Oc\u00E9ane",
                                    "Olga",
                                    "Olivia",
                                    "Pascale",
                                    "Patricia",
                                    "Paula",
                                    "Pauline",
                                    "Pierrette",
                                    "Rachel",
                                    "Raymonde",
                                    "Ren\u00E9e",
                                    "Rita",
                                    "Rosa",
                                    "Rose",
                                    "Rose-Marie",
                                    "Ruth",
                                    "Sabine",
                                    "Sabrina",
                                    "Sandra",
                                    "Sandrine",
                                    "Sara",
                                    "Sarah",
                                    "Silvia",
                                    "Simone",
                                    "Sofia",
                                    "Sonia",
                                    "Sophie",
                                    "St\u00E9phanie",
                                    "Suzanne",
                                    "Sylvia",
                                    "Sylviane",
                                    "Sylvie",
                                    "S\u00E9verine",
                                    "Tania",
                                    "Tatiana",
                                    "Teresa",
                                    "Th\u00E9r\u00E8se",
                                    "Valentine",
                                    "Val\u00E9rie",
                                    "Vanessa",
                                    "Victoria",
                                    "Virginie",
                                    "Viviane",
                                    "V\u00E9ronique",
                                    "Yolande",
                                    "Yvette",
                                    "Yvonne",
                                    "Zo\u00E9");
                        });

        public Object lastName =
                ZVal.arrayFromLambdaExpression(
                        /* Lambda can be removed if method size limit (64kb) is not an issue. */
                        () -> {
                            return ZVal.arrayFromList(
                                    "Aebischer",
                                    "Aeby",
                                    "Andrey",
                                    "Aubert",
                                    "Aubry",
                                    "Bachmann",
                                    "Baechler",
                                    "Baeriswyl",
                                    "Barbey",
                                    "Barras",
                                    "Baumann",
                                    "Baumgartner",
                                    "Berger",
                                    "Bernard",
                                    "Berset",
                                    "Bersier",
                                    "Berthoud",
                                    "Besson",
                                    "Blanc",
                                    "Blaser",
                                    "Boillat",
                                    "Bonvin",
                                    "Bourquin",
                                    "Bruchez",
                                    "Brunner",
                                    "Br\u00FCgger",
                                    "Buchs",
                                    "Bugnon",
                                    "Burri",
                                    "B\u00FChler",
                                    "Castella",
                                    "Cattin",
                                    "Chappuis",
                                    "Chapuis",
                                    "Chassot",
                                    "Chatelain",
                                    "Chevalley",
                                    "Chollet",
                                    "Christen",
                                    "Clerc",
                                    "Cl\u00E9ment",
                                    "Constantin",
                                    "Crausaz",
                                    "Da Silva",
                                    "Darbellay",
                                    "Demierre",
                                    "dos Santos",
                                    "Droz",
                                    "Dubois",
                                    "Dubuis",
                                    "Duc",
                                    "D\u00E9vaud",
                                    "Egger",
                                    "Emery",
                                    "Fasel",
                                    "Favre",
                                    "Fellay",
                                    "Fernandes",
                                    "Fernandez",
                                    "Ferreira",
                                    "Fischer",
                                    "Fleury",
                                    "Fl\u00FCckiger",
                                    "Fournier",
                                    "Fragni\u00E8re",
                                    "Froidevaux",
                                    "Gaillard",
                                    "Garcia",
                                    "Gasser",
                                    "Gay",
                                    "Geiser",
                                    "Genoud",
                                    "Gerber",
                                    "Gilli\u00E9ron",
                                    "Girard",
                                    "Girardin",
                                    "Giroud",
                                    "Glauser",
                                    "Golay",
                                    "Gonzalez",
                                    "Graf",
                                    "Grand",
                                    "Grandjean",
                                    "Gremaud",
                                    "Grosjean",
                                    "Gross",
                                    "Guex",
                                    "Guignard",
                                    "Hofer",
                                    "Hofmann",
                                    "Huber",
                                    "Huguenin",
                                    "H\u00E9ritier",
                                    "Jaccard",
                                    "Jacot",
                                    "Jaquet",
                                    "Jaquier",
                                    "Jeanneret",
                                    "Jordan",
                                    "Jungo",
                                    "Junod",
                                    "Kaufmann",
                                    "Keller",
                                    "Kohler",
                                    "Kolly",
                                    "Kunz",
                                    "Lachat",
                                    "Lambert",
                                    "Lehmann",
                                    "Leuba",
                                    "Leuenberger",
                                    "Liechti",
                                    "Lopez",
                                    "L\u00FCthi",
                                    "Maeder",
                                    "Magnin",
                                    "Maillard",
                                    "Maret",
                                    "Marti",
                                    "Martin",
                                    "Martinez",
                                    "Matthey",
                                    "Maurer",
                                    "Mauron",
                                    "Mayor",
                                    "Meier",
                                    "Meyer",
                                    "Meylan",
                                    "Michaud",
                                    "Michel",
                                    "Monnet",
                                    "Monney",
                                    "Monnier",
                                    "Morand",
                                    "Morard",
                                    "Morel",
                                    "Moret",
                                    "Moser",
                                    "Muller",
                                    "M\u00FCller",
                                    "Neuhaus",
                                    "Nguyen",
                                    "Nicolet",
                                    "Oberson",
                                    "Pache",
                                    "Pasche",
                                    "Pasquier",
                                    "Pereira",
                                    "Perez",
                                    "Perrenoud",
                                    "Perret",
                                    "Perrin",
                                    "Perroud",
                                    "Pfister",
                                    "Piguet",
                                    "Piller",
                                    "Pilloud",
                                    "Pittet",
                                    "Pochon",
                                    "Racine",
                                    "Rey",
                                    "Reymond",
                                    "Richard",
                                    "Robert",
                                    "Rochat",
                                    "Rodrigues",
                                    "Rodriguez",
                                    "Roduit",
                                    "Rosset",
                                    "Rossier",
                                    "Roth",
                                    "Rouiller",
                                    "Roulin",
                                    "Roy",
                                    "Ruffieux",
                                    "Savary",
                                    "Schaller",
                                    "Schmid",
                                    "Schmidt",
                                    "Schmutz",
                                    "Schneider",
                                    "Schwab",
                                    "Seydoux",
                                    "Simon",
                                    "Stalder",
                                    "Stauffer",
                                    "Steiner",
                                    "Studer",
                                    "Suter",
                                    "Tissot",
                                    "Vaucher",
                                    "Vonlanthen",
                                    "Vuilleumier",
                                    "Waeber",
                                    "Weber",
                                    "Wenger",
                                    "Widmer",
                                    "Wyss",
                                    "Zbinden",
                                    "Zimmermann");
                        });
    }

    private static final ReflectionClassData runtimeConverterReflectionData =
            ReflectionClassData.builder()
                    .setName("Faker\\Provider\\fr_CH\\Person")
                    .setLookup(
                            Person.class,
                            MethodHandles.lookup(),
                            RuntimeStaticCompanion.staticCompanionLookup)
                    .setLocalProperties("generator", "unique")
                    .setStaticPropertyNames("firstNameFemale", "firstNameMale", "lastName")
                    .setFilename("vendor/fzaninotto/faker/src/Faker/Provider/fr_CH/Person.php")
                    .addExtendsClass("Faker\\Provider\\fr_FR\\Person")
                    .addExtendsClass("Faker\\Provider\\Person")
                    .addExtendsClass("Faker\\Provider\\Base")
                    .get();

    @Override
    public ReflectionClassData getRuntimeConverterReflectionData() {
        return runtimeConverterReflectionData;
    }

    @Override
    public Object converterRuntimeCallExtended(
            RuntimeEnv env,
            String method,
            Class<?> caller,
            PassByReferenceArgs passByReferenceArgs,
            Object... args) {
        return RuntimeClassBase.converterRuntimeCallExtendedWithDataStatic(
                this,
                runtimeConverterReflectionData,
                env,
                method,
                caller,
                passByReferenceArgs,
                args);
    }
}
